### ISSUE TITLE
`nodeQuery` and `menuLinkContentQuery` by `url_alias`

### ISSUE THREAD

**Issue by johnmartin** [drupal-graphql/graphql#1]
I'm currently working on a headless Drupal site that is using the GraphQL module to provide data to a React frontend. However I'm beginning to get a little stuck.

Basically I've managed to run a query that get's the main menu items:

``` GraphQL
fragment menuFields on EntityMenuLinkContent {
  uuid
  title
  parent
  link {
    uri
  }
}

{
  main_menu: menuLinkContentQuery(menuName: "main") {
    ...menuFields
  }
}
```

Which is great for bootstrapping the menu on every page... BUT because within my Drupal instance I have URL aliases attached to nodes I'd really like to be able to return an alias if it's attached to `EntityMenuLinkContent` AND I'd really like to be able to run a `nodeQuery(urlAlias: '/example-route')`?

Any help pointing me in the right direction would be greatly appreciated as I'm a little stuck

**Comment by fubhy** [comment]
Hi. This is now possible in 3.x ... We are adding relay capabiliteis as well so that should work well with your React code-base. We are currently re-doing the entire schema so there is not much there yet but the entityByPath entry point is definitely part of what we are doing now.
