### ISSUE TITLE
How to install stable version

### ISSUE THREAD

**Issue by UrielNicolas** [drupal-graphql/graphql#1001]
I'm running composer require 'drupal/graphql:^3.0' but nothing happens, I get the message "nothing to install update".
I do have the alpha version, but I can't find a way to update the module. We haven't updated in a while, but nothing works, no composer update, or require.

**Comment by hirani89** [comment]
try adding --prefer-dist to your composer command. After you do that, check your composer.lock file. It will tell you what version is exactly installed.

**Comment by Kingdutch** [comment]
Hi Uriel,

I hope you've been able to install the module. If not, please open a new issue and provide any error output you may be getting.
