### ISSUE TITLE
Examples module doesn't throw error when limit is greater than MAX_LIMIT

### ISSUE THREAD

**Issue by anandtoshniwal** [drupal-graphql/graphql#1007]
In examples module’s  data producer  we have condition line 90
```
 if (!$limit > static::MAX_LIMIT) {
      throw new UserError(sprintf('Exceeded maximum query limit: %s.', static::MAX_LIMIT));
    }
```
If I pass 101 as limit to above query still I get the result back although MAX_LIMIT is set to 100
I think this condition should be like below
`if ($limit > static::MAX_LIMIT) {`
with above condition it throws an error if pass number greater than MAX_LIMIT

**Comment by Kingdutch** [comment]
Fixed in #1008
