### ISSUE TITLE
webonyx/graphql-php component not found

### ISSUE THREAD

**Issue by fer0ze** [drupal-graphql/graphql#1026]
Hi,

I'm getting this error (webonyx/graphql-php component not found) while activating graphql drupal module. No idea where to put this library in drupal. Anybody please help me.

Thanks

**Comment by bejes** [comment]
This should be included via composer when you add the module.

**Comment by Kingdutch** [comment]
Hi there,

As bejes mentioned the library should be installed automatically when you install the module. If that's not happening, please re-open the issue and provide more information about which version of the module is not working for you as well as how you're trying to install the module.
