### ISSUE TITLE
EntityQueryDeriver: $property->getMainPropertyName() return NULL value

### ISSUE THREAD

**Issue by xuxucode** [drupal-graphql/graphql#104]
field items such as `Drupal\Core\Field\Plugin\Field\FieldType\MapItem`, `Drupal\address\Plugin\Field\FieldType\AddressItem` has no main property, we should ignore them.

**Comment by fubhy** [comment]
Agreed. Do you want to submit a PR for that?

**Comment by xuxucode** [comment]
No, thanks, you can do that quickly :)
