### ISSUE TITLE
Persisted Query not caching

### ISSUE THREAD

**Issue by bejes** [drupal-graphql/graphql#1057]
Using latest branch with persisted queries (4.x)
I have enabled caching for the gql server. I have varnish running on port 80.
I have also tried setting cache-control headers in the request e.g max-age=600, public.
However i always get the response from drupal as "Cache-Control: must-revalidate, no-cache, private".
I thought it might development services.yml ...but disabled that and still get same result.
Example response below. 
curl -I --location --request GET 'etoll.local:8080/graphql?queryId=thesection'
HTTP/1.1 200 OK
Server: nginx/1.17.8
Date: Fri, 07 Aug 2020 06:35:54 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.2.30
**Cache-Control: must-revalidate, no-cache, private**
X-UA-Compatible: IE=edge
Content-language: en
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Drupal-Cache-Tags: config:graphql.graphql_servers.default config:user.role.anonymous graphql_response http_response node:1 node:10 node:3 node:4 node:5 node:6 node:7 node:8 node:9 node_list
X-Drupal-Cache-Contexts: languages:language_interface user.node_grants:view user.permissions
expires: -1
X-Generator: Drupal 8 (https://www.drupal.org)
Cache-Tags: config:graphql.graphql_servers.default config:user.role.anonymous graphql_response http_response node:1 node:10 node:3 node:4 node:5 node:6 node:7 node:8 node:9 node_list
pragma: no-cache

Any ideas on why drupal/graphql might be not caching this?

--Upon investigation, it seems the routes function in the route provider class is setting 'no_cache' to TRUE. 
This affects any servers added via the ui. Setting this to FALSE allows the response to be in fact cached. 
The page cache module does a check with $route->getOption('no_cache') and if this is true, the response will not be cached.
Not sure of the fix for this however or intended behaviour.

**Comment by Kingdutch** [comment]
I suspect this has been fixed in #1196 but if you still experience this, please re-open the issue :)
