### ISSUE TITLE
Some thoughts on EntityQuery

### ISSUE THREAD

**Issue by xuxucode** [drupal-graphql/graphql#106]
EntityQueryDeriver exposes many field arguments:
```graphql
nodeQuery(
  offset: Int
  limit: Int
  nid: Int
  uuid: String
  vid: Int
  langcode: String
  type: String
  status: GraphQLBoo
  title: String
  uid: Int
  created: String
  changed: String
  promote: GraphQLBoo
  sticky: GraphQLBoo
  revisionLog: String
  revisionTranslationAffected: GraphQLBoo
  defaultLangcode: GraphQLBoo
): [Node]!
```
Maybe we could only keep `offset` and `limit` arguments for `<entityType>Query`, and create another query like `entityPropertyQuery` for properties use.

At the end, we have two queries:

```graphql
nodeQuery(
  offset: Int
  limit: Int
): [Node]!
```

```graphql
entityPropertyQuery(
  offset: Int
  limit: Int
  type: EntityType!
  properties: String!
): [Entity]!
```

```graphql
enum EntityType {
  Node
  User
}
```
The `properties` argument is key-value pairs, like `nid=1,type=page`

In this way the GraphQL Schema looks more clean.

**Comment by pmelab** [comment]
Good point! But what about taking it one step further and use a generated `InputType` for properties? That way we get a cleaner interface (and remove possible name clashes with `limit` or `offset`), but keep type safety and autocompletion.

**Comment by fubhy** [comment]
I don't like the entityPropertyQuery returning EntityInterface. That doesn't make much sense imho simply because of the fact that EntityQuery doesn't work across different entity types.

I do, however, like the idea of putting the properties in an InputObjectType. So, what I'd like to see is this:

```graphql
nodeQuery(
  offset: Int
  limit: Int
  properties: NodePropertiesInput
): [Node]!
```

```graphql
NodePropertiesInput {
  nid: Int
  uuid: String
  vid: Int
  langcode: String
  type: String
  ...
}

**Comment by xuxucode** [comment]
Thanks, that's fine with me.

**Comment by fubhy** [comment]
Cool! Would you like to work on that?

**Comment by fubhy** [comment]
I also added a 'count' field to the entity query results now. Useful for implementing pagination.
