### ISSUE TITLE
Schema modularization

### ISSUE THREAD

**Issue by hirani89** [drupal-graphql/graphql#1068]
Hi,

Using v4

I have seven different content types with using multiple taxonomies.

Is it possible to extract the schema for all taxonomies in a separate file and import that to the schema of my content type?

**Comment by Kingdutch** [comment]
Hi @hirani89 ,

I hope you've been able to figure this out already, but if not, then [Schema Extensions](https://drupal-graphql.gitbook.io/graphql/advanced/composable-schemas#register-a-new-schema-extension) sounds like what you are looking for :D
