### ISSUE TITLE
Which version should I use for my Drupal 8.7?

### ISSUE THREAD

**Issue by searchmachine2001** [drupal-graphql/graphql#1095]
Hi,

I have Drupal 8.7 site.
I want to use this plugin.

Which version should I use? 3.x or 4.x?

Actually I might need to upgrade Drupal 8.7 to latest version at any time in future.
I do not want any mess in my graphQL functionality then.

Thanks.

**Comment by Kingdutch** [comment]
Hi @searchmachine2001 ,

I hope you've figured this out already. If not then the project page contains some information about the differences between 3.x and 4.x. If anything is unclear, please open an issue explaining what remaining questions you have. :)
