### ISSUE TITLE
Error while accessing explorer or executing a query

### ISSUE THREAD

**Issue by MarineW29** [drupal-graphql/graphql#1096]
Hello,

After a fresh install of :
- Drupal (version 8.9.6, installed via Docker, with PostgreSql database)
- graphql-php (via command "composer require webonyx/graphql-php")
- GraphQL and GraphQL Core (version 8.x-3.0)

I have the same error when I try :
- to open GraphQL Explorer
- to query an imported query map with an URL like : http://localhost:8080/graphql?queryId=b7cff04c7021094bcec1d38048d25a062ea39a93:1

Message displayed : The website encountered an unexpected error. Please try again later.

Can you help me resolving this problem please ?
(I already tried to clear all caches, no success)

Thanks in advance.
Marine

--------------------

Here are the corresponding logs :
Type	php
Date	Thursday, October 8, 2020 - 18:45
User	admin
Location	http://localhost:8080/graphql?queryId=b7cff04c7021094bcec1d38048d25a062ea39a93%3A1
Referrer	
Message	Error: Call to undefined method GraphQL\Server\ServerConfig::setDebug() in Drupal\graphql\Plugin\GraphQL\Schemas\SchemaPluginBase->getServer() (line 291 of /opt/drupal/web/modules/graphql/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php)
#0 /opt/drupal/web/modules/graphql/src/GraphQL/Execution/QueryProcessor.php(103): Drupal\graphql\Plugin\GraphQL\Schemas\SchemaPluginBase->getServer()
#1 /opt/drupal/web/modules/graphql/src/Controller/RequestController.php(82): Drupal\graphql\GraphQL\Execution\QueryProcessor->processQuery('default:default', Object(GraphQL\Server\OperationParams))
#2 /opt/drupal/web/modules/graphql/src/Controller/RequestController.php(70): Drupal\graphql\Controller\RequestController->handleSingle('default:default', Object(GraphQL\Server\OperationParams))
#3 [internal function]: Drupal\graphql\Controller\RequestController->handleRequest('default:default', Object(GraphQL\Server\OperationParams))
#4 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#5 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#6 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#7 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#8 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#9 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /opt/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /opt/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /opt/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#19 {main}
.
Severity	Error

Type	php
Date	Thursday, October 8, 2020 - 18:45
User	admin
Location	http://localhost:8080/graphql?queryId=b7cff04c7021094bcec1d38048d25a062ea39a93%3A1
Referrer	
Message	Notice: Trying to access array offset on value of type bool in Drupal\graphql\Routing\QueryRouteEnhancer->enhance() (line 36 of /opt/drupal/web/modules/graphql/src/Routing/QueryRouteEnhancer.php)
#0 /opt/drupal/web/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'Trying to acces...', '/opt/drupal/web...', 36, Array)
#1 /opt/drupal/web/modules/graphql/src/Routing/QueryRouteEnhancer.php(36): _drupal_error_handler(8, 'Trying to acces...', '/opt/drupal/web...', 36, Array)
#2 /opt/drupal/web/core/lib/Drupal/Core/Routing/Router.php(260): Drupal\graphql\Routing\QueryRouteEnhancer->enhance(Array, Object(Symfony\Component\HttpFoundation\Request))
#3 /opt/drupal/web/core/lib/Drupal/Core/Routing/Router.php(131): Drupal\Core\Routing\Router->applyRouteEnhancers(Array, Object(Symfony\Component\HttpFoundation\Request))
#4 /opt/drupal/web/core/lib/Drupal/Core/Routing/AccessAwareRouter.php(92): Drupal\Core\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#5 /opt/drupal/vendor/symfony/http-kernel/EventListener/RouterListener.php(113): Drupal\Core\Routing\AccessAwareRouter->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#6 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /opt/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(127): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#9 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /opt/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /opt/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /opt/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#19 {main}
.
Severity	Notice
Hostname	172.23.0.1
Operations	

------------------

GENERAL SYSTEM INFORMATION
 
Drupal Version
8.9.6
 
Web Server
Apache/2.4.38 (Debian)
 
PHP
Version
7.4.11 (more information)
Memory limit
128M
 
Database
Version
12.3 (Debian 12.3-1.pgdg100+1)
System
PostgreSQL

**Comment by prrenish** [comment]
Hi i also was facing the same issue and tried to debug the fix for it.

Try this cause it worked for me

drupal/modules/graphql/src/Entity/Server.php

![Screenshot from 2020-10-30 13-24-22](https://user-images.githubusercontent.com/45816962/97674438-894e2480-1ab3-11eb-9088-43bd63bad36d.png)

Note: Not the Best way to solve this error.

**Comment by MarineW29** [comment]
Hi prrenish,
Thanks for your reply.
I don't have this file Server.php in my install, but I will try to do something similar, based my error.

**Comment by MarineW29** [comment]
It works after commenting lines with "setDebug" or "getDebug" instructions :
/opt/drupal/web/modules/graphql/src/GraphQL/Execution/QueryProcessor.php : comment lines 157 to 159 ==> if ($config->getErrorFormatter() || $config->getDebug()) (...)
/opt/drupal/web/modules/graphql/src/GraphQL/Execution/QueryProcessor.php : comment lines 233 to 239 ==> if (!$config->getDebug() (...)
/opt/drupal/web/modules/graphql/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php : comment line 291 ==> $config->setDebug (...)

But as you said, prrenish, not really the best way...
Maybe somebody else have a better idea ?

**Comment by MarineW29** [comment]
I think I found the reason why I had this error.

When I first installed Drupal with the GraphQL module :
- I installed the module GraphQL through Drupal admin UI
- then I installed the missing dependance through the command line : composer require webonyx/graphql-php
I think it installed the wrong version of webonyx/graphql-php.

I just installed a new Drupal server, in a different way :
- I installed GraphQL (with its dependance) through the command line : composer require drupal/graphql

That way, I don't have error anymore when I open GraphQL explorer.

**Comment by zjlenovozj** [comment]
Call to undefined method GraphQL\Server\ServerConfig::setPersistentQueryLoader()

**Comment by tripodcreative** [comment]
For anyone experiencing this problem, there is a problem with the graphql installation. Simply remove drupal/graphql via composer or reinstall it via composer, and make sure to include the -W flag so it installs/upgrades all dependencies.
