### ISSUE TITLE
Graphql 4.x error while adding a new server using graphql create server interface.

### ISSUE THREAD

**Issue by Uttam-Pandey** [drupal-graphql/graphql#1097]
![image](https://user-images.githubusercontent.com/61231629/96114598-73f9c780-0f03-11eb-86e5-34d344bdadc6.png)
Only variables should be passed by reference in /app/web/modules/contrib/graphql/src/Form/ServerForm.php on line 95

**Comment by Uttam-Pandey** [comment]
[graphql.txt](https://github.com/drupal-graphql/graphql/files/5384303/graphql-patch.txt)

**Comment by Uttam-Pandey** [comment]
[graphql.txt](https://github.com/drupal-graphql/graphql/files/5384306/graphql.txt)

**Comment by Uttam-Pandey** [comment]
Here is the patch
[graphql-server.txt](https://github.com/drupal-graphql/graphql/files/5400870/graphql-server.txt)
:

**Comment by klausi** [comment]
This has been fixed in #1080 . Thanks for reporting!
