### ISSUE TITLE
Link fields / types by their plugin id, not by their name.

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#111]
Currently, we link fields to types and types to fields by using their names. This is problematic because it can cause ambiguity when there are two fields (for different types) with the same name in the plugin registry.

Thought @pmelab?

**Comment by pmelab** [comment]
This is intentional, since it allows overriding fields by name. Where is the ambiguity a problem?

**Comment by pmelab** [comment]
I see, when to types require a field with the same name. Yes, we have to resolve that.

**Comment by pmelab** [comment]
Perhaps we can use provider + id for lookups?

**Comment by pmelab** [comment]
Ok, after a night of sleep I've come to another conclusion. Please have a look at #113.

**Comment by pmelab** [comment]
Naming conflict has been resolved by removing explicit field annotations on types and interfaces.
