### ISSUE TITLE
[4.x] tap error : Unexpected token a in JSON at position 1 

### ISSUE THREAD

**Issue by bachy** [drupal-graphql/graphql#1133]
Hi, i'm trying to setup xdebug to be able to better understand what is happening in Resolvers but if i add tap it gives me an error
```php
$registry->addFieldResolver('Article', 'tags',
      $builder->compose(
        $builder->tap($builder->callback(function($parent, $args){
          echo('tags step 0');
        })),
        $builder->produce('entity_reference')
          ->map('entity', $builder->fromParent())
          ->map('field', $builder->fromValue('field_tags'))
      )
    );
```
```gql
{
  "message": "Unexpected token a in JSON at position 1",
  "stack": "SyntaxError: Unexpected token a in JSON at position 1"
}
```
this is running well without the tap

**Comment by bachy** [comment]
i manage to get xdebug working, but the error remains because of the echo
i close the issue obviously i removed the echo
but is it on purpose that you put a echo in the examples ?

**Comment by badrange** [comment]
This affected me too today, when I send the first graphql request I get the error, when I send the next request it shows normally. I opened Insomnia to see how this looks in another GraphQL client and yes drupal outputs `Composestep2.` in front of the opening bracket of the response.

**Comment by badrange** [comment]
This is not a bug, just wondering if a warning in the documentation might be helpful..
