### ISSUE TITLE
Is "use Drupal\graphql_core\Annotation\GraphQLType;" needed ?

### ISSUE THREAD

**Issue by scubafly** [drupal-graphql/graphql#118]
My php storm is complaining about GraphQLType not being imported.
Is this something we should add?

![entitybundle_php_-_aerius-monitor-drupal_-____sites_aerius-monitor-drupal_](https://cloud.githubusercontent.com/assets/820268/26308472/af73f9bc-3ef9-11e7-9548-b82e2248e546.png)

**Comment by fubhy** [comment]
That is not required anymore. See https://www.drupal.org/node/2096117
