### ISSUE TITLE
Best practice to make outbound graphql requests (Drupal as client not server)?

### ISSUE THREAD

**Issue by justclint** [drupal-graphql/graphql#1184]
Hi, Ive had a hard time finding information for making graqhql queries to external apis from Drupal. Everything seems to be about Drupal as a graphql server. 

I found this issue: https://github.com/drupal-graphql/graphql/issues/780 but seems the recommended service is no longer in v4 and after looking through https://github.com/drupal-graphql/graphql/blob/8.x-4.x/graphql.services.yml I didnt see anything obvious. 

Ive been able to successfully make graphql queries from Drupal using GuzzleHttp\Client but just doesnt feel so elegant so Im curious if there is a more recommended way or if this module provides a better interface for making graphql requests from Drupal.

Thanks!

**Comment by justclint** [comment]
Maybe a better way to ask this question is, if I store my queries in .graphql files, how do I call those to use them in my requests.

Currently im adding queries like this: 
```
    $query = <<<'GRAPHQL'
      query {
        someThing {
            id
        }
      }
    GRAPHQL;
```
but want to extract those to .graphql files so I can keep all the queries in one place.

If I store the queries in files, how can I call/include them?

**Comment by Kingdutch** [comment]
Hey @justclint ,

Doing GraphQL requests is outside of the scope of this module. However, you may look at the GraphQL library as they may provide this functionality and you could use that in your module directly.
