### ISSUE TITLE
Is the vulnerability fixed in 8.x-4.1 present in 8.x-3.x?

### ISSUE THREAD

**Issue by freelock** [drupal-graphql/graphql#1209]
https://www.drupal.org/sa-contrib-2021-013 disclosed a vulnerability that was patched in 8.x-4.1, but there is no information provided about whether 3.x is affected, and no new release for 3.x.

Upgrading from 3.x to 4.x is not trivial, due to the need to create all necessary schemas. Is the vulnerability present in 3.x?

**Comment by greggles** [comment]
From the private issue report I now see `This vulnerability exists in the 4.x version of the module, 3.x is not affected.` though it would be good to get the reporters/maintainers to confirm that here as well.

**Comment by klausi** [comment]
Confirmed, 8.x-3.x is not affected.

@greggles can you put that into the security advisory to avoid any confusion?

**Comment by greggles** [comment]
@klausi updated - let me know if you suggest different wording.

**Comment by klausi** [comment]
Looks good, thank you!
