### ISSUE TITLE
EntityDescription does not work with Taxonomy Terms

### ISSUE THREAD

**Issue by rudolfbyker** [drupal-graphql/graphql#1222]
To reproduce, pass a Taxonomy Term object to EntityDescription, like this:

```php
$registry->addFieldResolver(
  'ContributionRoleTerm',
  'description',
  $builder->produce('entity_description')->map('entity', $builder->fromParent())
);
```

It always lands on `return NULL`.

![image](https://user-images.githubusercontent.com/10025342/126330375-5cad6fc5-4745-4093-80a1-e60ddb5c6635.png)

![image](https://user-images.githubusercontent.com/10025342/126330438-ac593796-bcce-4713-af16-edec69f62657.png)

But `Term` objects do have descriptions:

![image](https://user-images.githubusercontent.com/10025342/126330500-f7a78e4d-93de-4047-90dc-2aed119a37dc.png)

**Comment by Kingdutch** [comment]
The use of the interface in the GraphQL module is correct. In this case the issue is that `Term` implements `getDescription` on its own interface rather than delegating to the `EntityDescriptionInterface`. The correct solution is for Drupal Core to improve the `TermInterface` implementation.

**Comment by rudolfbyker** [comment]
Do you know of a Drupal Core issue for this? (Lest I create a duplicate there...)
