### ISSUE TITLE
Two servers using the same schema, configured differently - only one works

### ISSUE THREAD

**Issue by darvanen** [drupal-graphql/graphql#1223]
I have a composable schema which defines 20-odd schema extensions.
I have two endpoints/servers configured differently (different sets of extensions) via the UI with different machine names and different paths.

After I refresh the cache, whichever server I make a request of first takes over the endpoint of the other one and it stays that way until the next cache refresh.

This doesn't occur on local where most if not all caches are turned off.

**Comment by darvanen** [comment]
I think perhaps the operation result is missing a cache context for the server:

![image](https://user-images.githubusercontent.com/5800400/126588665-2c8a73a6-6710-4102-9ed6-3daca8537261.png)

**Comment by darvanen** [comment]
Oh damn. schema_configuration is keyed by the schema id not the server id, and it's pulling the wrong server's schema before it instantiates the plugin.

**Comment by darvanen** [comment]
And that in turn appears to be because of some aggressive static caching in \GraphQL\Utils\SchemaExtender::extend

**Comment by darvanen** [comment]
Nope, it wasn't that, it was within the drupal module. This PR demonstrates where the schemas are being cached without respecting the server ID. Biggest problem I see here is the server ID isn't available to the plugin base in configuration.

https://github.com/drupal-graphql/graphql/pull/1224

**Comment by pfrenssen** [comment]
Created a corresponding drupal.org issue: https://www.drupal.org/project/graphql/issues/3491736

**Comment by klausi** [comment]
let's continue there!
