### ISSUE TITLE
DataProducerExecutionTrait::executeDataProducer() ignores defined default values

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#1233]
@pmelab @klausi I guess this is out of scope, but there seems to be an issue with the data producer argument default values.

For example, the `entity_reference` plugin definition sets a default value for `access` argument: https://github.com/drupal-graphql/graphql/blob/6961eac45de357a00637d927a4e4d0739487ebae/src/Plugin/GraphQL/DataProducer/Field/EntityReference.php#L46-L50

So I would guess that the `resolve` method never gets `null` for `$access` argument. Right?
 
However, it is typehinted as `?bool`: https://github.com/drupal-graphql/graphql/blob/6961eac45de357a00637d927a4e4d0739487ebae/src/Plugin/GraphQL/DataProducer/Field/EntityReference.php#L149

Then, when we call `DataProducerExecutionTrait::executeDataProducer()` without providing `access` argument, the data producer receives `access` as `null`. So it does not check the access, even if this should be the default behavior.

I would suggest:
- Remove `?` from data producer arguments having default values.
- Improve `DataProducerExecutionTrait::executeDataProducer()` to fill in default argument values.

_Originally posted by @Leksat in https://github.com/drupal-graphql/graphql/pull/1232#issuecomment-896749838_

**Comment by klausi** [comment]
Agreed, the `?bool $access` is really confusing. Even the variable name should have been $check_access.

Yep, we should use just `bool $access`. We cannot use `bool $access = TRUE` because there are other required parameters afterwards.

**Comment by klausi** [comment]
From my understanding our "default_value" in the annotation is not supported by Drupal core's context system.

2 options:
1. we keep the `?` optional operator on data producer parameters, since they will always receive NULL as default value.
2. we implement a better `getContextValues()` method in DataProducerPluginBase that handles default values.

I think option 2 should be doable.

**Comment by klausi** [comment]
Implemented option 2 in #1403

**Comment by edurenye** [comment]
If the MR has been merged, should we close this issue? Is all fixed?

**Comment by klausi** [comment]
yes, fixed!
