### ISSUE TITLE
Drupal\Core\Plugin\ContextAwarePluginBase is deprecated in drupal:9.1.0

### ISSUE THREAD

**Issue by animan01** [drupal-graphql/graphql#1250]
Hi,

In my unit test I got a notice with this:
` 1x: Drupal\Core\Plugin\ContextAwarePluginBase is deprecated in drupal:9.1.0 and will be removed before drupal:10.0.0. Instead, use \Drupal\Core\Plugin\ContextAwarePluginTrait. See https://www.drupal.org/node/3120980
`

Quick patch for fixing it:
[graphql-deprecated-ContextAwarePluginBase.patch.txt](https://github.com/drupal-graphql/graphql/files/7418857/graphql-deprecated-ContextAwarePluginBase.patch.txt)

But I think need to make a better decision.

**Comment by Kingdutch** [comment]
This has been fixed as part of https://github.com/drupal-graphql/graphql/commit/fa9764fb93284481cc4f3de1124e0a1f4c987176#diff-81e78d81b8f11cc9c33bad88ef5e2d03f4342bea1c5131c5b43fb18e09ffc3ab and https://github.com/drupal-graphql/graphql/commit/92d86825143824db4d94f8326158e6fc60fe4f53

:D
