### ISSUE TITLE
Symfony 4.4 event dispatcher parameter order change

### ISSUE THREAD

**Issue by tbsiqueira** [drupal-graphql/graphql#1251]
## Problem
Drupal 9 is now <a href="https://www.drupal.org/docs/understanding-drupal/how-drupal-9-is-made-and-what-is-included/what-changes-are-there-for-third#s-symfony-3-to-44" target="blank">using Symfony 4.4</a>, this version changed the parameters order of the <a href="https://symfony.com/doc/current/components/event_dispatcher.html#dispatch-the-event" target="blank">event dispatcher</a>.

## Solution
Invert the parameters order of <code>dispatch</code> calls.

**Comment by Kingdutch** [comment]
This was fixed in https://github.com/drupal-graphql/graphql/pull/1267 :)
