### ISSUE TITLE
Feature request: Automated, granular CRUD generation for new and existing content types.

### ISSUE THREAD

**Issue by laurencefass** [drupal-graphql/graphql#1285]
Ive just started using GraphQL so im picking it up at version 4.  Im entering into it using it with experience using the JSON:API and there appears to be a high coding requirement compared to JSON:API which automates exposure to entities through its API. i.e. I can automatically access content types through JSON:API REST interface without touching code.

The default functionality of graphql version 4 appears very limited in comparison. To improve future useability for site builders and administrators what do you think about the possibilities of the following features in future iterations of graphql core to give it some level of feature parity with JSON:API? Each item is a step-up in complexity and functionality with the final one offering features on par with JSON:API

1. Optional auto-generating schema for CRUD for new entities and content types via CLI or by configuration?
2. Optional auto-generating plugin code from schema via a CLI  or by configuration?
3. Automatic auto-generating CRUD + schema + plugin code for new entities and content types with no CLI and batch detection and generation of existing types on module installation.

These are just thoughts and initial impressions from a site builder/admin perspective to bring graphql useability to parity with JSON:API.

**Comment by Cryt1c** [comment]
Hi @laurencefass ,

you can follow and join the discussion on this topic [here](https://github.com/drupal-graphql/graphql/issues/1188) and [here](https://github.com/drupal-graphql/graphql/issues/1021)

**Comment by laurencefass** [comment]
thanks
