### ISSUE TITLE
Drupal 10 Readiness

### ISSUE THREAD

**Issue by balintpekker** [drupal-graphql/graphql#1299]
GraphQl's 8.x-4.x-dev branch is already Drupal 10 ready, however there are some issues reported by Upgrade status:

1. Call to deprecated method setMethods() of class PHPUnit\Framework\MockObject\MockBuilder:
- tests/src/Kernel/Framework/BufferedFieldTest.php:45
- tests/src/Kernel/Framework/DisabledResultCacheTest.php:50
- tests/src/Kernel/Framework/ResultCacheTest.php:42
- tests/src/Kernel/Framework/ResultCacheTest.php:68
- tests/src/Kernel/Framework/ResultCacheTest.php:84
- tests/src/Kernel/Framework/ResultCacheTest.php:113
- tests/src/Kernel/Framework/ResultCacheTest.php:129
- tests/src/Kernel/Framework/ResultCacheTest.php:158
- tests/src/Kernel/Framework/ResultCacheTest.php:187
- tests/src/Kernel/Framework/ResultCacheTest.php:203
- tests/src/Kernel/Framework/ResultCacheTest.php:263
- tests/src/Kernel/Framework/ResultCacheTest.php:279
- tests/src/Kernel/Framework/TestFrameworkTest.php:28
- tests/src/Traits/MockingTrait.php (in context of class Drupal\Tests\graphql\Kernel\GraphQLTestBase):128
- tests/src/Traits/MockingTrait.php (in context of class Drupal\Tests\graphql\Kernel\GraphQLTestBase):137

2. The '<name>' library is depending on a deprecated library. The core/jquery.once asset library is deprecated in Drupal 9.3.0 and will be removed in Drupal 10.0.0. Use the core/once library instead. See https://www.drupal.org/node/3158256:
- explorer
- voyager
- persisted_queries

**Comment by Kingdutch** [comment]
Fixed in #1300
