### ISSUE TITLE
Fatal error: Generators cannot return values using "return" in (...)/modules/contrib/graphql/modules/graphql_content/src/Plugin/GraphQL/Fields/RouteEntity.php on line 80

### ISSUE THREAD

**Issue by yann-yinn** [drupal-graphql/graphql#131]
Hello ! Thanks for your great work !
I got this message on my D8 site after installing this module. 

> Fatal error: Generators cannot return values using "return" in (...)/modules/contrib/graphql/modules/graphql_content/src/Plugin/GraphQL/Fields/RouteEntity.php on line 80

**Comment by pmelab** [comment]
Thanks!
