### ISSUE TITLE
PHP 5.6.29 : Parse error: syntax error, unexpected '$entity' (T_VARIABLE) in /Applications/MAMP/htdocs/jsonblog/modules/contrib/graphql/modules/graphql_menu/src/Plugin/GraphQL/Fields/MenuByName.php on line 57

### ISSUE THREAD

**Issue by yann-yinn** [drupal-graphql/graphql#132]
Hello, this fatal error with PHP 5.6.29

> Parse error: syntax error, unexpected '$entity' (T_VARIABLE) in /Applications/MAMP/htdocs/jsonblog/modules/contrib/graphql/modules/graphql_menu/src/Plugin/GraphQL/Fields/MenuByName.php on line 57

Either add PHP 7 as requirement on module page or use PHP5 syntax ? 
return (yield $entity)

**Comment by fubhy** [comment]
Save the planet! Use PHP7! But yeah... this should use PHP5 compatible  syntax.

**Comment by fubhy** [comment]
Thanks.
