### ISSUE TITLE
Parse Error in graphql_core entityquerycount.php on line 28

### ISSUE THREAD

**Issue by shawnmmatthews** [drupal-graphql/graphql#137]
Running into a parse error on Drupal 8.3.2 clean install.

Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /code/modules/graphql/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityQueryCount.php on line 28.

Just wanted to report it. Will attempt to debug and get back to this.

**Comment by pmelab** [comment]
Thanks! Looks like another PHP 5 incompatibility. You can't chain method calls directly on `clone`s. Works in PHP7.

**Comment by shawnmmatthews** [comment]
Awesome. That was it! Thanks. I was running from a docker environment and didn't even think to check php version.

**Comment by pmelab** [comment]
We have to fix it nonetheless, since 5.5.9 is Drupal's minimum requirement. Thanks for the catch!

Created a new issue: #140
