### ISSUE TITLE
[question] Example query to return Image attributes and Image Style

### ISSUE THREAD

**Issue by chuongle** [drupal-graphql/graphql#138]
I already enabled `graphql_image` and tried to follow the example query but could not return Image Style or attributes. I only have html return for my image field. Am I missing something for this functionality?

**Comment by pmelab** [comment]
In general, the field has to be exposed with the `image` field formatter in the `graphql` view mode.

The tests in `graphql_image` contain an example query:
https://github.com/fubhy/graphql-drupal/blob/8.x-3.x/modules/graphql_image/tests/queries/image.gql

I just discovered that the test doesn't cover the image derivative.

**Comment by chuongle** [comment]
@pmelab I actually followed that example. My Article Default View mode has field image render as image. This is how my query look:

```
query ($path: String!) {
  route:route(path: $path) {
    node:entity {
      fieldImage {
        alt
      }
    }
  }
}
```
With that simple query, I can't get the alt text to return. It only look at my fieldImage as String not object. I even tried with the following query but no luck.


```
query ($path: String!) {
  route:route(path: $path) {
    node:entity {
      ...on NodeArticle {
        fieldImage {
          alt
        }
      }
    }
  }
}
```

Am I missing something?

**Comment by chuongle** [comment]
@pmelab I understand what you mean now. I got it working. It actually answer part of my question on issue #134 as well. I will close this issue now.
