### ISSUE TITLE
Composer.json doesn't require drupal/typed_data. Typed Data module 1.0 is marked Unsupported.

### ISSUE THREAD

**Issue by mbomb007** [drupal-graphql/graphql#1412]
With the release of [Typed Data 2.1.0](https://www.drupal.org/project/typed_data/releases/2.1.0), the Typed Data API enhancements module removed support for 1.0@beta. I have a site using GraphQL, and Typed Data is installed, but it's not required by the GraphQL composer.json, so the Typed Data module isn't getting updated when I run `composer update --with-all-dependencies` (EDIT: it didn't work within the betas, but now that there's a new branch it works. Still, it is missing from composer.json), because I haven't required it explicitly in my site composer.json.

Does GraphQL depend on this module? It's listed in the info.yml file, but not in composer.json, so I think it should be added if needed, and make sure that the module works with version 2.1.0 of Typed Data, which is the only supported version now.

**Comment by klausi** [comment]
This has been fixed by #1407 , thanks for reporting!
