### ISSUE TITLE
Add schema validation and clean up step for missing types and empty types.

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#150]
We've run into this issue before and circumvented it because we added generic fields to all content entity types. However, we cannot really do that for input types and I am sure we will see this problem in other cases in the future too. I already talked this through with @pmelab a while ago: We could actually add a schema "clean-up" step that scans the schema for empty types (types without fields) and fields that have a non-existent type. While we run the clean up and remove empty types, we might obviously create such fields (fields that have a non-existent return type). Hence, this process needs to run recursively until no more empty types / non-existent fields remain. It's actually not too hard to implement this.

I am going to try to resolve this tomorrow.

**Comment by pmelab** [comment]
I'm still a little concerned that this might lead to very frustrating situations. We need idiot-proof reporting on what has been removed and why.
