### ISSUE TITLE
Idea: Root level "environment" field

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#151]
Using the API with e.g. Apollo has been troublesome because Drupal relies on a couple of global states (current language, current user, possibly the domain and potentially more), but Apollo expects to work with exactly one  endpoint. We managed to work around by doing full reloads when necessary (language/domain switch) and had to handle some SSR hiccups, but the solutions are not satisfying and there's a lot of potential for more problems.

What if we introduce a root level "environment" field with a return type that picks up all other root level fields. It could be used to *initialize* these global states for the enclosed query fragment. This could help with language negotiation and possibly caching and Drupal's states would fit more naturally in GraphQL based applications. 

Something like that:

```
query ($language: String!, $path: String!) {
  environment(language: $language) {
    route(path: $path) {
      ...
    }
  }
}
```

**Comment by fubhy** [comment]
I've done something similar before (but simply called it "root") in the relay schema we have been using for one of our clients (you know which). The field then set stuff in the query context. The youshido/graphql library has a so called "ExecutionContext" which contains a "container". This object gets passed to every field resolver). We could use this to set these values. It's basically just a key/value store.

**Comment by pmelab** [comment]
I'm thinking about the other way around. Not passing context into the query, but modifying Drupals state, like setting the current language when resolving "environment".

**Comment by fubhy** [comment]
I am not sure if that works because then you rely on no other stuff interfering with the global state at any point in time during the query execution. I'd rather like to see this as explicit context values in the executionContext container and have every resolver use these values. That way we can also make it easily extendable.
