### ISSUE TITLE
Simple Query example for entity fields (ex. title & body)

### ISSUE THREAD

**Issue by justinlevi** [drupal-graphql/graphql#154]
Based off the phpunit tests I was able to figure out the syntax easy enough for doing a simple query: 

```JSON5
{
  nodeById(id: "1") {
    nodeId
  }
}
```

Q: Why does the id need to be  string? This feels odd to me here, no?

This returned my single landing_page node, with the nid as expected. 

---

I struggled a bit to get the title and body fields though. Digging through the [Drupal Decoupled App](https://github.com/fubhy/drupal-decoupled-app), specifically in [frontend/app/.../components/ArticleTeaser/index.js](https://github.com/fubhy/drupal-decoupled-app/blob/master/frontend/app/screens/App/screens/ArticleOverview/components/ArticleTeaser/index.js#L39), I was able to find a working example I could modify for my case: 

```JSON5
fragment LandingPageTeaserFragment on NodeLandingPage {
  url:entityUrl {
    alias
  }

  title
  body
}

{
  nodeQuery(offset:0, limit:5){
    entities{
      entityId
      ...LandingPageTeaserFragment
    }
  }
}
```

And the slightly more concise version using inline fragments. 

```JSON5
{ 
  nodeQuery(offset:0, limit:5){
    entities{
      entityId
      ... on NodeLandingPage {
      	title
      	body
      }
    }
  }
}
```

What I'm wondering though, is this the correct way to handle this? I'm still super new to GraphQL and I'm wondering how to discover the syntax for such a simple query without having to dig through a working example. 

Totally understand that the module is still in development, and documentation is on the to-do-list... Any direction you can point me toward though, as far as a strategy for learning to write queries for GraphQL and Drupal, would be greatly appreciated. 

Also, I'd love to help on the documentation once I get my head wrapped around all of this. So far, I'm pretty excited about this project. Cheers!

**Comment by justinlevi** [comment]
Here's what I figured out doing a query for single node:

```JSON5
{ 
  nodeById(id: "1", language:en){
    entityLabel
    ... on NodeLandingPage {
      title
      body
    }
  }
}
```

Is a fragment required to get these fields? I guess I probably need to go back to the GraphQL spec and read up on fragments ;)

**Comment by justinlevi** [comment]
ahh, I think I might get it. We need to use fragments because GraphQL needs to actually perform two queries. One for the node, which doesn't actually return the entity fields, and another for the NodeLandingPage fields. The fragment instructs GraphQL to do a "join" on the secondary query into a single result set. Is this correct?

**Comment by kirkilj** [comment]
My desire to also help with the documentation was interrupted by my needing to find a paying job first, but as someone who has worked on other documentation projects over the years, I'd recommend that you keep a log of what you had to do with the current resources to find answers to your questions, as well as the solutions that worked for you. Once you do master the ins and outs of using GraphQL worth Drupal, you will have lost your innocence. There are a few different developer audiences that the documentation will need to address — those who know Drupal, but not GraphQL, and those who know GraphQL and are looking for a CMS.

**Comment by fubhy** [comment]
@justinlevi No, that's not the reason. We do not query "twice". Instead, GraphQL needs this information to be able to distinguish between the different types and interfaces.

Think of fragments and interface / object type-hints. By writing them out you can e.g. do stuff like this:

``gql
query {
  nodeById(id: 1) {
    entityId

    ... on NodeBasicPage {
      title
      body
      fieldSubheader { ... }
      fieldSomethingElseOnlyForBasicPage { ... }
    }

    ... on NodeArticle {
      title
      body
      fieldTags { ... }
      fieldSomethingElseOnlyForArticles { ... }
    }
  }
}``

That is like writing:

``php
$node = $storage->load(1);
if ($node->bundle() === 'page') {
  // Retrieve page specific fields.
} else if ($node->bundle() === 'article') {
  // Retrieve article specific fields.
}
``

``nodeById()`` returns an entity of type node, but before actually loading it we don't know what bundle / content type the node with the given id belongs to. We can then ask graphql "if this node is an article, do x, if it's a page, do y".

**Comment by fubhy** [comment]
@justinlevi Have you visited the /graphql/explorer path in your drupal backend? It should give you a GUI for exploring your schema including typeaheads / autocompletion. That's usually the best way to write and test qureies before copying them to your app code.

**Comment by justinlevi** [comment]
@fubhy Yes, I am writing the queries via the explorer but the syntax and introspection is not always intuitive for me yet. 

@kirkilj I think you make a very good point. I really need to document my process as I learn the process. 

Thanks all for your help!
