### ISSUE TITLE
Example: How to query for a user's email address & user entity reference on a node

### ISSUE THREAD

**Issue by justinlevi** [drupal-graphql/graphql#155]
I'm looking for an example of how to query for a user's (author) email address that is associated to a node. So far I'm striking out. Thanks.

**Comment by fubhy** [comment]
That is currently not (yet) possible. It's definitely something we will be adding though. One step in that direction is this: https://github.com/fubhy/graphql-drupal/pull/133.

Considering that the "uid" property on Node is not a field with a configurable field display formatter we might need to think of something else to solve it.

/cc @pmelab

**Comment by pmelab** [comment]
Will #133 allow entity reference traversal? Or will we just get the author's uid?

#82 will provide the tooling for this. You could create a "authors" view that takes a node as contextual argument and lists the users.

Without waiting for anything to be finished:
GraphQL also picks up extra fields. You should be able to use [Display Suite](http://drupal.org/project/ds) and configure a custom field that spits out the authors email. I didn't try this, but I'm interested if this actually works 😄

**Comment by fubhy** [comment]
You can now do this through the "EntityOwner" property.
