### ISSUE TITLE
Function parameters mismatch

### ISSUE THREAD

**Issue by xuxucode** [drupal-graphql/graphql#156]
The parameters of a [$this->getCacheDependencies($value, $args, $result))](https://github.com/fubhy/graphql-drupal/blob/8.x-3.x/modules/graphql_core/src/GraphQL/FieldPluginBase.php#L32) call in `FieldPluginBase` don't match parameters of the function [FieldPluginBase::getCacheDependencies($result, $value, array $args)](https://github.com/fubhy/graphql-drupal/blob/8.x-3.x/modules/graphql_core/src/GraphQL/FieldPluginBase.php#L57).

Maybe:

```patch
 public function resolve($value, array $args, ResolveInfo $info) {
   $result = iterator_to_array($this->resolveValues($value, $args, $info));
   if ($this->getPluginDefinition()['multi']) {
-    return new CacheableValue($result, $this->getCacheDependencies($value, $args, $result));
+    return new CacheableValue($result, $this->getCacheDependencies($result, $value, $args));
   }
```

It's an intention or a typo?

**Comment by fubhy** [comment]
Looks weird indeed. Can you submit a PR so we can see how that affects the tests? Our test coverage on the caching functionality is not very solid. But yes, it should be $result, $value, $args.

**Comment by xuxucode** [comment]
PR #158
