### ISSUE TITLE
Route query not respecting Node Access

### ISSUE THREAD

**Issue by pavlosdan** [drupal-graphql/graphql#162]
Unsure if this is by design or if it is a bug but when I run a query using a Node Query such as the following:
`{
  nodeQuery(offset:0, limit:1, filter: {nid: 16}) {
    entities {
      id:entityId
      title:entityLabel
      type:entityType
      bundle:entityBundle
    }
  }
}`
Node access rules seem to be respected as I do not get any of the node details (the node is unpublished).

If though I run a similar query but using the Route query e.g: route(path:"/node/16") {...

I get everything requested as if the node is publicly viewable. Is that how the Route Query is intended to work?

**Comment by fubhy** [comment]
We do check access on the router level actually: https://github.com/fubhy/graphql-drupal/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/Route.php#L29

I am wondering if we need another access check on the route object?

**Comment by fubhy** [comment]
Can you check if https://github.com/fubhy/graphql-drupal/pull/163 fixes the issue for you?

**Comment by pmelab** [comment]
Yes, we rely on `$url->access()` to do the right thing. We still need to find out why the `route` call even returns something. Might have other implications too.

**Comment by pavlosdan** [comment]
#163 seems to fix this! Thanks fubhy!

**Comment by fubhy** [comment]
Merged.

**Comment by fubhy** [comment]
> We still need to find out why the route call even returns something. Might have other implications too.

Agreed.
