### ISSUE TITLE
Respect revision published status

### ISSUE THREAD

**Issue by ohthehugemanatee** [drupal-graphql/graphql#164]
Seems like right now we return the latest revision of an entity, regardless of its publish status. Expected behavior is to return the latest *published* revision, ignoring newer draft revisions.

This is probably related to #162 .

There is a larger question of how to handle revisions at all.

* if I edit an existing entity and add a new draft revision, and then access the entity from GraphQL... do I get the latest revision to which I have access (the unpublished draft), or the latest published?
* Is it possible for the frontend application to request a particular revision, or particular revision behavior?

IMO we should mimic Drupal core behavior in in this ticket, and ignore more complicated revision behavior for now.

**Comment by fubhy** [comment]
> IMO we should mimic Drupal core behavior in in this ticket, and ignore more complicated revision behavior for now.

Agreed. Just return the latest published revision for now.

**Comment by fubhy** [comment]
Assigned @blazeyo to work on this.
