### ISSUE TITLE
GraphQL public API

### ISSUE THREAD

**Issue by sedubois** [drupal-graphql/graphql#17]
I couldn't find mention of this anywhere: is Drupal exposing its API somewhere, even if it would be experimental, similar to what [GitHub](http://githubengineering.com/the-github-graphql-api/) recently did? If not, is there any plan? Something where people can explore and familiarize themselves without the need to deploy anything anywhere. That could be the main factor preventing people from experimenting with this code and therefore providing feedback.

I very much like [Graph.cool](https://graph.cool/)'s approach, a "GraphQL backend-as-a-service". No need to install anything, developers can concentrate on a front-end deployable to CDN.

Thanks 😊

**Comment by weitzman** [comment]
There is no central Drupal company who could naturally be responsible for this. Any organization is welcome and encouraged to expose their site via graphql and advertise it.

**Comment by sedubois** [comment]
Thanks, I hadn't realized. Maybe the partners like Pantheon, Interserver etc should provide this.

I'll have a look at other CMS offerings, e.g just discovered [Relax](https://github.com/relax/relax) which looks quite promising but not yet production-ready.

**Comment by fgm** [comment]
Actually, there is one fro drupal.org itself, but not in GraphQL yet: https://www.drupal.org/drupalorg/docs/api
