### ISSUE TITLE
Generalize subrequest pattern

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#170]
Multiple extensions use a "sub request" pattern to fetch information valid for a specific request path (e.g. the blocks visible on `/node/3`). We need to refactor this and provide a common mechanism to reduce duplication.

* graphql_core (context retrieval)
* graphql_blocks
* graphql_metadata
* graphql_breadcrumbs

**Comment by fubhy** [comment]
Would a trait be enough for this?

**Comment by pmelab** [comment]
Thats already done in #245. Can be closed.
