### ISSUE TITLE
views as fields on nodes

### ISSUE THREAD

**Issue by rkoberg** [drupal-graphql/graphql#171]
Is there any way to use an view as a entity reference or view reference (https://www.drupal.org/project/viewsreference) or ?? as a field on a node. 

Let's say I have a "group" node content type. I also have a "group_post" node content type. The group_post has an entity reference to the group. On the display/graphql of a group node I want to list any associated group_posts. I have a view that does this, but it takes an argument (the group's nid). I have tried using EVA, viewsreference, and regular entity reference to the view. I have set the filter to "This graphql (override)". Graphical sees the new field (as fieldGroupPosts). It is shown as a field that has an array of Strings. Using arguments causes an error (e.g. fieldGroupPosts(filter: {field_group_target_id: "4"}))

Any ideas on how to make this work?

**Comment by pmelab** [comment]
I think issue #82 is what you are looking for, am I right?

**Comment by rkoberg** [comment]
That is part of it. I am talking about adding the view as a field on a content type/node. That does not  work. The graphical generated schema shows the type of this view field as an array of Strings (but does not return anything).

**Comment by pmelab** [comment]
Yes, thats exactly what #82 is aiming for. It's not implemented yet, but that's what it is supposed to solve.

**Comment by das-peter** [comment]
Just a follow up regarding this for the sake of searchability ;)
I've created an extension to #82 which allows explicit configuration where a view is attached: drupal-graphql/graphql-views#20
