### ISSUE TITLE
Walk the entity graph in raw values mode

### ISSUE THREAD

**Issue by blazeyo** [drupal-graphql/graphql#179]
Add the ability to jump to related entities in raw values mode (right now traversal ends at `target_id`).

**Comment by fubhy** [comment]
@blazeyo this is next up I guess? :)

**Comment by blazeyo** [comment]
@fubhy Yes, it is :).I've been thinking about it a bit already and one solution would be to

**Comment by blazeyo** [comment]
@fubhy Yes, it is :).

I've been thinking about it a bit already and one solution would be to expose properties instead of schema columns (eg. `entity` instead of `target_id` for reference fields). This way we'd get references as well as computed props for example. What do you think?

**Comment by fubhy** [comment]
Yes, it should use typed data instead.
