### ISSUE TITLE
GraphQL Image not working on images in content types outside of Articles

### ISSUE THREAD

**Issue by TTransmit** [drupal-graphql/graphql#186]
The following query works on an article: 
```
{
  nodeQuery(filter:{type:"article"}) {
    entities {
    ... on NodeArticle {
      title
      fieldImage {
        url
        alt
      }
    }
    }
  }
}
```

It gives this result: 
```
{
  "data": {
    "nodeQuery": {
      "entities": [
        {
          "title": "Thing",
          "fieldImage": {
            "url": "http://localhost:8880/drupal-8.3.4/sites/default/files/thing.jpg",
            "alt": "Thing"
          }
        }
      ]
    }
  }
}
```

If I try the same with a custom content type: 
```
{
  loyalty: nodeQuery(filter:{type:"test_type"}) {
    tiles: entities {
      ...on NodeTestType {
        title
        fieldImageTest {
          url
          alt
        }
        fieldTestCode {
          entityLabel
        } 
      }
    }
  }
}
```

It gives the following error: 
```
{
  "data": {
    "loyalty": {
      "tiles": [
        null,
        null
      ]
    }
  },
  "errors": [
    {
      "message": "You can't specify fields for scalar type \"String\"",
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ]
    },
    {
      "message": "You can't specify fields for scalar type \"String\"",
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ]
    }
  ]
}
```

If I remove the `fieldImageTest`, it works with the taxonomy term `fieldTestCode`.

I have set up the GraphQL view mode (machine name: node.graphql) and have it enabled as a custom display setting for the content type. The project is a Drupal 8.3.4 project. I added drupal-graphql with `composer require drupal/graphql:dev-3.x`. I enabled all graphql and rest api modules.

**Comment by pmelab** [comment]
Technically there is no difference between Article and any other node bundle. What does `fieldImage` return when accessed as a string?

```
 ...on NodeTestType {
  fieldImageTest
}
```

Until #180 is merged, it has to be configured with the `image` formatter in the `graphql` view mode.

**Comment by TTransmit** [comment]
With `fieldImageTest`, it returns the url of the image without the domain name. 

`"fieldImageTest": "/drupal-8.3.4/sites/default/files/2017-07/Screen%20Shot%202017-07-03%20at%2014.57.50.png",`

This is OK. We are wanting to use Drupal GraphQL as a headless CMS for Android, iOS and web. We need to be able to access the alternative text for images for accessibility purposes. We can certainly wait for that PR to get merged. 

I not sure how to configure with the image formatter: 
![screen shot 2017-07-07 at 13 40 40](https://user-images.githubusercontent.com/2356515/27958260-242ab63a-631a-11e7-83dc-5aaafddcf40b.png)

**Comment by pmelab** [comment]
The formatter is correct, but the view mode is "Default". Is the formatter configured in the `GraphQL` view mode?

**Comment by TTransmit** [comment]
I think so. On the same Manage display page:
![screen shot 2017-07-07 at 13 48 15](https://user-images.githubusercontent.com/2356515/27958460-059f3d7a-631b-11e7-8ede-6df1fdc5427e.png)

The machine name of the GraphQL view mode is `node.graphql`
![screen shot 2017-07-07 at 13 50 12](https://user-images.githubusercontent.com/2356515/27958493-3e5ac3f0-631b-11e7-889e-c29fe9886fd5.png)

**Comment by pmelab** [comment]
You enabled the view mode, but you have to click the corresponding tab on top to configure fields for it.
![27958260-242ab63a-631a-11e7-83dc-5aaafddcf40b](https://user-images.githubusercontent.com/501415/27958531-e996d864-6323-11e7-9f6f-3bbf85fcbbba.png)

**Comment by TTransmit** [comment]
Changing the Format to Image in the GraphQL tab worked. Many thanks. 
```
{
  "data": {
    "nodeQuery": {
      "entities": [
        {
          "title": "Test Welcome Gift",
          "fieldImageTile": {
            "url": "http://localhost:8880/drupal-8.3.4/sites/default/files/2017-07/Screen%20Shot%202017-07-03%20at%2014.57.50.png",
            "alt": "Test image"
          },
          "fieldTestCode": {
            "entityLabel": "TEST"
          }
        }
      ]
    }
  }
}
```

**Comment by pmelab** [comment]
You're welcome!
