### ISSUE TITLE
Add GraphQL-Voyager as another graph exploration tool

### ISSUE THREAD

**Issue by pixelmord** [drupal-graphql/graphql#189]
https://apis.guru/graphql-voyager/
This could be a submodule that provides that on a page.

See also #188

**Comment by fubhy** [comment]
Would be fairly easy to even add a more customized version of that. I recently mentioned this tool already on the drupal slack and am +1 for adding something like that

**Comment by pixelmord** [comment]
Customized in which way?

**Comment by fubhy** [comment]
WIth more information about drupal types, e.g. links to the type config pages / field config pages for entity related schema items, etc.
