### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by fgm** [drupal-graphql/graphql#19]
Currently instructions in the README are not up-to-date, leading newcomers to failed installs and a first impression that the module doesn't work at all.

This needs to be addressed, and carried over to the D.O. project page.

**Comment by morvans** [comment]
Came across this module these days and wanted to test it out, I exactly had this feeling.
What are the major directions to follow to currently make the most out of it ? 

Apart from getting entity identifiers & types, I could not even find how to output the node title...

**Comment by fgm** [comment]
The #22 documentation PR is supposed to alleviate this. Currently it only covers the intro, installation process, and contribution process, but should fill up quick.

**Comment by fgm** [comment]
The README part of #22 has been merged so this is supposed to be fixed, with the install documented more in depth on the doc site at https://fgm.gitbooks.io/graphql-for-drupal/content/ . Please reopen if you feel this needs to be changed.
