### ISSUE TITLE
graphql views entities coming in as a String/rendered

### ISSUE THREAD

**Issue by rkoberg** [drupal-graphql/graphql#193]
I just pulled the latest from the github repo (branch 8.x-3.x). I have a view which is basically the normal Drupal installed frontpage /nodes view with a graphql view added. Previously these were coming in as entity objects. Now they are coming in as Strings -- basically the Article or Basic Page rendered (with themeing). 

Is there someway to make the graphql view be an object again? Or is this a bug?

**Comment by fubhy** [comment]
I just tested a new view with the graphql display on a fresh drupal install with the latest 8.x-3.x and could not reproduce this. Can you check again and report back please? Maybe with more details?

**Comment by rkoberg** [comment]
Sorry, I was looking at the wrong thing (trying out so many things and confusing myself -- this is a very exciting and interesting project!). My problem was with entity references on the nodes in the view. I had them left as regular rendered entities for the node's entity reference field display. Switching those types of fields to use the "GraphQL Entity Reference" solved the problem I had.
