### ISSUE TITLE
currentUserContext availability

### ISSUE THREAD

**Issue by rkoberg** [drupal-graphql/graphql#194]
This is a feature request and not sure what kind of impact it would have. Ideally I would like to be able to get the currentUserContext on each request to ensure they are still an active user (so the SPA client can do what it needs).

Could currentUserContext be a field under the query and mutation roots? Or allow currentUserContext as a field under each root level child field?

**Comment by pmelab** [comment]
I think it would make sense to attach all context-fields to the root level and evaluate them against the current call. Some of them will obviously be empty (like the current node), but it's a generic approach that makes sense for a lot others.
