### ISSUE TITLE
Allow accessing Views through the route root field.

### ISSUE THREAD

**Issue by rkoberg** [drupal-graphql/graphql#195]
Say you could set a page path or reuse the view's page path and use that in a 
```
RootSchemaQuery>route(path: '/nodes') {
  entity: [ViewItemObject]
}
```
or
```
RootSchemaQuery>route(path: '/nodes', context: ??) {
  entity: {
    form: {
      formBuildId???
    }
    header: String
    items: [ViewItemObject]
    footer: String
  }
}
```
Since a view is an entity, should it work with route?

**Comment by pmelab** [comment]
I also thought about accessing views by paths. But if we just expose all `Page` displays with a path, this will blow up the schema significantly and add a way to accidentally leak information. So I think it still should be a dedicated display plugin.
The main benefit would probably to be able to call views dynamically. Could you describe a use case?

Exposing evaluated views regions is an interesting idea, but it think this would be more about accessing results of certain plugins placed there. We will need some examples. It's already difficult to draw the line between what to do within Drupal and what in the client and we have to be careful about adding too much options.

**Comment by fubhy** [comment]
We could expand the graphql display to optionall allow a path.

**Comment by rkoberg** [comment]
One use case or what I was trying to do is use a react route higher order component (HOC). This HOC makes all route based graphql request and wrapped components only have to worry about html structure. It seems like people here are familiar with React, so here is a route HOC:
```
// @flow
import React from 'react';
import { graphql } from 'react-apollo';

import type { FunctionalComponent } from '../types';
import Loading from './loading';
import routeGql from './route.graphql';


type ComponentProps = {
  // TODO: Waiting for Next.js 3 type definitions.
  url: {
    query: {
      path: string
    },
  },
};

type Component = FunctionalComponent<ComponentProps>;

const route = (WrappedComponent: Component) => graphql(routeGql, {
  options: props => {
    const pathVar = props.url.query.path ? props.url.query.path : '/';
    return {
      variables: {
        path: pathVar,
      },
    };
  },
})(props => {
  const { data } = props;
  if (!data || (data && data.loading) || !data.route) {
    return <Loading />;
  }
  return <WrappedComponent {...data} />;
});

export default route;
```

**Comment by rkoberg** [comment]
I guess why I was thinking about having everything available from the ```route``` (since it is a Url) root child field's entity field is that I can get the ```currentUserContext``` (without getting to a Url and its user context field). It is or would be pretty convenient and consistent to be able to get every entity by ```route``` and just use the singe route HOC above. A Link can be written like:
```
const mapRelated = (items, type) =>
  <ul>
    {items.map(item =>
      <li key={item.id}>
        <Link
          as={item.url.alias}
          href={{ pathname: `/${type}`, query: { path: item.url.path } }}
        >
          <a>
            {item.label}
          </a>
        </Link>
      </li>,
    )}
  </ul>;
```
So requests going to Drupal use the real path and Drupal would not need any code to look up aliases, but the user sees the alias -- don't know if that is useful or not yet.

(fwiw: If ```currentUserContext``` is a root level child too (or available on each root child field), it makes it easier or more desirable (at least for me) to use other root level fields)

**Comment by rkoberg** [comment]
And here is ```route.graphql```:
```
#import "../lib/entity-fragment.graphql"

query routePath($path: String!) {
  route(path: $path) {
    alias
    breadcrumb {
      url {
        routed
        path
        alias
        __typename
      }
      text
      __typename
    }
    path
    entity {
      ...EntityFragment
      ... on Node {
        uid
        body
      }
      ... on NodePage {
        articles:fieldArticles {
          ...EntityFragment
        }
      }
      ... on NodeArticle {
        image:fieldImage {
          mimeType
          fileSize
          url
          alt
          title
          width
          height
        }
        tags:fieldTags {
          ...EntityFragment
        }
        pages: fieldPages{
          ...EntityFragment
        }
      }
    }
    user:currentUserContext {
      ...EntityFragment
    }
    node:nodeContext {
      ...EntityFragment
    }
    __typename
  }
}
```
and ```../lib/entity-fragment.graphql``` is:
```
fragment EntityFragment on Entity {
  label:entityLabel
  id:entityId
  bundle:entityBundle
  uuid:entityUuid
  type:entityType
  url:entityUrl {
    path
    alias
  }
  __typename
}
```

**Comment by Pasqualle** [comment]
I think there should be an option to retrieve the view by path or with query (or both).
We have the same situation when trying to get page_variants (panels) with graphQL. We made the panels retrievable with route, for now.

**Comment by fubhy** [comment]
We should add a configuration option for setting a path for a View using the GraphQL Display. This can probably be copied 100% from the Views standard Page Display.

I am going to change the Url -> Entity field to Url -> Object where Object is a UnionType instead of directly exposing entities. That way we can also support things beyond the basic entity type.

**Comment by fubhy** [comment]
I am adding the capability to extend the RouteByPath field with this functionality. But since the views integration will be removed from this module before the release this particular feature (views routes) would have to be moved to that module.
