### ISSUE TITLE
drupal bootstrap the /graphql endpoint to a lower level

### ISSUE THREAD

**Issue by rkoberg** [drupal-graphql/graphql#196]
(I don't even know if D8 uses the same bootstrap type system). The ```js``` project https://www.drupal.org/node/2281429 was able to be used to bootstrap drupal to lower levels like DATABASE and eliminate the need for the request to go through the rest of Drupal core's higher levels (like theme). 

Perhaps the ```/graphql``` endpoint can be configured to bootrap drupal to a lower level?

**Comment by fubhy** [comment]
It might be possible for specific schema implementations to do that, however, since we generally also support outputting rendered strings, we don't want to do this by default. This would have to stay a per-project optimization.
