### ISSUE TITLE
optional Persisted GraphQL Queries ?

### ISSUE THREAD

**Issue by rkoberg** [drupal-graphql/graphql#198]
https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5

> If you’ve built a GraphQL server in the past, you’ve probably thought about one or both of these:
> 1. Restricting the queries that your server accepts by whitelisting a specific set of queries
> 2. Saving bandwidth between the client and server by only sending a query ID or hash instead of an entire GraphQL query
>
> What if we could solve the challenges of query whitelisting and bandwidth usage in one swoop? That’s what persisted queries support does! Persisted queries have been talked about a lot, in Apollo Client, in express-graphql, and in talks by developers at Facebook and in this post, we’ll tell you everything you need to know about them: how they work, the tooling we’ve built around them and how you can incorporate persisted queries into your GraphQL application.

**Comment by fubhy** [comment]
What do you mean? We've got this feature since quite a few months (days after that blog post was published) ;)

**Comment by rkoberg** [comment]
Ah, sorry. I did not see anything in the issue queue other than https://github.com/fubhy/graphql-drupal/issues/176

How do you use them? For ```/admin/config/graphql/query-maps```, do you paste in what is generated from:  https://github.com/apollographql/persistgraphql ? Or do you manage some particular JSON structure manually? Is the ID for lookup a drupal/mariadb generated ID? Can you you use a nice name (the name of the query seems to make a lot of sense) 

And not really sure what to do here: ```/admin/config/graphql/query-maps-json```

**Comment by fubhy** [comment]
Check out https://github.com/fubhy/drupal-decoupled-app for a full example of persisted queries in React with Apollo. There are two modules, one for saving config entities with json (the query map) or providing a path to a json file or directory of json files that contain different query maps. If you want you can write a PR that allows you to specify a custom name when creating a query map. Sure.
