### ISSUE TITLE
Pagination on content types ! determining length !?

### ISSUE THREAD

**Issue by drupalshift** [drupal-graphql/graphql#2]
Hi there , i am trying to get nodes from my article content type , i am wondering how can i use offset and limit since i can't get length of my entity !?

``` javascript
{
    nodeQuery(limit:2 ,offset:4) {
    ... on EntityNodeArticle {
      vid,
      articleImage {
        ... on FieldItemNodeFieldArticleImage {
          entity {
            uri
          }
        }
        alt
        title
        width
        height
      }
    }
  }
}
```

How can i get length of EntityNodeArticle ? so i can use it for pagination with limit and offset !

---

Another question is am i able to use pagination in graphql display views , i mean if i create a view and limiting pagination to show 1 node , how can i pass the offset in graphql ! 

``` javascript
{
   frontpageGraphql1 {
    ...on EntityNodeArticle {
      title
    }
  }
}
```

**Comment by fubhy** [comment]
We are currently re-doing the schema for 3.x using the Relay Connection model which contains pagination functionality. Please stay tuned. Sorry for the late reply...
