### ISSUE TITLE
Graph Explorer not working

### ISSUE THREAD

**Issue by ovidius72** [drupal-graphql/graphql#21]
Updating from 8.x-2.x to 8.x-3.x I'm not able to use graphQL explorer.

given a command like this:

```
{
  node(id: 1) {
    id
  }
}
```

I get 

```
{
  "data": {
    "node": null
  },
  "errors": [
    {
      "message": "Resoling function must return type"
    }
  ]
}
```

Looking at the log messages I can see:

```
Notice: Undefined offset: 1 in Drupal\graphql\TypeResolver\EntityTypeResolver->canResolveRelayNode() (line 100 of modules/contrib/graphql/src/TypeResolver/EntityTypeResolver.php).
```

node with ID 1  exists. Inside the node query, not other fields other then id are available when I press cmd+space.

Maybe I'm doing something wrong ?

**Comment by ovidius72** [comment]
Maybe I was wrong with the node id. It works if I set it to the base64 string "ZW50aXR5L25vZGU6MQ" as the id parameter value.

Still have no change to query other fields such as title, ui and so on.

**Comment by danbruder** [comment]
Hi @ovidius72, fields are not yet exposed in the 8.x-3.x branch (aside from a few properties like id). This is actively being worked on. Some discussion on that here: https://github.com/fubhy/graphql-drupal/pull/20.

**Comment by fgm** [comment]
@ovidius72 The ID you give is the opaque form of the generic graph IDs for graph nodes (unrelated to Drupal node entities), as it is the base64 encoding of "entity/node:1". As you can see, it describes the fact that the graph node you are looking for is a drupal entity, of type "node", and of entity id "1".

**Comment by ovidius72** [comment]
Thanks. To be honest I'm still learning graphQL, so there are certainly many aspects I'm not aware of, but I find it incredibly powerful.  The plan is to use this module to build a decoupled web site with Angular2( or React) and Drupal 8 on an incoming project. Me and other co-workers are trying to switch from rest services. I'm not sure if at the moment it is safe to completely rely on it or use it in combination with rest or keep waiting for a stable release.

**Comment by fgm** [comment]
No comment in over one month: assuming closed. Feel free to reopen if still needed.
