### ISSUE TITLE
Option to rename views query

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#212]
note: I might be using a wrong terminology here. For query I mean graphQL field type? I am not familiar with the graphQL terminology yet. Please correct me if my naming of things is wrong.

I have added a graphQL display to "who's online" view. It created a new query with name "whoSOnlineGraphql1View". This is not a really good name.

I have created an option on view display edit page to freely change the name. PR coming.

**Comment by pmelab** [comment]
It will use the views "machine name", which can be configured on the lower right part of views UI.

**Comment by Pasqualle** [comment]
The machine name is editable for the display id, but the view id is not editable.
Therefore if the id is "who_s_online" it becomes whoSOnline, when it should be whoIsOnline.
So the only option currently to fix such views id, is to clone a view..

**Comment by pmelab** [comment]
Thats true. I'm fine with a configurable "name" setting. This also opens new possibilities like overriding other fields.

**Comment by fubhy** [comment]
Yes, I am +1 for allowing to manually define the full name.
