### ISSUE TITLE
Mutation only works with title and default body field.

### ISSUE THREAD

**Issue by chuongle** [drupal-graphql/graphql#217]
I have a simple Article content type which contain title, body(default from Drupal), image and summary(plain long), tags(taxonomy term reference). When I tried mutation it only create the title and body. It does not work for any other field types (plain text, plain long text, entity reference...etc). How do I handle this? Thanks

**Comment by fubhy** [comment]
Hi @chuongle, this will be fixed by https://github.com/fubhy/graphql-drupal/pull/221
