### ISSUE TITLE
Cannot filter content entities by userId

### ISSUE THREAD

**Issue by peterkeppert** [drupal-graphql/graphql#219]
I cannot filter fields which are stored in database with underscore (e.g. user_id, revision_user, ...). GraphQL Explorer instructs me to use these fields as userId, revisionUser, ... (camelCased) in QueryFilterInput. However when I do so, I receive a message "'userId' not found". I traced this issue to this line in EntityQueryFilterInputDeriver class. In function getDerivativeDefinitions() on line 79, there is this code: `$fieldName = graphql_core_propcase($key);`

If I use `$fieldName = $key;`, the filter works with original field names. We should probably use camelCasing but transform to DB-style field names before query gets executed.

**Comment by fubhy** [comment]
Hi @peterkeppert. Thanks for highlighting this issue. I've submitted a fix at https://github.com/fubhy/graphql-drupal/pull/220
