### ISSUE TITLE
Omit empty views filters

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#224]
If a views filter value is omitted, it passes an empty string to the view which leads to an empty result set. It should properly omit the filter completely.

**Comment by weitzman** [comment]
FYI, I've added node.status as a contextual filter but am omitting it in the query. I am seeing results.

**Comment by weitzman** [comment]
Views itself has a setting for what to do when a filter is omitted. I have 'display all values' selected.

**Comment by pmelab** [comment]
I think this was fixed by #230? We forgot to close this issue.

**Comment by pmelab** [comment]
Fixed with #230 and #241
