### ISSUE TITLE
Module graphql doesn't meet the requirements to be enabled.

### ISSUE THREAD

**Issue by Fonseca1990** [drupal-graphql/graphql#227]
I'm really sorry if i'm beeing just a tad dumb here but i can't seem to find anyone with this problem.

When i'm trying to enable this module either with drush or in the website it outputs:

> Module graphql doesn't meet the requirements to be enabled.                        [error]
> youshido/graphql component not found                                                            [error]

I went into the module folder and install dependencies with composer.
Am i doing somthing wrong here?
I'm using version "8.x-3.0-alpha2"

Thanks in advance.

**Comment by fubhy** [comment]
You need to install the module with composer. Running composer install INSIDE the module director later wil place the dependency inside the module. It needs to be installed inside of the Drupal vendor root though.

Ideally you would be using something like this: https://github.com/drupal-composer/drupal-project

And then run "composer require drupal/graphql:3.x-dev" to install the module which will also install the dependencies (youshido/graphql).

I'd advise to always use composer to downlaod and install modules for Drupal 8. And to use https://github.com/drupal-composer/drupal-project. Drush for dependency management is discouraged from my point of view at this point.

**Comment by Fonseca1990** [comment]
Thanks for the awnser.Got it working.

Though now when i activate the Graphql_core the website crashes and outputs:

> Drupal\\graphql_core\\GraphQL\\FieldPluginBase has colliding constructor definitions coming from traits in /mnt/c/development/drupalsites/cnal8/modules/contrib/graphql/modules/graphql_core/src/GraphQL/FieldPluginBase.php on line 110

Have i installed something wrong? It's fine until i enable the core module.

Thanks in advance once again

**Comment by pmelab** [comment]
I've already seen this on simplytest.me, but was never able to reproduce it! What php version are you using?

**Comment by fubhy** [comment]
This is a PHP 5.4.1 bug afaik. There are no conflicting constructors in our traits. We should consider fixing this anyways.

**Comment by Fonseca1990** [comment]
Ok here's the report with PHP version:

```
[Fri Aug 04 14:39:05.282513 2017] [:error] [pid 760] [client ::1:62829] PHP Fatal error:  Drupal\\graphql_core\\GraphQL\\FieldPluginBase has colliding constructor definitions coming from traits in /mnt/c/development/drupalsites/cnal8/modules/contrib/graphql/modules/graphql_core/src/GraphQL/FieldPluginBase.php on line 110
root@DESKTOP-QOVEK6U:~# php -v
PHP 7.0.12-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by fubhy** [comment]
It's already fixed. I'll publish this on composer / packagist and release a new alpha soon.
