### ISSUE TITLE
Authentication recommendation

### ISSUE THREAD

**Issue by shawnmmatthews** [drupal-graphql/graphql#233]
I've been running an app with public queries for a while now, and things are going great. Ive been looking into some different authorization options for my React front end and was wondering if there are any recommendations for options that play well with graphql and D8. I was looking at Auth0 and passing a JWT but am not quite sure how the token should be passed using graphql. Also has anyone found any decent free options? Would something like simpleoauth work? Are there any repos that you know of where I might be able to base this off of?  Thanks for any advice you can provide! Once again, I really appreciate all the hard work on this awesome module.

**Comment by xuxucode** [comment]
I use [simple_oauth](https://www.drupal.org/project/simple_oauth) module on D8, and save JWT in [cookie httpOnly](http://dev.apollodata.com/react/auth.html#Cookie) for SSR. I tried saving JWT in [localStorage](http://dev.apollodata.com/react/auth.html#Header), it's vulnerable and hard for SSR.

**Comment by shawnmmatthews** [comment]
Thanks @edwardaa! for the quick response. Is this achievable without a node.js layer? I'm new to SSR and Apollo for that matter, and am looking to keep the initial complexity to a minimum, as I'm finding it a bit difficult to find Drupal based backend examples.

**Comment by xuxucode** [comment]
React applications need a node.js server side, it may be just a simple [server.js](https://github.com/zeit/next.js/blob/master/examples/custom-server-express/server.js) file. I use [next.js](https://github.com/zeit/next.js) that has built in support for SSR and router. You can start from [next.js/examples/with-apollo](https://github.com/zeit/next.js/tree/master/examples/with-apollo) or  [next.js/examples/with-apollo-and-redux](https://github.com/zeit/next.js/tree/master/examples/with-apollo-and-redux), it's easy to get started.

**Comment by shawnmmatthews** [comment]
Awesome. Thank you! I've been running it from a create-react-app build and serving it statically, via a regular LAMP stack server with some recommended redirects from the FB docs. I'm not sure if Acquia or Pantheon are supporting Node on the server yet. I'll check it out.

Best,
Shawn

**Comment by shawnmmatthews** [comment]
Confirmed neither Acquia nor Pantheon will allow for Node.js installs on their cloud platforms. @edwardaa  I'm assuming this means if I want to make this happen I'll be looking at an additional server to run the front end?...

**Comment by fubhy** [comment]
amazee.io supports it. Maybe check with @Schnitzel!

**Comment by xuxucode** [comment]
@shawnmmatthews Yes :-)

**Comment by shawnmmatthews** [comment]
Awesome thanks everyone! Looks like I have some reading to do! Closing this down.

**Comment by shawnmmatthews** [comment]
@edwardaa @fubhy Would you mind sending me an invite for the slack channel? shawn.m.matthews@gmail.com 

Thanks!
