### ISSUE TITLE
Add content fields for uid and created

### ISSUE THREAD

**Issue by weitzman** [drupal-graphql/graphql#234]
uid and created are registered as field display components, so these fields show up in the graphql schema for nodes. however they are of String type. Instead uid should be a reference to a User so that one can grab the user's Fields (and roles, once thats added to the schema, hint hint).

**Comment by pmelab** [comment]
`uid`  and `created` are there more or less by accident, since they are non-configurable components of the node display. The PR adds properly typed `entityOwner` and `entityCreated/Changed` fields. 

>  ... (and roles, once thats added to the schema, hint hint)

_Hint:_ Could these hints manifest in an issue where we discuss the use case? 😃
