### ISSUE TITLE
Add roles Field on Users

### ISSUE THREAD

**Issue by weitzman** [drupal-graphql/graphql#237]
It can be needed to know the role list for a given user. Just role machine names for values are fine for now.

**Comment by pmelab** [comment]
What is your use case? Actually displaying a users roles? Do we need to access protect that? If it's about permissions, perhaps we need a `hasPermission()` field.

**Comment by weitzman** [comment]
I think the calling application wants to check to see if user has 'admin' role, for example ... I'm mostly trying to be equivalent to an existing custom rest api endpoint that offerred this.

**Comment by weitzman** [comment]
I think hasPermission() can be helpful in a decoupled drupal scenario. my caller is an analytic application that wants to enrich its data with knowledge of drupal users

**Comment by pmelab** [comment]
I see. So this field would have to be protected by `administer users` and your consumer would have to bring this permission.

**Comment by weitzman** [comment]
Well, 'administer users' is generally considered to be about editing the
roles of a user. Simply viewing the roles could be a lesser perm. Not sure
whats appropriate though.

**Comment by fubhy** [comment]
I'd first like to introduce config entity support. Then we can link to the Role config entity from there.

**Comment by fubhy** [comment]
Will be covered by config support. This is a post 3.0 item.
