### ISSUE TITLE
Views filter not used - node.type

### ISSUE THREAD

**Issue by weitzman** [drupal-graphql/graphql#239]
I've created a graphql Views display with an exposed filter for 'Content type'. When I browse the graphql schema I see this filter as type [String]. I expected to see Enum, but maybe [String] is right. Regardless, when I pass in a single value, I see that Views ignores the condition thus nodes of all types are returned. Am I supposed to use square brackets around the value like below? 

```
{
  graphqlNodesGraphql1View(filter: {type: ["service_page"]}) {
    count
    results {
      entityId
      entityBundle
      entityLabel
    }
  }
}
```

**Comment by pmelab** [comment]
Are you using the alpha or latest dev? There was a problem with taxonomy term filters that manifested in the same way: https://github.com/fubhy/graphql-drupal/commit/3a0b7a5948c4e9ce4be52d931d73e5da2273a5fc

**Comment by weitzman** [comment]
Yes,thats the commit that I have. A bit of debugging leads to:

the graphql schema declares a filter named `type`, but the View expects an $input key named  `content_type`

i’m not sure how to fix it. a symptom of the bug is this notice `Notice: Undefined index: content_type in Drupal\views\Plugin\views\filter\FilterPluginBase->acceptExposedInput() (line 1385 of core/modules/views/src/Plugin/views/filter/FilterPluginBase.php).`
