### ISSUE TITLE
Simplify selection based views filters

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#246]
Currently the "generic" filter mechanism turns some filters into too complex structures. The node type filter for example requires this structure:

```
myView( filter: { type: {article: "article"} }) {
  ...
}
```

Thats not very intuitive. A list of enums would be perfect for this case:

```
myView( filter: { type: [article, page] }) {
  ...
}
```

I'm not sure if there is  a way how to reliably identify these cases.

**Comment by fubhy** [comment]
I am removing the release blocker tag from this one. Sadly views simply doesn't have good type definitions or any typed data integration at all. That  leaves us with little possibilities to optimize this further and I think this will have to wait until we can rework our views integration based on the configuration interface in some fashion.
