### ISSUE TITLE
nodeByID requires AvailableLanguages

### ISSUE THREAD

**Issue by clemens-tolboom** [drupal-graphql/graphql#250]
As a newbie I'm puzzled resolving properly

```GraphQL
{
  nodeById(id: "1") {
    title
  }
}
```
responds with
```GraphQL
{
  "data": {
    "nodeById": null
  },
  "errors": [
    {
      "message": "Require \"language\" arguments to query \"nodeById\""
    }
  ]
}
```

Adding a language argument resolved into a result

```GraphQL
{
  nodeById(id: "1", language: "en") {
    entityId
    title
    entityType
    entityLanguage {
      id
    }
  }
}
```
but still gives

![graphql-available-languages](https://user-images.githubusercontent.com/371014/29408823-ffb19418-8349-11e7-9243-27df84a5d776.png)

**Comment by clemens-tolboom** [comment]
Solved it by removing the quotes "en"

```GraphQL
  nodeById(id: "1", language: en) {
```
After I discovered the Docs on http://drupal.d8/graphql/explorer

**Comment by fubhy** [comment]
Yes, AvailableLanguages is an ENUM.

**Comment by clemens-tolboom** [comment]
So how to request more languages ... aka where should I read more? nodeById is Drupal but AvailableLanguages is GraphQL right?

Google gives #172 as a first result on `GraphQL "AvailableLanguages"`

**Comment by pmelab** [comment]
No, `AvailableLanguages` is also Drupal. It's an enumeration of the languages configured.
