### ISSUE TITLE
Expose formatters in graphql

### ISSUE THREAD

**Issue by dasjo** [drupal-graphql/graphql#254]
Currently, we use display formatters to configure how data should be exposed to graphql. To go with the concept, that graphql empowering webservice clients so that they can specify their requirements, I was thinking we could go one step further: we expose all formatter options directly in the graphql schema. This is just a rough idea, but basically for each typed data property, the graphql schema would allow you to access formatters that usually configure via site building in the display formatter. Instead, you can now configure the formatters directly in your graphql query and add parameters. This would especially be helpful, as graphql would expose a nice autocomplete UI to configure those formatters and configuring how data should be display would be put entirely into the graphql clients hand. I briefly discussed this with @fubhy today and he highlighted that we might need to think about security concern / a permissions concept to restrict formatters available.

**Comment by fubhy** [comment]
I think we should solve this through the graph configuration and the corresponding user interface that Philipp and me have discussed at length already. I think the full explanation of what we have in mind might warrant a blog post detailing the architecture for that.

Work on this would probably eat up a considerable amount of time and might require sponsoring.

**Comment by pmelab** [comment]
What @dasjo is suggesting doesn't fully overlap with the configuration ui. But exposing configuration options for all field formatters will increase the schema drastically (while you probably need 2) and will face the same problem of missing standardisation of input as we face it with views filters.

**Comment by fubhy** [comment]
I am not saying that it overlaps but I am saying that what Josef is suggesting it would solve would also be solved by the Configuration Graph that we discussed.

**Comment by pmelab** [comment]
Not quite. What Josef suggests would mean it's possible to invoke field formatters dynamically and e.g. pass variables into them. The configuration is still static and can't adapt per query.
