### ISSUE TITLE
Expose integer and float

### ISSUE THREAD

**Issue by iamake** [drupal-graphql/graphql#264]
I see we have a module for boolean field #91 . Just curious if we should have submodules to expose integer and float field as well?

If you are agree, I can do PR for those 2 modules since I'm going to use them for my project anyway.

**Comment by pmelab** [comment]
By now, we have the *GraphQL Raw* formatter that just emits typed data properties and covers all of them. Boolean was there before, but right now it's just backwards compatibility. Unless you have another reason for a distinct field formatter?

**Comment by fubhy** [comment]
Yep, I consider this resolved too. :)

**Comment by iamake** [comment]
It's for 2 reasons below. What do you think ?

1)  It's more intuitive to display scalar value as a scalar, not as an object

```javascript
// edible as a scalar of boolean type
{
  "data": {
    "apple": {
      id: 1,
      edible: true
    }
  }
}
```

```javascript
// edible as a boolean object
{
  "data": {
    "apple": {
      id: 1,
      edible: {
        value: 1
      }
    }
  }
}
```

2) Drupal displays integer and float as a String on Unformatted display format. It's more intuitive to display them as their corresponding native type.

**Comment by pmelab** [comment]
@fubhy Hasn't there been a plan to automatically simplify single property fields?
