### ISSUE TITLE
Naming improvement for views related schema items

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#267]
Issue #212 introduced the option to rename views query, but it can be still improved.

example of renamed views query in graphQL schema:
`whoIsOnline(page: Int = 0, pageSize: Int = 5): WhoSOnlineGraphql1Result`
Instead of the ugly result name, the result should be named `whoIsOnlineResult`.

Other schema item names could be improved also. Search for graphql_camelcase inside graphql_views module.

**Comment by fubhy** [comment]
Agreed

**Comment by fubhy** [comment]
Assigned @blazeyo to work on this.

**Comment by fubhy** [comment]
https://github.com/fubhy/graphql-drupal/pull/279
