### ISSUE TITLE
View result type

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#268]
If node type (with 1 type) is used in the view filter, then the result should be that node type.

example:
latestBlogPosts view result is `Node`, but its should be `NodeBlog` (as node_type = 'blog' filter is used in the view)

Should work for every entity, not just nodes (where bundle is used as view filter).

**Comment by fubhy** [comment]
Agreed.

**Comment by fubhy** [comment]
Assigned @blazeyo to work on this.
