### ISSUE TITLE
Views pager

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#271]
Why does the views query result changes when paging is enabled?

```
whoIsOnline1: [Entity]
whoIsOnline2(page: Int = 0, pageSize: Int = 5): WhoSOnlineGraphql1Result
```
same view, just the second display has paging enabled under "Advanced" section

**Comment by fubhy** [comment]
Because when paging is enabled you can fetch the count of ALL results across all pages. Useful for figuring out how many pages there are.

**Comment by Pasqualle** [comment]
Ok, makes sense..
Thanks
