### ISSUE TITLE
Create a custom graphQL type

### ISSUE THREAD

**Issue by yann-yinn** [drupal-graphql/graphql#275]
Hello ! is there a good starting point or example i can look to create my own custom query and add it to graphQL module schema ?

**Comment by fubhy** [comment]
Hi

https://www.amazeelabs.com/en/blog/drupal-graphql-batteries-included
https://www.amazeelabs.com/en/blog/extending-graphql-part1-fields
https://www.amazeelabs.com/en/blog/extending-graphql-part-2

**Comment by yann-yinn** [comment]
@fubhy that's awesome, i suggest to put this in the README at the beginning of the documentation section, until official documentation is not outdated anymore, because these are very, very valuable informations to get started with graphQL module
