### ISSUE TITLE
A little help please :)

### ISSUE THREAD

**Issue by CarstenHoyer** [drupal-graphql/graphql#28]
I just saw this https://events.drupal.org/dublin2016/sessions/no-compromises-%E2%80%93-react-relay-and-graphql-drupal-8

And wanted to try out the module. However it seems like none of what you are demoing is working.

Is there some trick that I am missing?

Currently I can query a node like in issue #21 with a base64 string, but no fields are available. Pretty far from the demo, where both fields and entity references are available.

[EDIT]: I had a bit more time working with the module. I cant say that I have more than the most shallow knowledge yet, but it looks like I have 104 fields in the QueryRoot returning from Drupal\graphql\GraphQL\Relay\Schema. I guess there should be something related to my actual content types here?

**Comment by fgm** [comment]
AFAIK most of the demos you may have seen are based on the legacy 8.x-1.x/2.x branches: this is the want you want to checkout to obtain these behaviors, but notice that it has been superseded in terms of development by 8.x-3.x, which has been completely redesigned on top of the https://github.com/youshido/graphql library, but still needs a lot of work to reach the functionality level of the legacy branch.

**Comment by CarstenHoyer** [comment]
Ah I see. That makes sense. I´ll check it out.

**Comment by RoySegall** [comment]
I'm struggling with this module. I created a custom entity and the only things I'm getting is the entity id and the entity bundle. How can I add extra fields?

Shouldn't all the fields need to be exposed out of the box? The documentation of Youshido/GraphQL is not very clear for the Drupal side.

**Comment by fgm** [comment]
@RoySegall which branch have you been using ? fields are not (yet) exposed in 8.3, as explained above: you need to write your own resolvers.

**Comment by RoySegall** [comment]
> @RoySegall which branch have you been using
I downloaded it with composer and it's the 8.3 branch, I can pull it with git if nothing will work.

> you need to write your own resolvers.

I tried to understand how to do it but I could not find any documentation for that:

> The documentation of Youshido/GraphQL is not very clear for the Drupal side

**Comment by fgm** [comment]
Unless you plan on working on the module itself or are ready to spend some time understand it the system while our doc slowly improves, you might be better off with 8.1 or 8.2 : one of these (not sure which) is the one Dries used for the Drupalcon demo.

**Comment by RoySegall** [comment]
I will take a look on the 8.1 branch. BTW - there is no 8.2 branch in this repo, I think only on d.o

**Comment by RoySegall** [comment]
Still don't get it. I cloned 2.x and 1.x, and I can't see any example on how to add fields.

But I'm looking on the graphql_test_custom_schema module, and I can see that you add a service and a graphql.config. If you could elaborate what each of them does in the custom schema definition that would be good. I think I could take it from there.

**Comment by fgm** [comment]
Never used these so I can't help you there. Hopefully @fubhy can chime in.

**Comment by fubhy** [comment]
I can give you a demo module for 3.x. It is very easy to create a custom, hand-crafted schema.

**Comment by RoySegall** [comment]
> I can give you a demo module for 3.x 

That would be awesome! I have a custom entity in my project as well

**Comment by fubhy** [comment]
@RoySegall Okay then. I can add the demo module until Thursday/Friday.

**Comment by RoySegall** [comment]
That's would be awesome. 10x.

**Comment by bogue** [comment]
I second that emotion

**Comment by RoySegall** [comment]
@fubhy Any updates?

**Comment by fubhy** [comment]
@RoySegall Yep, you will get it today :).

**Comment by kirkilj** [comment]
In a message above, FGM stated that since the 8.1 work was being refactored in 8.3 to use the youshido/graphql PHP library, it wasn't yet at feature parity. What is the outlook for this on the development timeline? Is there a rough roadmap? How about mutations and Relay compatibility?

I am thrilled that some forward thinking souls in the Drupal community see how Graphql compatibility could make Drupal more enticing as a back-end repository by allowing a single request/bootstrap to take the place of several discrete fetches. My project's selection of Drupal as a middleware application layer would be dependent on such a capability. In any event, keep pushing on. If I had the Drupal/PHP API programming chops, I'd jump in and contribute.

**Comment by fubhy** [comment]
@RoySegall @bogue Here is your example schema: https://github.com/fubhy/graphql-drupal/commit/c863dd33ca390f15de49056879b419e50f5d423f.

Note: It only exposes menus and their links atm. but it's a good example because it's recursive.

**Comment by RoySegall** [comment]
Thanks. Looks awesome.

**Comment by bogue** [comment]
@fubhy Aaaaah... saved the little brains i have left -- thanks a bunch!

**Comment by fgm** [comment]
I also added a simple example to give new developers on the project a simpler way to start: a module only exposing a new simple field. It's currently awaiting merge, on PR #36
