### ISSUE TITLE
displaying body summary 

### ISSUE THREAD

**Issue by yann-yinn** [drupal-graphql/graphql#280]
Hello !
I'm rebuilding my site with a decoupled Drupal, but i don't know how to build this page : https://yineo.fr/blog 

It displays body summary but i have only access to full body value. What is the easiest way to achieve this ? a custom module to handle this special field ?
I thought i could use view modes but i can use only one view mode, so i would loose full body is choosing to display the summary in my view mode.

**Comment by pmelab** [comment]
Yes, currently a custom field is the easiest solution. We hardly ever use the trimming feature and this didn't come up yet ... But lets keep this ticket as a reminder.

**Comment by yann-yinn** [comment]
@pmelab yep we discussed this several days ago, i tried with no luck with pseudo fields with display suite, and did not take the time to write custom code for now.

I will simply create a new "teaser" field and fill it manually instead of default body summary, that's make perfectly sense from an content editors perspective

**Comment by yann-yinn** [comment]
@pmelab gave me another solution :
- in display mode, choose "graphQL raw formatter" 
- in your graphQL query you have now access to all properties  : 

_edit : changed summary to summaryProcessed_

```graphql
query {
  nodeQuery {
    entities{
      entityBundle
      ...on NodePost {
        body {
          summaryProcessed
          value
        }
      }
    }
  }
}
```

**Comment by pmelab** [comment]
@nyl-auster Actually, there should be a "processed" and "summaryProcessed" property. You should use this one, since it also applies input filters.

**Comment by yann-yinn** [comment]
@pmelab oh yes thanks, updated.
