### ISSUE TITLE
graphQL entity reference broken ?

### ISSUE THREAD

**Issue by yann-yinn** [drupal-graphql/graphql#289]
Hello ! I have a field "tags" on my "Post" content type. This is an entity reference for terms.
I choose "GraphQL entity reference" as my formatter, but that throws me error below. ( "GraphQL raw value" works as expected. )
GraphQL version: according to composer.lock : "version": "3.0.0-alpha5",

<img width="1385" alt="capture d ecran 2017-08-31 a 09 45 44" src="https://user-images.githubusercontent.com/335495/29912213-2cb46bce-8e31-11e7-8836-693d99dbe386.png">
<img width="1063" alt="capture d ecran 2017-08-31 a 09 45 53" src="https://user-images.githubusercontent.com/335495/29912214-2fda8fae-8e31-11e7-8034-b6d23df2c590.png">

**Comment by yann-yinn** [comment]
Silly me, i forgot to expose my taxonomy vocabulary to graphQL in ```admin/config/graphql/content```, plugin graphQL entity reference is not enough to make this work.

**Comment by pmelab** [comment]
Thats a problem stumbled over myself. I should add some kind of warning ...

**Comment by pmelab** [comment]
I created #293
