### ISSUE TITLE
Context resolver should not fall back to "String" when type is not registered.

### ISSUE THREAD

**Issue by nick-zh** [drupal-graphql/graphql#291]
E.g. the userContext field should not be typed as "String" if the entity:user data type is not registered. In this case we should simply not add the user context. First I thought that it might be useful to then fall back to just "entity" but actually it doesn't make sense to have it in there at all in that case.

**Comment by nick-zh** [comment]
Currently this fails with "invalid resolve type for field userContext" because the resolver still returns the User object while the User type is not registered in the schema anywhere causing the buildType() method to set it to "String".

**Comment by pmelab** [comment]
@nick-zh Could you test #298? This should fix the problem.
