### ISSUE TITLE
Warn if unexposed entity types are used in the schema

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#293]
If a schema field returns an entity type that is not exposed, the resulting behavior is very confusing. There should be a warning with a link to where to expose the type.

**Comment by yann-yinn** [comment]
I saw an error in watchdog, but not in graphQL explorer : 
```
graphql_  warning   Plugin raw_field_item:node-field_tags-entity could not be added to the GraphQL schema: GraphQLcore                
plugin with name TaxonomyTerm could not be found.
```

**Comment by pmelab** [comment]
Yes. But it could already warn you when you set a taxonomy term field to "GraphQL Entity".
