### ISSUE TITLE
Support solr view (results)

### ISSUE THREAD

**Issue by nick-zh** [drupal-graphql/graphql#295]
The default in graphql/modules/graphql_views/src/Plugin/GraphQL/Fields/View.php does not work for solr views. we need a seperate implementation, in resolveValues we need
```
yield $row->_object->getValue();
```
instead of
```
yield $row->_entity;
```
also solr specific fields (like relevance, etc.) would be very nice

**Comment by pmelab** [comment]
There already is #83 that should cover SOLR views.

**Comment by fubhy** [comment]
No, Solr views results have a different format. We need to access $solr->_object->getValue() instad of $row->_entity. So field displays are nice but it doesn't solve theproblem that the Solr result set for entity results is different than the one for standard Views.

**Comment by pmelab** [comment]
Is `$solr->_object->getValue()` the entity?

Then this would be a shortcut to enable solr without field displays.

Views field display will probably not access the rows result object directly but invoke result formatters, so this change doesn't apply there.

**Comment by fubhy** [comment]
Yes. That's the entity. And yes, we want to enable Solr views for Entity Row displays.

**Comment by pmelab** [comment]
Okay, makes sense. Do we know of other modules that provide different views result objects? Just thinking about how generic this should become.

**Comment by fubhy** [comment]
Any module that provides alternative result plugins for views like Entity Query Views or anything that connects a different database or so...

**Comment by fubhy** [comment]
Will be tackled with https://github.com/fubhy/graphql-drupal/pull/313
