### ISSUE TITLE
Licensing and patents

### ISSUE THREAD

**Issue by fgm** [drupal-graphql/graphql#297]
While following the patents issue about React, I fell upon mention of two patents FB holds, which apply to GraphQL:

* https://www.google.com/patents/US9646028
* https://www.google.com/patents/US9400822

AIUI Any code implementing these algorithms, regardless of its possible cleanroom origin, falls under the scope of the patents, unlike what happens with copyright licensing, so we probably should at the very least mention the existence of these patents in the README/documentation, to be perfectly open about potential risks users incur when deploying GraphQL tools, as patent licensing is not covered by our GPL-2.0+ licensing.

I'd even be interested in learning what the Drupal legal/licensing working group has to say about the risks Drupal itself incurs when building and distributing code covered by such patents without an explicit license to use them.

**Comment by fubhy** [comment]
Interesting. I will dig around a bit. I just found this post which is quite informative: https://medium.com/@dwalsh.sdlr/using-graphql-why-facebook-now-owns-you-3182751028c9

Not sure what to do with that information though. Will check with some peers.

**Comment by fgm** [comment]
Excellent article indeed.

**Comment by fubhy** [comment]
This is now resolved :) https://medium.com/@leeb/relicensing-the-graphql-specification-e7d07a52301b
