### ISSUE TITLE
Is there multilangage support?

### ISSUE THREAD

**Issue by RoMay** [drupal-graphql/graphql#30]
First of all thanks a lot for the really good work! 

We currently try to fetch a translated content by passing language in a query `"8.x-2.x-dev"`:

```
POST https://example.com/de/graphql
{
  nodeQuery (langcode: "de") {
    title
    renderedOutput
  }
}
```
In this case **renderedOutput** returns an german translation, BUT **title** is still in english (master language). Are multilanguage queries supported in the GraphQL module?

For any advice I would be very appreciated!

**Comment by RoMay** [comment]
So after some reverse enginiering, came up with a very pragmatical solution:

```
ContentEntityTypeResolver.php

public static function getFieldValueSimplified(EntityAdapter $data, $a, $b, $c, $d, $e, $f, $config) {
  ...
  // use translated content
  $currentLanguage = \Drupal::service('language_manager')->getCurrentLanguage();
  $entity = $data->getValue()->getTranslation($currentLanguage->getId());
  $data = EntityAdapter::createFromEntity($entity);
  $data = $data->get($property);
```

It works by passing a language in the request URL.

@fubhy would be that possible to support translations in `"8.x-3.x"`?

**Comment by fubhy** [comment]
Yes, currently you can do that through your own custom schema. In the future, we will add this together with a submodule that will take over the job of generating a schema based on the Drupal data graph.
