### ISSUE TITLE
Enable file upload in mutations

### ISSUE THREAD

**Issue by ClemensSahs** [drupal-graphql/graphql#300]
We have a mutation to create and update files, yes. But in my mind we only add a URIs as Strings, right?

Currently I search the best way to create a File with create the URI, too. (like a uploader). But sending the file as string appear as a bloody workaround.

Has any body a equal Use Case?

**Comment by fubhy** [comment]
We would probably use multipart/form-data as the Content-Type and submit the files in a keyed list somewhere in the POST body. Inside of the query we would then reference these. E.g. with a special file upload input type that has a field that points to the file as a string with a special syntax for instance something that looks like a protocol, e.g. "file://[name-of-key-in-post-body]".

Would you like to work on a PR for that?

**Comment by ivanjaros** [comment]
How about chunking big files, wouldn't that be a problem?

**Comment by fubhy** [comment]
Generated mutations have been removed from the base module for now but we should still add a base API for this to allow other modules to more easily add file upload capabilities.

**Comment by webexpert5** [comment]
Does the module support file uploads in any way?
I really need to get it working.

The graphql_legacy module provides file mutations, but I am not sure how to send the file itself as the parameter.
The mutation is generated by the Entity Mutations, so I think files are not handled by the module even if we send the image in the request.

Can you guide how can i extend the module (beta version) to create custom file mutations?

**Comment by fubhy** [comment]
No we currently do not have a way to send files but it's not hard to solve imho. Someone simply needs to work on it ;). I can provide more info on Wednesday (currently on vacation) in case anyone is interested to solve this and submit a PR.

**Comment by ivanjaros** [comment]
I'll be creating upload files today or tomorrow(just working on entity crud). My plan is to have simple upload, chunked upload and possible streamed upload(I'm getting inspiration from plupload). But those will be only standalone mutations and when I thought about it I am not sure how to approach the validation. Since this will be standalone mutation(s) the entity field settings won't apply.

Maybe I could have unrestricted global upload mutation for admin with some sane validation in place(size, file type) and maybe a file upload field that could receive input of entity reference(ie. already uplaoded file) or simple file upload(no chinking or streaming) where field validation would work.

**Comment by ghost** [comment]
https://gist.github.com/ivanjaros/325b5846d9320dab5a1b07cbaef7f960

**Comment by justinlevi** [comment]
@ivanjaros I just noticed that the link above is no longer working - do you have your example posted anywhere else? I was hoping to dig into uploading images to GraphQL

**Comment by justinlevi** [comment]
@fubhy any additional direction on this would be great. I'm happy to work on this too

**Comment by justinlevi** [comment]
Posting some research I've been looking into here: 
- https://medium.com/@danielbuechele/file-uploads-with-graphql-and-apollo-5502bbf3941e
- https://github.com/apollographql/apollo-server/issues/229

This seems really interesting
- https://github.com/Youshido/GraphQLFilesBundle

**Comment by ghost** [comment]
https://gist.github.com/ivanjaros/34bc0c628b7243c71310d57bffeeaced

**Comment by justinlevi** [comment]
thank you!

**Comment by justinlevi** [comment]
I have a WIP module here: https://github.com/justinlevi/graphql_custom_file_upload

Was trying to get some unit tests work and it seems like the file entity should be getting created in my test but these lines in `CreateEntityBase` seem to be failing??

```
    if (!$entity->access('create')) {
      return new EntityCrudOutputWrapper(NULL, NULL, [
        $this->t('You do not have the necessary permissions to create entities of this type.'),
      ]);
    }
```

Any idea why an Authenticated user with the following permissions wouldn't have the necessary permissions? 

```
    Role::load(RoleInterface::AUTHENTICATED_ID)
      ->grantPermission('execute graphql requests')
      ->grantPermission('create media')
      ->grantPermission('view media')
      ->grantPermission('access content')
      ->grantPermission('bypass node access')
      ->grantPermission('create url aliases')
      ->save();
```

**Comment by fubhy** [comment]
Duplocate of #458
