### ISSUE TITLE
Paragraphs result type

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#302]
Paragraphs module has an option to filter by bundle.
If one bundle is used in the filter then the graphql schema should return the given pragraph bundle and not the entity.

Similar improvement as #268, just different use case.
```
fieldBits {
        ... on ParagraphBit {
          fieldTitle
       }
}
```
becomes
```
fieldBits {
  fieldTitle
}
```

**Comment by Pasqualle** [comment]
The good thing is that the old query will still work after the change. So we will not break any existing queries.

**Comment by fubhy** [comment]
This is due to the way we handle entity reference fields. I don't want to add special handling for all modules that do something.

**Comment by Pasqualle** [comment]
```
/**
 * Implements hook_graphql_fields_alter().
 *
 * Change graphQL result for single type paragraphs.
 */
function mymodule_graphql_fields_alter(&$fields) {
  $mapping = [
    'entity_reference:node-photo-field_bits' => 'ParagraphBit',
  ];

  foreach ($mapping as $key => $new_type) {
    if (isset($fields[$key]) && $fields[$key]['type'] === 'Paragraph') {
      $fields[$key]['type'] = $new_type;
    }
  }
}
```
