### ISSUE TITLE
Expose available options of list fields as Enums.

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#303]
The result type for List (text) fields could be enum if it is defined with allowed values.
It might not work if the field allowed values are defined with a function.

**Comment by fubhy** [comment]
That would require a custom field formatter in the current system. We currently do not have a field formatter for text fields except the globally applicable "raw value" formatter.

**Comment by fubhy** [comment]
I don't think that this offers much benefit currently.
