### ISSUE TITLE
Option to rename exposed fields

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#304]
It would be nice to have an option on "Exposed content" config page to rename any Drupal field in graphQL schema.

The issue I have is, that I have field_faq_category and field_blog_category field. I can not name both fields as category because they have different field config, therefore different field names. But in the graphQL schema the category is just a String, therefore no benefit to name category field differently on faq node and blog node.

**Comment by fubhy** [comment]
This will have to wait until we are post-release. For now you can use the alter hook to rename the fields in the schema to your liking.

**Comment by Pasqualle** [comment]
```
/**
 * Implements hook_graphql_fields_alter().
 *
 * Rename textfields and image fields in graphQL schema.
 */
function mymodule_graphql_fields_alter(&$fields) {
  // Rename selected fields.
  $mapping = [
    'rendered_field:node-faq-field_faq_category' => 'category',
    'rendered_field:node-blog-field_blog_category' => 'category',

    'rendered_field:node-blog-field_blog_image' => 'image',
    'image_field:node-blog-field_blog_image' => 'image',
  ];

  foreach ($mapping as $key => $new_name) {
    if (isset($fields[$key])) {
      $fields[$key]['name'] = $new_name;
    }
  }
}
```

**Comment by fubhy** [comment]
Exactly :)
