### ISSUE TITLE
Deprecated test traits

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#318]
Some of the traits used in tests are deprecated in Drupal 8.4
like: 
Drupal\simpletest\ContentTypeCreationTrait;
Drupal\simpletest\NodeCreationTrait;
Drupal\simpletest\UserCreationTrait;
Drupal\simpletest\BlockCreationTrait;

In case we are comfortable of increasing the minimal version for core dependency to 8.4, then these deprecated traits can be replaced with the right ones.

**Comment by fubhy** [comment]
Nope, for now we can't do that. We have to support 8.2 and 8.3 at least for a while.
