### ISSUE TITLE
Rename "entity" field on Url type to "object" and make it extendable

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#334]
Instead of having an "entity" field on the Url type that always returns an Entity we should have an "object" field that is of type UnionType and is extendable.

**Comment by fubhy** [comment]
The current use case for that would be https://github.com/fubhy/graphql-drupal/issues/334

In this issue we would add a resolver that can handle views urls.

**Comment by pmelab** [comment]
This should contain a "rename" alter hook in `graphql_legacy`.

**Comment by pmelab** [comment]
Extensibility can be solved by the type `applies` method as it's used for interfaces.
