### ISSUE TITLE
Retrieve Parent-ID from taxonomy term using GraphQL

### ISSUE THREAD

**Issue by lenoirmind** [drupal-graphql/graphql#336]
Hi there,

How can I retrieve the parent tid from a Taxonomy Term using GraphQL query?
I have tried many different ways, one of them is a view that returns all the taxonomy terms in a vocabulary. Filtering using exposed filters and contextual filters work. But I cannot seem to get to parent tid...

My simple query
```

 taxonomy:graphqlTaxonomyGraphql1View {
   ... on TaxonomyTermReactarotCompetencyModel {
     name
     tid:entityId
 
     url:entityUrl {
        path
     }
  }
}   
```
I would expect parent-tid to show much the same as "name"

Am I doing something wrong or do I misunderstand?

Kind regards,

Reatarot

**Comment by lenoirmind** [comment]
For anyone who might use this feat: I did find a neat workaround for retrieving complete taxonomy trees as GraphQL.

By installing the module [Taxonomy Menu](https://www.drupal.org/project/taxonomy_menu) one can associate a vocabulary (including it's hierarchy) to a Drupal menu. Using the GraphQL Menu module one can transform this Taxonomy Menu to GraphQL. When inside the query one can use the entity field to retrieve most of the Taxonomy Term data. But this time you'll have the complete hierarchy of the taxonomy.

Below is an example query retrieving the taxonomy that is exposed through Taxonomy Menu named "taxonomyMenuName":

```
  Taxonomy:menuByName(name: "taxonomyMenuName") {
    children:links {
      name:label
      
      url {
        term:entity {
          tid:entityId
          name:entityLabel
          taxonomy:entityBundle
        }
        path
      }
      children:links {
        name:label
        url {
          term:entity {
            tid:entityId
            name:entityLabel
            taxonomy:entityBundle
          }          
          path
        }
      }
    }
  }
```

**Comment by skp3zl** [comment]
The FieldTaxonomyTermParent within the TaxonomyTerm entity doesn't seem to work either. No results are returned.

```
{
  taxonomyTermQuery {
    entities {
      ... on TaxonomyTerm {
        name
        parent {
          targetId
          entity {
            entityId
            entityLabel
          }
        }
      }
    }
  }
}
```
```
{
  "data": {
    "taxonomyTermQuery": {
      "entities": [
        {
          "name": "Parent",
          "parent": []
        },
        {
          "name": "Child",
          "parent": []
        }
      ]
    }
  }
}
```

**Comment by xuxucode** [comment]
@sebkamil The parent property does not work because of the bug: https://www.drupal.org/node/2543726

**Comment by gabesullice** [comment]
That issue just landed. This will be fixed in Drupal 8.6 and the patch can _probably_ be applied to Drupal 8.5 as long as you don't have custom/contrib modules relying on the taxonomy_hierarchy table :)

**Comment by wimleers** [comment]
> This will be fixed in Drupal 8.6

Yep, it already _is_ in fact!

> the patch can probably be applied to Drupal 8.5 as long as you don't have custom/contrib modules relying on the taxonomy_hierarchy table :)

Correct, and at least Facets (https://www.drupal.org/project/facets/issues/2919034) and Taxonomy Manager (https://www.drupal.org/project/taxonomy_manager/issues/2932067) have already been made forward-compatible!

**Comment by fubhy** [comment]
Yai. Cool!

**Comment by lenoirmind** [comment]
Excellent!!
