### ISSUE TITLE
Rename plugin manager services to follow core

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#345]
Plugin managers should follow the `plugin.manager.[snake case plugin name]` naming convention.

**Comment by fubhy** [comment]
I never understood that convention. Why? :)

**Comment by ghost** [comment]
I guess because you don't have to look up the exact name of the service, you expect it to be named like XY.  If you look into core, that's the "standard".

**Comment by fubhy** [comment]
Done.

**Comment by fubhy** [comment]
JFYI, the reason why they are called plugin.manager is because there is a Container Pass in Core that adds cache cleanup logic to all plugin managers.
