### ISSUE TITLE
[Question] Authentication with GraphQL

### ISSUE THREAD

**Issue by webexpert5** [drupal-graphql/graphql#357]
Hi there,

I am planning to use React, Apollo and Graphql on a production website.
I have the basic setup running and graphql queries work very well.

I could not find much documentation for the version 3 of the module.
What I would like to know is how to do the authentication and make subsequent graphql requests as that user.
Entity Access and Field Access already works on drupal graphiql. So I guess we just need to pass user information while making graphql request from our apollo client. How can I do that?

Could you please provide me some leads on this. 

Thank you for your time.

**Comment by fubhy** [comment]
Hi! You can use the standard Drupal authentication flow with AuthenticationProviders. We've done that recently with a custom JWT Token based AuthenticationProvider in conjunction with auth0. Basically, all you need to do is to enhance your request header (via the Apollo network interface) with the JWT Token. When the request then hits Drupal it takes that JWT Token and authenticates you and logs you in as a Drupal user. The GraphQL Query then automatically respects that user's access permissions.

**Comment by fubhy** [comment]
https://www.drupal.org/project/jwt

**Comment by webexpert5** [comment]
Thank you very much for your guidance.
It totally worked. 

For authenticating users against our drupal user base, I suppose I could create a new login mutation, that takes in the credentials and return JWT token generated by JWT Authentication Issuer module.

Do you think, this could be a part of the module in the future. (For people who do not want to use external auth provider)

**Comment by fubhy** [comment]
@webexpert5 yes, absolutely, that would be possible. Creating a mutation plugin for that should be fairly simple. Remember though that while using Apollo that means that after successful login you'd have to somehow store the JWT token in some sort of state and then PURGE the apollo cache entirely because the now logged in user status might affect the returned data.

**Comment by fubhy** [comment]
I am not sure. It sounds like this would be part of a graphql_jwt module. Not sure if we would want to add that to the graphql modul ebecause we recently decided that all contrib module integrations should live in separate modules.

**Comment by sebas5384** [comment]
@fubhy I did mutations for login and logout for a normal cookie login which ease an admin semi decoupled from Drupal, like an admin theme inside Drupal it self.

Do you think it make sense having those mutations as part of the module? if it is, I could sent a PR with it tests.

**Comment by fubhy** [comment]
I don't think that should be part of the core graphql core module. It highly depends on your implementation on the client side. E.g. your solution only works if the TLD is the same which is probably not the case in most situations.

**Comment by fubhy** [comment]
I think that should be in a graphql_session_auth module or so.

**Comment by sebas5384** [comment]
@fubhy Yeah you're right! but consider that I have seen and deliver some projects using a semi decoupled approach which works really well when you don't need a node server, like traditional SPA's without SSR.

I'll create a sandbox module with that name, I liked 👍 

Cheers!

**Comment by ghost** [comment]
I have implemented login mutation which can serve JWT or session data. I have decided to remove the session option since I do not want to store any data in sessions(like messages) so this will make sure sessions will be available only via UI.

But if somebody is interested, this is my code. It is a bit hacky but it was the only working solution:
```

public function createSession(int $uid): ?SessionBag {
    $session_options = $this->sessionConfig->getOptions($this->requestStack->getCurrentRequest()) + session_get_cookie_params();
    $session_id = Crypt::randomBytesBase64();

    // @see \Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag
    // @see \Symfony\Component\HttpFoundation\Session\Session::set()
    $data = [
      '_sf2_attributes' => [
        'uid' => $uid
      ]
    ];

    // Special handling for session serialization.
    $current_session = $_SESSION;
    $_SESSION = $data;
    $serialized_data = session_encode();
    $_SESSION = $current_session;

    // @see \Drupal\Core\Session\SessionHandler::write
    try {
      $this->database->insert('sessions')
        ->fields([
          'uid' => $uid,
          'hostname' => $this->requestStack->getCurrentRequest()->getClientIP(),
          'session' => $serialized_data,
          'timestamp' => REQUEST_TIME,
          'sid' => Crypt::hashBase64($session_id)
        ])
        ->execute();
    } catch (\Exception $e) {
      watchdog_exception('foo', $e);
      return NULL;
    }

    return new SessionBag(
      $session_options['name'],
      $session_id,
      $session_options['cookie_lifetime'] + REQUEST_TIME,
      $session_options['path'],
      $session_options['cookie_domain'],
      $session_options['cookie_secure'],
      $session_options['httponly']
    );
  }
```

**Comment by breidert** [comment]
@sebas5384 Did you already create the sandbox? We have a similar usecase and would like to see you code.

**Comment by shawnmmatthews** [comment]
@sebas5384 Just making sure this wasn't answered in a PM, but I'd also very much like to see a sandbox example of this. Thanks in advance!

**Comment by sebas5384** [comment]
Hey @shawnmmatthews and @breidert sorry about the delay to answer!

We didn't upload it to a sandbox yet, but I'm planning to upload some contribs at the https://decoupleddevdays.com which is in a few days.
Our sandbox module is a little outdated now since the Graphql module has changed so much since then, so I should have to upgrade it first which is something I have to do it anyways.

**Comment by shawnmmatthews** [comment]
Hey @sebas5384 did you end up building out a sandbox for devdays? If so I'd still be super interested in seeing it. Sorry to pester you. Thanks again!

**Comment by klausi** [comment]
I just caught a security issue in our internal code base because we did not implement the user login correctly (forgot flood control and checking blocked users). This is highly security related code, so we will have to write a graphql_jwt module which issues a JWT on a user + password request correctly. I think it is important to have that publicly on drupal.org, otherwise people will make the same mistakes again and again if they have to implement their login graphql mutations themselves.

**Comment by rthideaway** [comment]
Hi there. Rolled a small module which should do that. It's very a simple thing, where in graphql query it's just doing an internal subrequest via http kernel service to login as regular drupal user would do. So basically everything regarding the user is evaluated, such as authorization with password, flood control, checking blocked users, etc. When all of this is successful, the JWT token is then generated and returned in a response.

Module link:
https://www.drupal.org/project/graphql_jwt

**Comment by joaogarin** [comment]
I think would be nice to standardize as much as possible at least a simple approach to authentication such as this. We could add some simple docs on how that works, maybe if there is interest add it to the related projects in the readme or even under the drupal-graphql umbrella

**Comment by sebas5384** [comment]
@shawnmmatthews some years later xD here's a snippet of what we use to login our users using cookie https://gist.github.com/sebas5384/ab0da24e6091f96a6cced2cb6fb0e069

**Comment by ndrake0027** [comment]
This issue gave me a lot of good ideas on how to implement authentication and use that auth with the 4.x branch. Felt it might be helpful to drop some info for the next person who comes across this on their google journeys. 

I ended up using the drupal JWT module along w/ the patch here https://www.drupal.org/project/jwt/issues/2957273. The code adds a sub-module that appends a JWT token to the REST login endpoint. It was based on another contrib module, https://www.drupal.org/project/getjwtonlogin
