### ISSUE TITLE
Keep available variables in templates (graphql_twig)

### ISSUE THREAD

**Issue by unamaria** [drupal-graphql/graphql#363]
Twig templates in Drupal 8 have a bunch of variables already available (like [node.html.twig](https://github.com/drupal/drupal/blob/8.4.x/core/themes/classy/templates/content/node.html.twig)). It'd be nice to keep those and, in addition, have all the data from the graphql query.

**Comment by pmelab** [comment]
The template with the root query will receive an additional `graphql` variable with `data` and `errors` properties.
