### ISSUE TITLE
New separate Schema refactor breaks graphql endpoint

### ISSUE THREAD

**Issue by stewest** [drupal-graphql/graphql#369]
After this update - drupal/graphql dev-3.x (9f58cd0 => ded7454):  Checking out ded7454a7f things broke.

In Explorer we get 

SyntaxError: Unexpected token < in JSON at position 2

And in error logs
/en/graphql/undefined

**Comment by fubhy** [comment]
I can't reproduce this. Can you check again with the latest version or provide additional information / steps to reproduce?
