### ISSUE TITLE
Interfaces will inherit fields only for one level

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#371]
I have interfaces: Entity -> ContentEntity -> FooEntity

I have field EntityUuid attached to:
FooEntity = present
ContentEntity = present in FooEntity
Entity = not present in FooEntity

**Comment by pmelab** [comment]
Thats true. [FieldablePluginTrait](https://github.com/fubhy/graphql-drupal/blob/abeb355800d559486ae7b299b67c8f29f385a375/src/Plugin/GraphQL/Traits/FieldablePluginTrait.php) needs a recursive interface list to properly build all fields.

Thanks!

**Comment by fubhy** [comment]
This already works as proven in this test: https://github.com/fubhy/graphql-drupal/issues/371
