### ISSUE TITLE
Rename "types" annotation attribute to "parents"

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#379]
The Type and Types in the plugin annotation is very confusing. It should be more clear what each of those attributes represent.

The types is described as:
> The id of the GraphQLType or GraphQLInterface this field is bound to. If omitted, the field is considered a "root" field.

From that context, it would make more sense to rename it to **parent** or **attached_to**.

The type is described as:
> The field type.
> Must be a registered Interface, Type, Scalar or Enum.
> If an associative array is provided - the Enum type will be created
> automatically for the given set of values. But $enum_type_name has to be
> defined in this case.

This description/implementation is confusing on itself. Anyhow, it would make more sense to rename this field to **provides**, **represents**, **graph_type**, **field_type**, **data_type** or something in that manner.

**Comment by ghost** [comment]
Also **secure** could be renamed to **public**.

**Comment by fubhy** [comment]
While I can see that renaming "types" to "parents" might make sense, renaming "type" to something else doesn't. It's called "type" in the graphql-js reference implementation and all sudo code examples from all parser libraries in all languages too.

I don't have any opinion about "secure".

**Comment by blazeyo** [comment]
+1 for **types**. **attached_to** best describes the purpose IMHO but **parents** is a good choice too.

**Comment by fubhy** [comment]
I'd be +1 for "type" and "parents". Can you submit a PR for this?
