### ISSUE TITLE
Derived type not being recognized

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#383]
I have custom entity query gql **field** that has deriver for each supported entity type and it uses the "[entity type]QueryResult" gql **type**(for example NodeQueryResult).

Then I have the EntityQueryResult gql **type** that has deriver for supported entity types. But for some reason these derived gql **types** are not being recognized and the EntityQuery gql **field** will throw error about missing **type** and null being provided in the type collector.

When I debug the code the gql type is correctly set in the plugin annotation but there is null in the gql config of that gql type.

The query result has only id, name and deriver and in deriver I only change the name(EntityQueryResult -> NodeQueryResult). I am wondering if this might be an issue with lack of interfaces defined for this gql type or something else?

Using single EntityQueryResult gql type works fine, just like graphql_core module does.

--

Additionally it might be an issue with order of plugin parsing. For example the gql fields are parsed before the gql types are or before the deriver for gql type kicks in.

**Comment by ghost** [comment]
Seems the issue is somewhere else.

**Comment by fubhy** [comment]
This is likely caused by a typo in the type name you reference in "types" (the plugin manager cannot find the plugin and then returns NULL for the plugin instance which the type collector doesn't like).
