### ISSUE TITLE
Config entities

### ISSUE THREAD

**Issue by blazeyo** [drupal-graphql/graphql#387]
How should we handle configuration entities and references to such (e.g. node type, user roles, etc)? Right now it's only possible to get the id via the `target_id` property of the reference field.

**Comment by fubhy** [comment]
Well we definitely do want to expose config entities. @peterkeppert started a PR here https://github.com/fubhy/graphql-drupal/pull/299

But it does not expose any config values. Just the config entity properties. That would need to be added. Do you want to work on that?

**Comment by blazeyo** [comment]
Sure. Do you think #299 is ready to merge?

**Comment by fubhy** [comment]
I'd prefer to first finish the full PR (including config values) and then review it as a whole. You can start off of #299 though.

**Comment by fubhy** [comment]
Duplicate of #64
