### ISSUE TITLE
Add current feature set to README.md

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#39]
We should add the current features (caching, batching, persisted queries, graphiql, base classes, etc.) to the readme.

**Comment by kirkilj** [comment]
I'd welcome this as well as updating  the project description on Drupal.org, which currently states:

Known Limitations
The Schema is not fully Relay compliant
Currently does not expose Config Entity Types
Mutations are currently not supported

**Comment by bartfeenstra** [comment]
I'm not sure how mutations are not supported, but we have been using them successfully for a while now.

**Comment by kirkilj** [comment]
This is an issue concerning just the _description_ of the functionality, not the working functionality itself. This is just a "documentation" issue. When I heard about Drupal having support for GraphQL, I looked at the documentation and almost ruled out using it, until I asked around on Slack.

**Comment by bartfeenstra** [comment]
Hah, you're right. I totally misread and misinterpreted your comment. Sorry for the needless ping! :)

**Comment by fubhy** [comment]
Yes. Agreed. I suck with Documentation and marketing text. Any takers?

**Comment by kirkilj** [comment]
Hi Sebastian, I'm an amazeeio hosting customer and have worked with Amazee's Austin team for consulting services. I'm game for helping with the documentation. I just need a way to track the current feature set, caveats, etc.. I can obviously look at the code comments, issue cue and commit comments from GitHub and D.O. If that's not sufficient, than I may also harvest information from Michael and Brandon in your Austin office. The DrupalCon session materials (video) will indicate where the project is right now, I'd imagine.

**Comment by fubhy** [comment]
@kirkilj I am going to be in Austin between 1st and 12th of May. Feel free to join me there for some code/documentation sprinting on the module. If you want to start before then, I'd suggest you join us on slack. If you send me your e-mail address I can invite you to the #graphql channel on the Amazee Labs slack server.

**Comment by kirkilj** [comment]
I'm under the gun right now, but I'll make sure to get together when you come to town. I look forward to it.

**Comment by fubhy** [comment]
I updated the project page at https://www.drupal.org/project/graphql

**Comment by fubhy** [comment]
Also updated the README.

**Comment by fubhy** [comment]
@kirkilj I am in the Amazee Labs offices in Austin until the 11th... In case you want to come by for some code/documentation sprinting on GraphQL. There's a lot of stuff happening atm.
