### ISSUE TITLE
Invalid schema should fail silently

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#396]
For the past week I have been building large schema and most of the time I get this error:
```
The website encountered an unexpected error. Please try again later.
TypeError: Argument 1 passed to Drupal\graphql\GraphQL\Utility\TypeCollector::doCollectTypes() must implement interface Youshido\GraphQL\Type\TypeInterface, null given, called in web\modules\graphql\src\GraphQL\Utility\TypeCollector.php on line 127 in Drupal\graphql\GraphQL\Utility\TypeCollector::doCollectTypes() (line 49 of modules\graphql\src\GraphQL\Utility\TypeCollector.php).
```

due to #373 it is hard to find out the issue. Anyway, when this happens the whole site is down. I cannot access any route. I think this is really bad DX and the error should be logged into watchdog and only when calling the `/graphql `the error should be visibly shown.

**Comment by fubhy** [comment]
It should actually be fairly simple to find out the issue by just setting a breakpoint there and checking if you are referencing a non-existant type there or by stepping back into the plugin manager to find out which plugin instance is null.

However, I can feel your pain because we simply do not have a pre-schema validation check in place which could be used for protecting against these issues in the first place. This is also partly due to how the parser library works. Would you like to work on this?

**Comment by ghost** [comment]
I have tried to figure out the issue but it always seems that the "type" in the youshido config is empty whereas it is correctly set in the plugin definition. So far I have always been able to fix it, although most of the time I sincerely have no idea how :D

I could work on gql(I have created some issues already) but not at this moment since I have to finish the schema I am working on at this moment. But later, sure. GQL will be a massive part of large commerce distro I'm rewriting so I'll be working with gql on daily basis.

**Comment by fubhy** [comment]
@ivanjaros for the future I can give you this tip: Usually, a type is NULL if there is an exception in the PluggableSchemaManager in createInstance. There is a try/catch block there. If it ends up in the /catch/ block the plugin instance will end up as NULL. This is the root of the issue in  most cases. It means that either you have a typo somewhere when referecing a type (enum, scalar, interface, whatever) or that a plugin is simply faulty.

**Comment by fubhy** [comment]
Sorry, I meant TypeSystemPluginManager.

**Comment by fubhy** [comment]
> I could work on gql(I have created some issues already) but not at this moment since I have to finish the schema I am working on at this moment. But later, sure. GQL will be a massive part of large commerce distro I'm rewriting so I'll be working with gql on daily basis.

That's cool. I've seen your issues and it's definitely helpful. I'd love to also see some pull requests for some of them in the future and I am looking forward to having you on board for that.

**Comment by fubhy** [comment]
Will follow up in #150
