### ISSUE TITLE
Simplify typed data field types

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#398]
@blazeyo, @fubhy: Is there a reason we derive a field item type for every field storage instance?
Right now there are `TypeNodeFieldImage` and `TypeUserUserPicture`. Couldn't this be simplified to `ImageItem`? It's very complicated to add new graphql fields to the current field types.

**Comment by fubhy** [comment]
That's right, we should not derive per bundle here. The schema should be identical regardless of the bundle. There IS a possibility of there being a mismatch. But only if there are computed typed data properties on the field that change by bundle. I am not 100% sure if that's posisble but the storage is definitely identical.

**Comment by pmelab** [comment]
Lets find out if there can be properties only for a specific bundle. We could go for types per bundle and an interface per storage type. But thats  a significant increase of schema size i would like to avoid.

**Comment by fubhy** [comment]
Is the field storage instance bundle aware? If not, we can rule that out already.

**Comment by blazeyo** [comment]
@fubhy Field storage is not bundle aware AFAIK.

**Comment by fubhy** [comment]
Then let's simplify it.

**Comment by fubhy** [comment]
Solved in https://github.com/drupal-graphql/graphql/pull/400
