### ISSUE TITLE
To high time consuming function InterfacePluginBase::resolveType

### ISSUE THREAD

**Issue by iamake** [drupal-graphql/graphql#402]
Is there a plan to improve the performance of the function InterfacePluginBase::resolveType ? I have been optimizing my Drupal GraphQL application and found out this function takes over 90% of the total time. The function is invoked when we query a property with type Entity.

https://github.com/drupal-graphql/graphql/blob/2e9ca9b67fa35f14d0338eef8c8af1e5d945c70c/src/Plugin/GraphQL/Interfaces/InterfacePluginBase.php#L87

**Comment by fubhy** [comment]
Already solved.

**Comment by fubhy** [comment]
There is an open pull request that will resolve this: https://github.com/drupal-graphql/graphql/pull/401/files#diff-9564d6fdc46f3187c42f41919d40d0f3R82
