### ISSUE TITLE
Use singular expression instead of plural in plugin namespaces

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#408]
Standard for Drupal plugin namespace naming is to use singular expressions. For example Plugin/Field/FieldFormatter, Plugin/Block ...

The GraphQL uses plural expressions like Plugin/GraphQL/Interface**s**, Plugin/GraphQL/Type**s** and so on. This goes against the "standard" and can surprise new developers.

**Comment by fubhy** [comment]
This would be an unnecessary API break for now. Furthermore, this would not work anyways because "Interface" is a reserved word in PHP and we cannot use it. For now, we'll stick with the plural names even if it is against Core principles. It does not bother me enough to warrant an API break.
