### ISSUE TITLE
StringHelper::propCase should lowercase all characters if argument is all uppercased

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#410]
Purpose of `StringHelper::propCase` is to use lower case characters to split words. This is working just fine but in case the provided value is something like `UUID `or `ID` the result is ugly `uUUID` or `iD`. I think that in such cases the intent of lower-casing the words should take over the original string completely and in this case return completely lower-cased string. So `UUID` will become `uuid` whereas `FooBar` will be still `fooBar`.

I have encountered this when working with config entity fields.

Something like:
```
public static function propCase($components) {
    $result = static::camelCase($components);
    return ctype_upper($result) ? strtolower($result) : lcfirst($result);
  }
```

**Comment by fubhy** [comment]
Fixed in beta preparation PR.
