### ISSUE TITLE
GraphiQL does not show schema

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#415]
The GraphiQL does not show schema but it performs query just fine. Since there is the Voyager script available this is not an issue. But Voyager does not show mutations so now I have no way of seeing them in an UI.

Also there are no watchdog or js errors. Although for some reason graphiql calls `/function()%7Bn()%7D` url which will return 404 so that might have someting to do with it.

PS: I am using the latest version, download today with last commit showing 4 days ago.

**Comment by fubhy** [comment]
Works for me with the standard graphql and graphql_core module enabled (and nothing else).

**Comment by fubhy** [comment]
I cannot reproduce this. Sorry!

**Comment by ghost** [comment]
If someone's interested - Firefox will NOT show any errors but Chrome will!

In my case, it turned out you cannot have empty interfaces(ie. no fields).
