### ISSUE TITLE
[question] Support of GET method for Queries (not mutations)

### ISSUE THREAD

**Issue by sebas5384** [drupal-graphql/graphql#416]
The module currently supports using the GET method for queries? just queries, not mutations.

**Comment by pavlosdan** [comment]
Yes it does. You need to pass your query to the query parameter of the endpoint. So something like:
http://mydrupalsite.com/graphql?query=myquery :)

http://graphql.org/learn/serving-over-http/#get-request

**Comment by fubhy** [comment]
Exactly. You can also use GET with persisted queries using "id" and "version" arguments.
