### ISSUE TITLE
Mutations not showing up in beta 1

### ISSUE THREAD

**Issue by bogue** [drupal-graphql/graphql#418]
Just updated to beta 1 -- quite the cleanup, thanks!

Oddly enough, mutations aren't showing up anywhere (explorer, voyager, ...), am i missing something? Un/reinstalled and disabled custom fields, to no avail; no error message. 

P.S: is anyone hanging out anywhere for quick drupal-graphql chats? Seems like this may not be an issue-worthy question.

**Comment by fubhy** [comment]
We are in the drupal slack in the #graphql channel. Feel free to join us. 

Automatically generated Mutations have beem removed for now to pave the way for a first stable release. Please check the release notes / changelog for further information.
