### ISSUE TITLE
Scalars forgotten?

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#420]
I have noticed that scalar plugins don't use plugin names nor descriptions. Seems like those plugins got kind of forgotten?

**Comment by ghost** [comment]
Seems the base class is missing which should call:
```
/**
   * {@inheritdoc}
   */
  public function __construct(array $configuration, $pluginId, $pluginDefinition) {
    $this->constructPlugin($configuration, $pluginId, $pluginDefinition);
  }
```

**Comment by fubhy** [comment]
We can't have a base class here. Adding a constructor to each of them.
