### ISSUE TITLE
Make entityQuery filtering and sorting more flexible

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#421]
EntityQuery could use the same concept of "fancy filters" as JSON API does, and even share the code.

https://gist.github.com/e0ipso/efcc4e96ca2aed58e32948e4f70c2460

**Comment by ghost** [comment]
Looks interesting but:
I have a custom per-type-entity query that has entity-specific sorting(ie. sort only on fields attached to the entity type) and conditions(apply condition only to fields attached to the entity type).

This requires a lot of derivers.

Looking at that proposal I cannot imagine being able to make the conditions and sorts entity-type-specific since the design allows grouping and nesting and whatnot. So I assume the developer would have to know the fields from another source and not directly from schema.

**Comment by pmelab** [comment]
Yes, we would need to figure out typing. But it think even untyped this could be beneficial.

**Comment by ghost** [comment]
Looking at the original structure, that is actually quite doable. The second proposal(last comment) is a bit scary.

**Comment by e0ipso** [comment]
Excited to see progress on this already! I lack implementation knowledge in this project but I have _some_ GraphQL familiarity and a lot of familiarity with Fancy Filters.

Ping me if you think I can help.

**Comment by fubhy** [comment]
I submitted a pull request for this feature: https://github.com/drupal-graphql/graphql/compare/entity-query-filter?expand=1

**Comment by fubhy** [comment]
Merged!

This now allows queries like e.g. this:

```
{
  nodeQuery(filter: {
    conjunction: AND
    conditions: [{
      field: "nid"
      value: ["1", "10"]
      operator: BETWEEN
    }]
    groups: [{
      conjunction: OR
      conditions: [{
        field: "title"
        value: ["graphql filtering rocks"]
      }, {
        field: "title"
        value: ["graphql is awesome"]
        operator: LIKE
      }, {
        field: "uid"
        value: ["1"]
      }],
      groups: [{
        conjunction: AND
        conditions: [{
          field: "field_tags.target_id"
          value: ["1"]
        }]
      }]
    }]
  }, sort: [{
    field: "nid"
    direction: ASC
  }, {
    field: "uid"
    direction: DESC
  }]) {
    entities {
      entityUuid
      entityBundle
      entityPublished
      entityType
      entityChanged
      entityId
      entityCreated
      entityLabel
    }
  }
}
```

**Comment by philbert440** [comment]
did this make it into version 4.x?

**Comment by pmelab** [comment]
It does not really apply, since with 4.x you would define your api yourself.
