### ISSUE TITLE
Text (formatted, long) no longer accessible directly via the query after upgrading to Beta1

### ISSUE THREAD

**Issue by pavlosdan** [drupal-graphql/graphql#425]
Previously in alpha7 a field (Text (formatted, long)'s value was directly accessible using:

{
  fieldRichTextWidget
}

now to get the same result one needs to do:

{
  fieldRichTextWidget { 
    value
  }
}

even though the explorer reports that inside the 'fieldRichTextWidget' there is only a string. (please see screenshot)

![screen shot 2017-11-02 at 3 49 57 pm](https://user-images.githubusercontent.com/5995324/32315055-8bb4fe96-bfe5-11e7-8fcb-6f48897f02aa.png)

**Comment by pmelab** [comment]
Did you add `graphql_legacy`?

This is on purpose (see the [release notes, 2nd bullet](https://github.com/drupal-graphql/graphql/releases/tag/8.x-3.0-beta1). This behaviour is still available in [graphql legacy](https://github.com/drupal-graphql/graphql-legacy), but the preferred way is to use the `processed` typed data property, which will provide the same result (and the trimmed text as well).

**Comment by pavlosdan** [comment]
No I didn't add legacy as it said it's not meant to be used:
"These modules have been deprecated and should not be used."

Thought it may be better to rewrite the queries than using code that's deprecated.

**Comment by pavlosdan** [comment]
I see in Voyager the same field has the properties: processed, format and value. Shouldn't explorer have the same?

**Comment by pmelab** [comment]
Yes, they use the same data. Sounds like a caching issue to me.

**Comment by pavlosdan** [comment]
duh yes. cleared the browser cache and refreshed. yes now it reports the new properties!

**Comment by pavlosdan** [comment]
Thanks! closing this :)
