### ISSUE TITLE
Provide field access check

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#427]
It is ok to see/explore the schema via voyager/graphiql so one can see the possibilities and basically the spec but there should be access check in place for actually being able to call specific **root** fields and mutations. For example dev A with user role "authenticated" can see createNode() mutation but only dev B with user role "content editor" should be able to actually invoke it.

Implementing access check into individual fields is unrealistic.

It should abide the same principle as hook_entity_field_access.

Sure, we can simply create two schemas and change permissions on route level but that seems like bad DX and essentialy UX as well.

PS: I see there is "secure" attribute available in annotations but from the looks of it it seems like its all or none approach and personally I don't get it.

**Comment by sebas5384** [comment]
@ivanjaros agree with you.
Some ideas:

1. `permissions` property for the plugins definitions where you could specify more than one permission.
2. Each field has it's own permission created when a field plugin is defined, for example: `view graphql mutation nodeCreate`, `view graphql field author`, `execute graphql requests to field author` or `execute graphql requests to mutation nodeCreate`. Permissions could be created with a parent prefix to indicate that the access is only granted to specific cases when a field is on a parent type, for example: `view graphql field author at node`.

I think permission to view or execute are the same, if you can't execute the field or mutation, why it should be visible on the schema?

**Comment by fubhy** [comment]
@sebas5384 GraphQL Schemas are never be per-user / per-permission by default. You can always SEE everything in the schema, but the access restrictions will disallow execution of a mutation of querying of a field if you don't have the proper permissions. You can of course make permission sensitive schemas yourself if you wish to do so for whatever reason but it is strongly discouraged. In fact, some of the more advanced features e.g. persisted queries as well as simple introspection will run into huge problems if you do this. So yeah, don't (because there is also no good reason to do so). Security comes through restircting access on the actual field execution level, not by simply hiding it.

@ivanjaros Why is it unrealistic to add access checks in every single field? That's what we have been doing all along. In some way, GraphQL operates at the same level as Drupal theme rendering. You have to check access on what you are rendering yourself too and it makes perfect sense. Also, it's not a lot of work to simple call ->access('view') on an entity before returning it from a resolver.

That said, it wouldn't be hard to add field-level permissions (remember though, not for the schema but for execution, we will not add schema-level field access). But before we do that, someone has to convince me that that makes sense.

**Comment by pmelab** [comment]
All the core fields derive their access from Drupal mechanisms (entity access, routing access etc.), but it would make sense to provide an easy option for custom plugins. A permissions property could make sense in some cases, in others you would probably wan't to handle permissions based on context/arguments.

@ivanjaros: The `secure` property is something different. Fields that are not marked secure are automatically blocked in untrusted environments. For example there is a field that allows to fetch content from a remote url, which would basically turn your website into a proxy for anybody. This field will only work with a certain user permission or in persisted queries, where we are in control of what they do. The other way around, a field that is marked as *secure* doesn't allow any operations drupal itself wouldn't.

**Comment by ghost** [comment]
@fubhy you've misunderstood. I do implement entity access checking in fields that do entity stuff.
My points is that the GQL field itself should not care about who can access/execute it.

The field is visible in schema and that is totally fine. I am talking about the fact that if the client tries to perform a query, each (root?)field in that query should invoke access check to see if the client can retrieve information returned by the field, again, like `hook_entity_field_access` does. Access results can be cached, so performance-wise it's fine. If the user does not have access, null is returned(or probably error message, depends on the implementation).

Imagine GQL field as entity field formatter. The formatter does not care about access. That is handled in higher layer before the formatter is even invoked. Same goes in GQL. You know the field is there, but when you try to invoke it, access control takes place before the field is even invoked.

@sebas5384 I think a permissions/s in the annotation is not a bad idea, as basic access control, but keep in mind that the annotation is cached so you will need alteration in place to have dynamic access control no matter what + I do not think I have particularly large schema yet, but I have a shitload of fields so defining/generating a permission for each field would be **too much**, IMHO and I don't think auto-generating permission for each field would be a good idea.

If you need fine-grained access control, it should be custom implementation. By default, the `hook_entity_field_access`-like approach would be better base for access system.

If you look at `\Drupal\graphql\GraphQL\Execution\Processor::doResolve` there is "secure" check. Adding something like `\Drupal\Core\Entity\EntityAccessControlHandler::fieldAccess` should not be difficult.

**Comment by fubhy** [comment]
> @fubhy you've misunderstood. I do implement entity access checking in fields that do entity stuff.
> My points is that the GQL field itself should not care about who can access/execute it.

If I understand you correct, I strongly disagree with this proposal. Fields should be in charge of determining access. This gives us maximum flexibility. Also, not all fields are related to entities / drupal fields, so building something like automatic entity / field access checks into the processor would be bad. We could add a ``->access()`` method to FieldPluginBase which would get the same arguments as the ``->resolve()`` method and could return an access result (or TRUE/FALSE, like in Core) for fields that actually want to implement e.g. permission based access checking. If that method would return FALSE, we would simply not call the resolver and directly return NULL. Personally, I don't like this approach however, I think each resolver (each field plugin you create) should simply handle that in ``->resolve()``. This is also what other implementations like plain graphql-js advocate.

**Comment by fubhy** [comment]
Discussed this with @pmelab. We believe this should be implementedi n each resolver individually. If you want to make it more generic, you can always add this in your submodule by either providing a base class for your field plugins or implementing an interface that you then check for in your processor and do some fancy generic permission checks in.

**Comment by joaogarin** [comment]
> All the core fields derive their access from Drupal mechanisms (entity access, routing access etc.), but it would make sense to provide an easy option for custom plugins. A permissions property could make sense in some cases, in others you would probably wan't to handle permissions based on context/arguments.

@pmelab does that mean that if one implements hook_entity_field_access that should be respected when running a mutation as in https://github.com/drupal-graphql/graphql-examples/blob/master/src/Plugin/GraphQL/Mutations/CreateArticle.php for example?

**Comment by abelass** [comment]
Finally how is this implemented. 

I have field restrictions added via hook_entity_field_access but they only seem to be partially respected, most of the fields return their value even if they are restricted. How can I make the restrictions effective so graphql only returns values for fields the user is allowed to view?
