### ISSUE TITLE
Could userQuery return User instead of Entity?

### ISSUE THREAD

**Issue by blazeyo** [drupal-graphql/graphql#428]

**Comment by fubhy** [comment]
That would mean that we would have to have a dedicated return type for each entity query field. Surely possible, but is it worth it?

**Comment by blazeyo** [comment]
No idea :). I was just playing with graphiql and I found it non-intuitive to have to add a fragment in a field that already defines the type unequivocally, so just wanted to report it as food for thought.

**Comment by ghost** [comment]
@blazeyo I have this implemented. Not that hard really. But I think it should be a custom implementation(ie. your own code). The graphql should provide only the basic API and the graph_core core should provide only the basic fields. I only use the graphql without the core module. Everything is custom.

**Comment by fubhy** [comment]
Yes, this is very easy, no question. But the question is if it  brings much benefit vs. the growing schema size. Size of the schema is a valid concern especially with introspeciton and persisted queries.

**Comment by ghost** [comment]
@fubhy 

> Size of the schema is a valid concern especially with introspeciton and persisted queries.

By introspecion you mean using tools like GraphiQL to visualize/parse the schema, correct? If so, then it is just a matter of sending the json schema to the client when it is requested, so performance/size is not that big of a deal. But what do you mean about persisted queries? Where does the schema size come to play?

**Comment by fubhy** [comment]
Introspection grows in size and is required by tools like apollo/relay to gather information abvout the schema to properly handle caching.

**Comment by fubhy** [comment]
Hence that stuff ends up in the client side javascript it is important to keep an eye on the size of that .json.

**Comment by ghost** [comment]
I see.

OT: How about implementing a switch(header?) that would strip descriptions?

**Comment by pmelab** [comment]
I don't think schema size was part of this decision, but dependency issues between `graphql` and `graphql_core`. One more small return type for each entity type exposed by `graphql_core` wouldn't scale terribly high.

**Comment by fubhy** [comment]
We don't have this dependency issue anymore. So would you suggest we switch to a deriver for this? I don't have a problem with it considering that we will end up with a configurable schema soon anyways.
