### ISSUE TITLE
On Drupal 8.5, GraphQL should respect Typed Data's new ::isInternal()

### ISSUE THREAD

**Issue by wimleers** [drupal-graphql/graphql#429]
# Problem/Motivation
https://www.drupal.org/node/2871591 introduced the ability to mark Typed Data definitions as "internal": `\Drupal\Core\TypedData\DataDefinitionInterface::isInternal()` and `\Drupal\Core\TypedData\DataDefinition::setInternal()` were introduced. Change record: https://www.drupal.org/node/2916592.

This means that both fields and properties can be marked as internal now. The core Serialization and REST modules will respect this, meaning that they will not normalize those fields and properties.

The GraphQL module used to support omitting certain fields through the use of a special "GraphQL" view mode. (The https://www.drupal.org/project/jsonapi module allows something similar via the https://www.drupal.org/project/jsonapi_extras module: "disabling fields". Sister issue at https://www.drupal.org/node/2921257.)

In Drupal 8.5, GraphQL should start using the `setInternal()` API to mark certain fields as internal, which will then also be respected by Serialization/REST in core, and JSON API in contrib.

Of course, the tricky thing is going to be that this will need an update path, because that API addition is only available in 8.5, not 8.4.

# Proposed resolution

1. Update GraphQL to respect 8.5's `DataDefinitionInterface::isInternal()`
2. Perhaps there should be a new contrib module, because this functionality is no longer specific to GraphQL or JSON API — it would affect Serialization + REST + JSON API + GraphQL.

#Remaining tasks
TBD

# User interface changes
TBD

# API changes
TBD

# Data model changes
TBD

**Comment by pmelab** [comment]
@wimleers As discussed in the API-first meeting, we actually do use some "internal" fields, *somewhat* internally 😛

I think this drives us into an ambiguity. Does `isInternal` mean it's not meant to be serialised, but may be accessed through further processing (traversing in graphql) as the `entity` property, or not meant to be exposed at all? How are we supposed to decide between these two?

I think @tedbow said that we are advised to not expose internal fields at all?

**Comment by blazeyo** [comment]
@wimleers just to give you some more background on this one - right now GraphQL is using straight typed data properties, including the `entity` prop of reference fields. This is a query that fetches a tag from an article for instance:

```
query {
  nodeById(id: "1", language: en) {
    ... on NodeArticle {
      fieldTags {
        targetId
        entity {
          name
        }
      }
    }
  }
}
```

The `entity` here is a valid field of type `TaxonomyTerm` that can be used to traverse the entity graph.

It definitely makes sense to hide some properties (like the mentioned `entity`) from the serialized output, however since GraphQL is not serializing any data the `isInternal` might not apply here in the same manner.

**Comment by ghost** [comment]
in my custom entity field implementation, i build fields from field storage and then make a list of field instances(that are not computed) on each entity type and use is as parents. fields that do not have a storage should be added via custom plugin on case-by-case basis.

**Comment by wimleers** [comment]
Now also being implemented at the entity type level. See https://www.drupal.org/project/drupal/issues/2936714 and https://www.drupal.org/project/drupal/issues/2941622.

Note this is being implemented in JSON API at https://www.drupal.org/project/jsonapi/issues/2932035.

**Comment by wimleers** [comment]
See 
https://github.com/drupal-graphql/graphql/pull/571#issuecomment-424721682. Given what happened over at 
https://github.com/drupal-graphql/graphql/issues/643#issuecomment-423528064, it actually has become trivial to support this.
