### ISSUE TITLE
Dispatch events for GraphQL operations

### ISSUE THREAD

**Issue by sebas5384** [drupal-graphql/graphql#430]
I'm using Rules to set some contextual information for some pages, so in order to trigger the rule I need an event to be fired when a query like `route(path: "/node/1") ` is executed.

**Comment by fubhy** [comment]
You could implement this generically by overriding the processor and dispatching an event on every root field or even every field. But we won't add that to the module because I don't see much use for side-effects when executing a graphql query. You can try to convince me though ;). Only thing I can see would be a generic side-effect solution for e.g. debugging / tracking / logging of resolvers and then allowing ppl to attach listeners so they can do whatever they want on that level. But I have to think about that more and currently I don't see a necessity.

**Comment by fubhy** [comment]
This could become relevant once we start talking about adding a profiling interface for schemas. With analytics on executed queries etc.

**Comment by sebas5384** [comment]
@fubhy you're right, I guess I could dispatch an event at the processing time of the query, and that could be really interesting to do side-effects using the Rules module, for example.

My use case is a little different because I need to set the value of a `context` using a customized Rule Reaction, meaning the same behavior of the `Url` children fields (`SubrequestFieldBase`) has which is simulating a request coming to Drupal filling all the contexts that are needed in order to execute the conditions for the rule to be executed.
What we (because I'm not alone on this cc @recidive) did for now is creating a new field with the `Url` type as parent and then dispatch an event like `rules_entity_view:node` before we resolve the field to return the value of the context.

That worked for now, but it would be nice to have some event being fired before a subrequest is executed, so in that way we could have rules changing context values served by context "auto defined" fields.

Dispatching events for side-effects could be really useful, look at what [Graph.cool](https://www.graph.cool/) is doing with their hooks system decoupling logic from their data layer.

**Comment by fubhy** [comment]
These hooks from graph.cool operate on a whole different layer though. They do nothing to the field / resolver. They do not run as "events" when resolving a field but rather as a pre-/post-processing step for database writes / reads. So basically one level deeper. What we are talking about here would basically be a generic field resolver visitor that runs with a onBeforeResolve and onAfterResolve pattern. E.g. allowing to mutate input args / ResolveInfo or even the parent value BEFORE passing it to the resolver and then  allowing to mutate the return value in the AFTER step.

**Comment by fubhy** [comment]
Or not do any mutation at all and instead just log e.g. execution time for profiling purposes for instance.

**Comment by sebas5384** [comment]
@fubhy graphcool has some functions types:
![screen shot 2017-11-07 at 11 05 27 am](https://user-images.githubusercontent.com/97021/32495200-d35a9840-c3ab-11e7-8d7e-f11d7c6294bd.png)

But, in my case I'm not mutating the value coming from the field's resolver, instead the rules reaction is filling the context's value, so the context when is resolved is already with the needed value.

I liked the ideia of before/after resolving events, I guess that would resolve my case, since I'll create a rule which subscribes to the before event having a condition to select what fields I would like to react to, for example the `nodeContext` field.

**Comment by fubhy** [comment]
In that case it should be enough to just override doResolveValue() in the processor and calling something before and something after.

**Comment by sebas5384** [comment]
@fubhy do you think those events could be in core (graphql module)? or a contrib like `graphql_sideeffects`?

**Comment by fubhy** [comment]
I don't see a compelling reason for adding them to the core module for now. As I said, once we start talking about profiling / tracking of queries etc. we can bring this up again but for now it's easy enough to do this in your own project by simply overriding the processor and adding a custom pre/post-resolver hook.
