### ISSUE TITLE
Add descriptions to the plugin definitions of all fields, types, etc.

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#435]

**Comment by fubhy** [comment]
I started with this and added a few descriptions mostly for entities and their fields. If someone could finish this ... :)

**Comment by pixelmord** [comment]
I will see how I can contribute here, currently looking for descriptions on the types myself (entity_reference?)
@fubhy can you point me in a direction where the biggest empty space is for that?

**Comment by scubafly** [comment]
I guess @fubhy is revering to: https://github.com/drupal-graphql/graphql/commit/817b2504bc492976e8db9a9b3f5ed31cd87b3e63
