### ISSUE TITLE
Add support for fetching specific revisions and listing revisions of an entity

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#436]

**Comment by ghost** [comment]
imho this should be a field on the entity itself. it would list all revisions as entities with their fields available just like the active revision.

**Comment by fubhy** [comment]
Yes, that's the plan. But also with a single field for fetching specific revision by their revision id.

**Comment by yched** [comment]
I'm still fairly new to the overall organization of the schema, so I'm not
really opinionated on how we want to shape this.
But if given a temptative spec, I can work on a PR to get my feet wet :-)

On Wed, Nov 8, 2017 at 9:31 AM, Sebastian Siemssen <notifications@github.com

**Comment by fubhy** [comment]
@yched Cool! The first step would be to simple have a "revisions" field on all revisionable entities. For that we would need a deriver based plugin that adds this field to all entities that support it. It would then simply return a paginatable list of entity revisions for the current entity. So it should probably also have arguments for sorting and limiting the number of returned items as well as an offset argument.

**Comment by fubhy** [comment]
@yched Do you want to work on this? Otherwise I would start with an implementation. I actually got a use case for it now :)

**Comment by yched** [comment]
Yeah, sorry, not going to happen before another couple days at least :-/

**Comment by fubhy** [comment]
Started a pull request for that here: #496
