### ISSUE TITLE
There is no examples/step1_query/ directory as mentioned in gitbook

### ISSUE THREAD

**Issue by scubafly** [drupal-graphql/graphql#45]
https://fgm.gitbooks.io/graphql-for-drupal/back/queries.html#exposing-new-queries

I'm not sure where I can contribute to the documentation in this book.
Sorry if I made a wrong issue for this.

Kind regards,

Jack

**Comment by fubhy** [comment]
You can submit PRs for the documentation handbook right here. You can find the documentation handbook files under /doc in this repository.
