### ISSUE TITLE
Add a field for rendering an entity with a specific display mode

### ISSUE THREAD

**Issue by freelock** [drupal-graphql/graphql#451]
Hi,

I've played around with GraphQL a few times now, great work! The first site I installed on was when you had to configure a Graphql display and set the fields up on that display, so I've seen the switch to having fields automatically available without that work. What I'm looking for is slightly different -- the ability to get a rendered entity using a specified display mode -- is this something pretty straightforward to add?

Cheers,
John

**Comment by fubhy** [comment]
That's super easy. Just needs a new derived field plugin for each entity type with an ENUM argument based on the available display modes for that entity type and a return type of "string". The code of that field plugins resolver would just need to call the entity renderer service and pass it the parent entity and the view mode from the arg.

**Comment by wimleers** [comment]
… but I don't think this is something that would be added to GraphQL core, right? I can totally seeing it being a useful contrib module :)

**Comment by fubhy** [comment]
Solved in #495
