### ISSUE TITLE
Cache tags are lost on deferred results

### ISSUE THREAD

**Issue by sebas5384** [drupal-graphql/graphql#452]
Just want to start saying that this bug is not present any more at the current `8.x-3.x` branch since DeferredResult class was removed here: https://github.com/drupal-graphql/graphql/commit/6293661cdf4e5ccf4d506a6f11d1172e63ea5eb9

I have a use case which I needed to generate dynamic cache tags in a field that extends `SubrequestFieldBase` and I couldn't make the `getCacheDependencies()` method to add the cache tag, so after some time I found out why it wasn't working, so here's a patch for the folks using the beta1 and had the same issue.

https://github.com/drupal-graphql/graphql/compare/8.x-3.0-beta1...TallerWebSolutions:cache-tags-deferred-result-beta1

I run all the tests and all passed successfully.

Cheers! and hopes to see a new beta release soon! 👍

**Comment by fubhy** [comment]
Thanks. We will be tagging a new beta this week.
