### ISSUE TITLE
How to obtain data from the fields of a referenced entity?

### ISSUE THREAD

**Issue by Gonzalo2683** [drupal-graphql/graphql#453]
I have two entities created, in one entity I reference the other entity, but when I try to access the fields of the entity that was referenced, I can not get the values. Only the main field appears from where the other entity is referenced, but the internal fields of the referenced entity do not appear.

Any suggestions?

**Comment by blazeyo** [comment]
Check out the _Entity reference fields_ section of this post https://www.amazeelabs.com/en/blog/graphql-for-drupalers-fields

**Comment by fubhy** [comment]
Use a fragment. E.g. "... on NodeArticle { fieldFoo }"
