### ISSUE TITLE
Changing the underlying node doesn't invalidate the route result

### ISSUE THREAD

**Issue by blazeyo** [drupal-graphql/graphql#454]
Steps to reproduce:
- Add a node
- Execute this query with the node path as argument
```graphql
query($path: String!) {
  route(path: $path) {
    ... on EntityCanonicalUrl {
      entity {
        entityLabel
      }
    }
  }
}
```
- Change the node's title
- Execute the query again - title is stale

**Comment by sebas5384** [comment]
@blazeyo yeah, I have the same issue with other fields like entity references.

I believe the cache tags are not being returned for those autogenerated fields/resolvers like nodeContext for example.

Maybe this is fix on the new beta release.

**Comment by pmelab** [comment]
And @blazeyo solved it! @sebas5384 could you help testing and verify that https://github.com/drupal-graphql/graphql/pull/457 did the trick?

**Comment by fubhy** [comment]
Works for me. Good work @blazeyo.
