### ISSUE TITLE
Mutations as field side effects?

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#455]
This might be a dumb question, but what is the reason not to nest mutations as we nest fields (or just mutate as field side effects)? I was looking for one:

https://github.com/graphql/graphql-js/issues/672
https://blog.graph.cool/improving-dx-with-nested-mutations-698c508339ca
https://github.com/facebook/graphql/issues/183

But I couldn't find a real argument, besides API design decisions that might or might not apply to our generic use case. Imagine this ...

```
mutation {
  nodeQuery(status: 0, publishingDate: '> now') {
    setStatus(1)
  }
}
```

... or this ...

```
mutation {
  nodeById(id: 1) {
    fieldComments {
      appendNew(message: "Hi!") {
        ... on Error {
           notify(mail: 'admin@example.com', message: 'You're screwed!')
        }
        ... on Comment {
          parentNode {
            author {
              notify(message: 'You've got a new comment!')
            }
          }
        }
      }
    }
  }
}
```

It feels odd to have this super reusable and composable resolvers for reading but not for writing. The benefits in combination with the Entity API would be tremendous. We even could re-assemble atomic setters (like setting one field value) using buffers.

What would happen If we would change `MutationBase` to be a field with cache max age  = 0 and attach all root level fields to the mutation object? Any opinions?

**Comment by blazeyo** [comment]
I can only say it looks great and I'd be more than happy to help with the implementation.

**Comment by justinlevi** [comment]
Wow, this sounds awesome. Definitely available to help test.

**Comment by fubhy** [comment]
I have got some serious concerns about this. I think we talked about it before @pmelab. But let's clear up two things first:

1. Side effects in read operations (within the query key word) are out of question. I think we can agree on that. 

2. Nested mutations in the way your comment describes them (also the way i see them) look great. But the blog post you linked shows somethint completely different. It actually shows nested input args which we can do without problems. So we don't really need to discuss that. If someone wants to implement something like that for a particular custom mutation nothing stops you from doing that. Lets call this nested input. 

Nested Mutations sound and look intriguing and they would indeed open a few nice possibilities. There is nothing in the spec that prevents us from implementing them but they are also not particularly mentionened or advised. And I also have some serious concerns. Explained in the last abstract. In fact, Lee Byron spoke out against them although he did not make a clear case imho/afaik yet. So another concern would be that we might be moving against the flow with this. I would hate to implement something that works against the Common understanding of GraphQL and the spec. Maybe we can get a more concrete answer from @leeb whether we would be doing somethint nasty here. Maybe we are missing something else. But here is my main argument against it which basically all boils down to #1 explained above already:

When a mutation returns a complex type you are basically again looking at a type from the query part of your schema. E.g. a createComment mutation simply returns the "Comment" type. It thereby allows you to query stuff right after executing a write operation. This is very useful e.g. for updating a client side cache that might be affected by the mutation. Apart from validating a write operation / reacting to errors / input validation this is the main reason for mutations reaching into the type system from the query part of your schema. 

Now if you want to have a nested mutation on that returned type you would also be adding it to the query schema. E.g. a "like comment" mutation on the "create comment" return type "comment". That field would also appear in your query schema. So we would be at point #1 I made earlier. Not cool.

This is the main reason why I oppose this idea. In my opinion it is not compliant with the way the GraphQL spec currently works for mutations. It seems to be specifically designed for mutations as root fields.

**Comment by fubhy** [comment]
Mutation fields on nested types would somehow have to be muted in the "query" schema. This would require a change in th spec. Feel free to argue about that in the main graphql repo but I really think this would be mistake to do on our own.

Please re-open if you think this needs further discussion.

**Comment by pmelab** [comment]
> Side effects in read operations (within the query key word) are out of question. I think we can agree on that.

I agree. But this could be a set of types and fields that are used by mutations only.

>  I would hate to implement something that works against the Common understanding of GraphQL and the spec.
> ...
> This is the main reason why I oppose this idea. In my opinion it is not compliant with the way the GraphQL spec currently works for mutations. It seems to be specifically designed for mutations as root fields.

Thats also my major concern. But this doesn't mean we have to shut it down immediately. The potential benefits are too big to at least discuss and get a couple of opinions.

**Comment by fubhy** [comment]
Then this conversation should me moved to the official graphql repo with a suggestion for how to add this to the spec in a way that does not conflict with the "no side effects in read operations" mentality.

**Comment by justinlevi** [comment]
You guys have infinitely more knowledge about the GraphQL Spec and the overall architecture of this project but at the core I believe we are really talking about Developer experience. Having just gone through the process of creating a very simple mutation, I can say with some confidence that the barrier to entry is still way too high. 

Implementing something like what @pmelab has proposed would dramatically reduce the friction of a large audience adopting GraphQL in Drupal projects. I think this is especially applicable given the move to address the Drupal editorial experience. 

The work you guys have done so far is frankly amazing and the architecture is quite beautiful the more I get to know it. If there is any way to abstract away the complexity of mutations, I think that is a very important discussion.

Oh, and thanks again! This is the most interesting project I've seen in a while.

**Comment by fubhy** [comment]
@justinlevi I am not sure it would actually affect DX when *creating* new plugins (creating new mutations) in code. You'd still have to write the code yourself. That only goes away once we generate mutations which we currently don't do.

**Comment by justinlevi** [comment]
I may have misunderstood the proposal in rereading this. @fubhy I think you're right that the DX would probably not be impacted all that much in this case.

**Comment by pmelab** [comment]
Yes, the way we create mutations would stay the same. It would still improve DX. Just the *D* is the client developer.

I see 2 problems being addressed here:

* To modify an entity you have to know it first. Currently this requires a query request and a mutation request. Not a dealbreaker, just a convenience thing.
* Mutations are not reusable. Drupal users expect functionality to be built from reusable components without writing code.

Both could also be solved by integrating with [rules](https://www.drupal.org/project/rules). Perhaps we should focus on getting a prototype out and then fueling rules development with the whole excitement around decoupling.

**Comment by fubhy** [comment]
Is this still active? Again, I think it's the wrong place to discuss this as it would affect the spec, not our module alone. So we should probably move it to the graphql spec repo instead? If people are still interested that is?
