### ISSUE TITLE
Add support for file uploads in mutations

### ISSUE THREAD

**Issue by justinlevi** [drupal-graphql/graphql#458]
I have custom module (WIP Branch) here: https://github.com/justinlevi/graphql_custom_file_upload/tree/feature/file_upload_WIP

I have a custom react app here that posts an image to the endpoint. 
https://github.com/justinlevi/graphql_custom_file_upload_mutation_react

I am trying to leverage some of the code posted @ivanjaros here: 
https://gist.github.com/ivanjaros/34bc0c628b7243c71310d57bffeeaced

Specifically the FileUpload Scalar Type
`class FileUpload extends GraphQLString implements ContainerFactoryPluginInterface`

I can verify that the $_FILES array gets to the graphql RequestController->handleRequest function. 

However, the super strange thing I'm seeing is that if I pass the File field as a String, the $query and $variables are NOT null but as soon as I pass the actual file object, both of those variables are null???

In the screen grab video below I first send the mutation field as a String. I then go back and actually send the File. 
![screenflow](https://user-images.githubusercontent.com/1117989/34446862-b64b2e34-ecac-11e7-885f-5e11b82d90ff.gif)

My thought is that Scalar `FileUpload` type is somehow not correct?

I don't want to post too much code here, but happy to if there is anything specific that would help diagnose the issue. I feel like I'm close with this, but just can't figure out why I'm getting the `Error: GraphQL error: Must provide an operation.` whenever I post a file versus a String.

**Comment by justinlevi** [comment]
What should the request look like when POSTing a file? If I send the file object as a mutation variable then the file object is blank when it shows up on in the Symfony handleRequest. 

I'm was trying to use the `createUploadLink` from the  `apollo-upload-client` but I'm thinking that maybe the signature of the request that gets generated is not appropriate for how the graphql module processes things. 

I don't know what that request should look like though.

The medium post here looks interesting, but I'm unsure if the request would be correct here either?

```
export function createNetworkInterface(url) {
    return {
        query(request) {
            const formData  = new FormData();
            
            // search for File objects on the request and set it as formData
            for(let { node, path } of new RecursiveIterator(request.variables)) {
                if (node instanceof File) {
                    const id = Math.random().toString(36);
                    formData.append(id, node);
                    objectPath.set(request.variables, path.join('.'), id);
                }
            }

            formData.append('query', printGraphQL(request.query));
            formData.append('variables', JSON.stringify(request.variables || {}));
            formData.append('debugName', JSON.stringify(request.debugName || ''));
            formData.append('operationName', JSON.stringify(request.operationName || ''));

            return fetch(url, {
                headers: { Accept: '*/*' },
                body: formData,
                method: 'POST',
            }).then(result => result.json());
        }
    }
}
```
https://medium.com/@danielbuechele/file-uploads-with-graphql-and-apollo-5502bbf3941e

**Comment by justinlevi** [comment]
I was able to identify one client-side issue. The operation and variables were parsed and processed fine as  long as there wasn't a file object being sent. This let me to look at the JS code that was creating the request. 

```
if (files.length) {
  fetchOptions.body = new FormData()
  fetchOptions.body.append('operations', JSON.stringify(requestOperation))
  fetchOptions.body.append(
    'map',
    JSON.stringify(
      files.reduce(function(map, _ref3, index) {
        var path = _ref3.path
        map[''.concat(index)] = [path]
        return map
      }, {})
    )
  )
  files.forEach(function(_ref4, index) {
    var file = _ref4.file
    return fetchOptions.body.append(index, file)
  })
} else {
  fetchOptions.headers['content-type'] = 'application/json'
  fetchOptions.body = JSON.stringify(requestOperation)
}
```

So it seems that the FormData object is not being parsed in the Youshido library. If the query is directly added as a string to the body, then everything works as expected. As soon as you add the body to a FormData object, the parameters and query are not found. 

I'm assuming this has something to do with the parser... investigating this next.

**Comment by sebas5384** [comment]
@justinlevi here's another pice to the puzzle:
https://github.com/TallerWebSolutions/graphql_upload

It's working well for now (in prod), hopefully we could join forces :)

oh! and we are using it with Apollo 2.0 and [Apollo Upload Client js module](https://github.com/jaydenseric/apollo-upload-client).

cheers!

**Comment by fubhy** [comment]
Yes, this should follow https://github.com/jaydenseric/graphql-multipart-request-spec and it should be solved using the QueryRouteEnhancer. We should probably teach the `extractParams` method to also deal with multipart/form-data requests. I think we should be able to solve this by only touching that method. Nothing else.

**Comment by justinlevi** [comment]
@sebas5384 @fubhy So I'm seeing the same issue I was seeing yesterday with my own module - The request files object is invalid by the time it reaches `extractParams`. 

Also @sebas5384, the `GraphqlUploadQueryRouteEnhancer` -> filterRequestValues method never seems to get called. 

I'd like to see the difference in how you were posting the file object using the apollo upload client vs how I am. 

I'm wondering if this has something to do with the multipart/form-data? I have a stack exchange post here with some additional details. I'll also try and do a screen capture video demonstrating the problem further. 

https://drupal.stackexchange.com/questions/253052/custom-file-uploads-seem-impossible-from-a-post-request
  
Perhaps a multpart/form-data issue?

Here's my react implementation: 
https://github.com/justinlevi/graphql_custom_file_upload_mutation_react

**Comment by justinlevi** [comment]
@fubhy I think this screenshot shows the issue pretty clearly. 

* XDebug paused on line 213 `Drupal\graphql\Controller\RequestController::handleRequest`
* Note the watched expressions - specifically that `file_exists($_FILES[0]['tmp_name'])` == false
* If I get the current request stack `$files = $request->files->all();` and look at the FileBag object, I see the same result. 

By the time handleRequest is reached, the temporary file no longer exists. My understanding is that if that temporary file does not exist, I can't save, move, or do anything with the file

This seems like a big problem to implementing multipart/form-data uploads unless I'm missing something (very likely...)

![screen shot 2018-01-04 at 11 06 42 am](https://user-images.githubusercontent.com/1117989/34572579-b6430c8a-f13f-11e7-8df8-ccdff89f53cc.jpg)

Whoa.... I just figured out that symfony is renaming the temp file???!!!
The tmp file in the files array starts as: `/private/var/tmp/php5LGklG`
By the time is reaches `handleRequest`, the tmp file has been renamed to: 
`symfony5a4e551619af73.65717941BYwCkd `

WTF???!!!

I found the symfony code that is making this change after digging in more: 


`Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory`

```
  /**
     * Creates Symfony UploadedFile instance from PSR-7 ones.
     *
     * @param UploadedFileInterface $psrUploadedFile
     *
     * @return UploadedFile
     */
    private function createUploadedFile(UploadedFileInterface $psrUploadedFile)
    {
        $temporaryPath = '';
        $clientFileName = '';
        if (UPLOAD_ERR_NO_FILE !== $psrUploadedFile->getError()) {
            $temporaryPath = $this->getTemporaryPath();
            $psrUploadedFile->moveTo($temporaryPath);

            $clientFileName = $psrUploadedFile->getClientFilename();
        }

        return new UploadedFile(
            $temporaryPath,
            null === $clientFileName ? '' : $clientFileName,
            $psrUploadedFile->getClientMediaType(),
            $psrUploadedFile->getSize(),
            $psrUploadedFile->getError(),
            true
        );
    }

    /**
     * Gets a temporary file path.
     *
     * @return string
     */
    protected function getTemporaryPath()
    {
        return tempnam(sys_get_temp_dir(), uniqid('symfony', true));
    }
```

I'm confused why this new request would not be available in resolve???

**Comment by justinlevi** [comment]
OK, I think I found where the problem stems from. 

The `SimpleOauthAuthenticationProvider` calls `validateAuthenticatedRequest($request)` which creates a new psr7 request. During this process, the files are moved and the new request does not include the updated request files object. 

I think this must be a bug with oauth
 
See the screenshot below. The `$request` variable is created and the tokens are reset. As a result of the new request, the temporary files are moved and renamed. The screenshot shows the new spl filepaths but this request dies in this method and the files do not get updated on the original request object. 

![screen shot 2018-01-04 at 12 47 40 pm](https://user-images.githubusercontent.com/1117989/34577028-e2d428d4-f14d-11e7-92cc-c9de207a04c0.jpg)

**Comment by justinlevi** [comment]
FYI - I created a drupal core issue here as I think this is a major blocker to getting file uploads to work correctly. @sebas5384 - I have no idea how that module was working for you unless you were using a different authentication method. 

https://www.drupal.org/project/drupal/issues/2934486#comment-12407588

**Comment by ghost** [comment]
I also haven't had upload issues(with my code). But I think it is due to the fact that I have used rest client and not apollo.

**Comment by sebas5384** [comment]
@justinlevi we are using cookie auth for now and not using Contenta anymore, just a clean D8 install.

**Comment by justinlevi** [comment]
Ahhh, that would explain why you weren’t running into the same issue that I
was with the $_FILES object.

Cookie auth won't work for my use case unfortunately.

I have a super "hacky" workaround for the time being. Hoping to get some
tests in place this week

**Comment by wimleers** [comment]
This was mentioned on the weekly API-First Initiative call a few hours ago.

We've been working on this in core's `rest` module for about a year. All blockers are now resolved. We're down to the final reviews: https://www.drupal.org/project/drupal/issues/1927648. It supports uploads of any size (i.e. also larger than the PHP memory limit), and creates a `File` entity.

At minimum, the GraphQL module should be able to learn from some of that, and ideally would test the same edge cases.

Ideally, in the future, `graphql` and `rest would both reuse the same logic. But for that, we need GraphQL to first figure out how this is supposed to work. So for now, I'd encourage to copy/paste from that core patch, and then in https://www.drupal.org/project/drupal/issues/2940383 we can start working on sharing that code.

**Comment by fubhy** [comment]
We have got a working implementation for that here now: https://github.com/drupal-graphql/graphql/pull/503 

Waiting to be merged!
