### ISSUE TITLE
Image styles with numeric ID cause fatal error in GraphiQL

### ISSUE THREAD

**Issue by davidwhthomas** [drupal-graphql/graphql#461]
Hi there,

Firstly thanks for the excellent work on the GraphQL support for Drupal 8, great stuff.

I've got a question regarding image style names and support.

We use "width x height" image style names such as `400x255`

However, such image style names currently cause a fatal error in the GraphiQL utility:

```
Uncaught Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "400x225" does not.
```

It appears this comes from details returned in the following function

```
class ImageStyleId extends EnumPluginBase {

  public function buildValues(PluggableSchemaBuilderInterface $schemaBuilder) {
    $items = [];
    foreach (ImageStyleConfig::loadMultiple() as $imageStyle) {
      $items[$imageStyle->id()] = [
        'value' => $imageStyle->id(),
        'name' => $imageStyle->id(),
        'description' => $imageStyle->label()
      ];
    }
    return $items;
  }

}
```

Perhaps it could be updated to add a string prefix for such cases? 

e.g: check with the regex `/^[_a-zA-Z][_a-zA-Z0-9]*$/` if not match, add `style_` prefix?

Not sure if updated there, it may also need updating elsewhere, good to check from your perspective.

Thoughts appreciated, thanks.

**Comment by fubhy** [comment]
I've seen that error before. Back then I remember I was wondering whether it is actually a requirement of the GraphQL specification or if it is just something someone overly ambitious built into the graphiql code for no good reason. I don't have time to check right now but just prefixing it with something seems like a good solution. We might run into this problem in other places too and we previously did actually. For that reason, we added string helper utilities to format the names of our plugins by stripping out invalid prefixes. Obviously that would lead to all styles being called "x123" in your case (e.g. 400x400 would become x400). Not good. So maybe we need to change that logic and instead just prefix everything with a static string if there are dynamic / configured values involved that may potentially violate these strict rules from the graphql spec / graphiql.

**Comment by yvmarques** [comment]
We run into the same problem and it seems it's GraphQL spec.

http://facebook.github.io/graphql/October2016/#Name

~~I am quite new to GraphQL, but maybe for this case we could rely on the field aliases for those kinds of  naming ?~~

**Edit** After reading it more attentively, aliases won't work as they need to obey the same naming rules as the fields

**Comment by davidwhthomas** [comment]
I was thinking I could alter the ENUM value now using

```
/**
 * Implements hook_graphql_enum_alter().
 */
function MODULE_graphql_enums_alter(&$definitions) {
  dpm(func_get_args());
}
```

However, curiously while other ENUM definitions have the `values` key set, for the `image_style_id` the `values` array is empty?

<img width="590" alt="screen shot 2018-04-24 at 10 03 08 am" src="https://user-images.githubusercontent.com/1858243/39160525-baa617d2-47a6-11e8-8c91-97c1b7be24f5.png">

This is the case even without any numeric `300x300` type image styles defined.

Is it possible to alter the `image_style_id` values in the ENUM definition there?

**Comment by davidwhthomas** [comment]
Just updating with a solution that worked for us, using numeric based image style names such as 300x300.

The approach was to override the `Drupal\graphql_core\Plugin\GraphQL\Enums\Images\ImageStyleId` plugin with a custom version.

Basically, an extension of the source class with an adjusted `buildEnumValues` function

A useful feature is, using the "weight" key in the annotation, we can override the default handler.

Here's the class file

_web/modules/custom/my_module/src/Plugin/GraphQL/Enums/NumericImageStyleId.php_

```
<?php

namespace Drupal\my_module\Plugin\GraphQL\Enums;

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\graphql\Plugin\GraphQL\Enums\EnumPluginBase;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\graphql_core\Plugin\GraphQL\Enums\Images\ImageStyleId;

/**
 * @GraphQLEnum(
 *   id = "image_style_id",
 *   name = "ImageStyleId",
 *   provider = "image",
 *   weight = 10
 * )
 */
class NumericImageStyleId extends ImageStyleId {

  /**
   * {@inheritdoc}
   */
  public function buildEnumValues($definition) {
    $items = [];

    $storage = $this->entityTypeManager->getStorage('image_style');
    foreach ($storage->loadMultiple() as $imageStyle) {
      $id = $imageStyle->id();
      // Add underscore prefix to numeric image styles
      if (is_numeric(substr($id, 0, 1))) {
        $id = '_' . $id;
      }
      // Add enum value
      $items[strtoupper($id)] = [
        'value' => $imageStyle->id(),
        'description' => $imageStyle->label(),
      ];
    }

    return $items;
  }

}
```

**Comment by fubhy** [comment]
Thanks. Good catch. Fixed in https://github.com/drupal-graphql/graphql/commit/3fdc714885a0f2697c18f2f44ffd3dad966ceb23
