### ISSUE TITLE
Dynamic Entity Reference field causes error in Explorer

### ISSUE THREAD

**Issue by captaindav** [drupal-graphql/graphql#474]
If I add a dynamic entity reference field to a node or other entity type /graphql/explorer crashes.  This is the same issue I reported in: #465 but at that point I thought it was related to the entity type outline_entry. I did not realize that if any entity has a dynamic entity reference field, this would cause explorer to crash.

Here is the error:

The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Drupal\Component\Plugin\Exception\PluginNotFoundException</em>: The &quot;&quot; entity type does not exist. in <em class="placeholder">Drupal\Core\Entity\EntityTypeManager-&gt;getDefinition()</em> (line <em class="placeholder">133</em> of <em class="placeholder">core/lib/Drupal/Core/Entity/EntityTypeManager.php</em>). <pre class="backtrace">Drupal\graphql_core\TypeMapper-&gt;typedDataToGraphQLFieldType(Object) (Line: 36)
Drupal\graphql_core\Plugin\Deriver\Fields\EntityFieldItemDeriver-&gt;getDerivativeDefinitionsFromFieldDefinition(&#039;node&#039;, Object, Array) (Line: 106)
Drupal\graphql_core\Plugin\Deriver\EntityFieldDeriverBase-&gt;getDerivativeDefinitions(Array) (Line: 101)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator-&gt;getDerivatives(Array) (Line: 87)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator-&gt;getDefinitions() (Line: 283)
Drupal\Core\Plugin\DefaultPluginManager-&gt;findDefinitions() (Line: 174)
Drupal\Core\Plugin\DefaultPluginManager-&gt;getDefinitions() (Line: 81)
Drupal\graphql\Plugin\GraphQL\PluggableSchemaBuilder-&gt;find(Object, Array) (Line: 121)
Drupal\graphql\Plugin\GraphQL\Schemas\SchemaPluginBase-&gt;getRootFields() (Line: 72)
Drupal\graphql\Plugin\GraphQL\Schemas\SchemaPluginBase-&gt;getSchema() (Line: 139)
Drupal\graphql\GraphQL\Schema\SchemaLoader-&gt;getSchema(&#039;default&#039;) (Line: 86)
Drupal\graphql\GraphQL\Execution\QueryProcessor-&gt;processQuery(&#039;default&#039;, &#039;    query IntrospectionQuery {
      __schema {
        queryType { name }
        mutationType { name }
        subscriptionType { name }
        types {
          ...FullType
        }
        directives {
          name
          description
          locations
          args {
            ...InputValue
          }
        }
      }
    }

    fragment FullType on __Type {
      kind
      name
      description
      fields(includeDeprecated: true) {
        name
        description
        args {
          ...InputValue
        }
        type {
          ...TypeRef
        }
        isDeprecated
        deprecationReason
      }
      inputFields {
        ...InputValue
      }
      interfaces {
        ...TypeRef
      }
      enumValues(includeDeprecated: true) {
        name
        description
        isDeprecated
        deprecationReason
      }
      possibleTypes {
        ...TypeRef
      }
    }

    fragment InputValue on __InputValue {
      name
      description
      type { ...TypeRef }
      defaultValue
    }

    fragment TypeRef on __Type {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                  ofType {
                    kind
                    name
                  }
                }
              }
            }
          }
        }
      }
    }&#039;) (Line: 131)
Drupal\graphql\GraphQL\Utility\Introspection-&gt;introspect(&#039;default&#039;) (Line: 77)
Drupal\graphql\Controller\ExplorerController-&gt;viewExplorer(&#039;default&#039;)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;Drupal\Core\EventSubscriber\{closure}() (Line: 576)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array) (Line: 153)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 67)
Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 38)
Drupal\jsonapi\StackMiddleware\FormatSetter-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 657)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>

**Comment by fubhy** [comment]
Hi @captaindav. Good catch, thanks. This should fix it: #476 

Can you give that pull request a shot and see if that fixes your problem?

**Comment by captaindav** [comment]
Hi @fubhy.  I tried the PR code but get a different error, I put the error as comment in the PR.  I can try debugging this myself, or perhaps you already know what is going on from the error.   If you were to install the outline module you could get the error that way.

**Comment by fubhy** [comment]
Tested with the outline module. Works! Your new error is not rrelated to this pull request but the update to the youshido/graphjql library we had to do with beta3. In order to test this you now need to run "composer require drupal/graphql:3.x-dev" freshly because it jneeds to instasll youshido/graphql:1.5.3

**Comment by captaindav** [comment]
Confirming it works, thanks!
