### ISSUE TITLE
Incompatibility with the dynamic_page_cache module

### ISSUE THREAD

**Issue by sebas5384** [drupal-graphql/graphql#482]
There are some modules like `acquia_purge` which has `dynamic_page_cache` module as a hard dependency, and there's going to be cases when you could needed both installed, `graphql` and `dynamic_page_cache` module.

I know I did talked about this with @fubhy but I didn't got a time to figure it out how to avoid the `dynamic_page_cache` to intercept GET request to the GraphQL entry point.

I would consider this as a potential stable blocker.

**Comment by fubhy** [comment]
Fixed in https://github.com/drupal-graphql/graphql/pull/483

**Comment by rafatwork** [comment]
@sebas5384 , @fubhy 
Could one of you be so kind as to elaborate little more on why the graphql module is incompatible with the dynamic_page_cache module?

I've tried looking for information regarding this in the issue queue/commit logs, but to no avail.
