### ISSUE TITLE
[Question] Will field settings be exposed as part of config entities?

### ISSUE THREAD

**Issue by skp3zl** [drupal-graphql/graphql#486]
In response to #64 @fubhy 

I'm wondering if Drupal field settings (type, is required, etc.) will be exposed as part of #477 

I'd like to create forms on my frontend using custom components per Drupal field type e.g. dropdown for lists. I can check the field object type using the __type query right now (beta3) but that method is somewhat limited compared to all the information available in Drupal.

Thanks

**Comment by fubhy** [comment]
All of the config properties on all config entities will be exposed!
