### ISSUE TITLE
Document static schema & response cache metadata in results

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#500]
Cache information from the schema is merged with the cache metadata of every result. This means that for example the result of every request will contain the `entity_bundle`, `entity_type` and `entity_field_info` cache tags as long as `graphql_core` is enabled, because the schema is derived from entity types.

There are no immediate plans to resolve this, since pre-parsing the query to calculate the correct cache tags would create more overhead than this tradeoff.
This issue is there to document the circumstances.

**Comment by fubhy** [comment]
@pmelab I can fix this!!!

**Comment by fubhy** [comment]
I mean "write the code that fixes this" (not document this, I don't do documentation, pft)
