### ISSUE TITLE
Incompatibility with Commerce 2.x

### ISSUE THREAD

**Issue by abushak** [drupal-graphql/graphql#502]
console shows 
Error: FieldCommerceLogParams fields must be an object with field names as keys or a function which returns such an object.  in bundle.min.js:1:192663
![graphql_commerce2](https://user-images.githubusercontent.com/3105505/36002040-550226be-0d31-11e8-880d-6ca02b719af6.jpg)

my environment:
drupal8.4.5
7.1.11-1+ubuntu14.04.1+deb.sury.org+1
nginx/1.12.1

after downgrade to version 2.x  all goes normal

**Comment by fubhy** [comment]
Hi! Version 2.x is not supported and barely functional. Please don't use it. The error means, that the commerce log params field does not expose any properties. Interesting.

**Comment by abushak** [comment]
Hello! yeah i see..thank you for a great work!
i just start trying with a few queries just for test how it could work with commerce entities.. 
it would be cool to have it fully working.. Unfortunately im not programmer so can't help..

Also after i've uninstalled Commerce Log same error results with this:
_"Error: FieldCommerceOrderData fields must be an object with field names as keys or a function which returns such an object in bundle.min.js:1:192663"_

P.S> can't find a link to make a donation

**Comment by fubhy** [comment]
I will install a Commerce project tomorrow and see what I can do. Thanks for reporting!

We currently do not have a donation bucket set up anywhere.

**Comment by xuxucode** [comment]
It was caused by **map** field type, I just disable it, see my gist https://gist.github.com/edwardaa/4c8acc1d02a8f471ce66421ba3d1daaa

**Comment by fubhy** [comment]
@edwardaa Thanks for checking. Yes, what you discovered is the cause of the issue but the fix should be this: https://github.com/drupal-graphql/graphql/pull/504/files#diff-5006144f74464460741e724e7436b575R19

We previously only checked if the field has 1 or more properties but forgot to check if it has 0 (which is the case for map fields).
