### ISSUE TITLE
graphql_mutation doesn't seem compatible with graphql:8.x-3.0-beta5

### ISSUE THREAD

**Issue by rawxx** [drupal-graphql/graphql#523]
After updating graphql module to beta5, I get the following error :

`PHP Fatal error:  Declaration of Drupal\\graphql_mutation\\Plugin\\GraphQL\\Mutations\\EntityMutationInputTrait::extractEntityInput(array $inputArgs, Drupal\\graphql\\GraphQL\\Type\\InputObjectType $inputType, Youshido\\GraphQL\\Execution\\ResolveInfo $info) must be compatible with Drupal\\graphql_core\\Plugin\\GraphQL\\Mutations\\Entity\\CreateEntityBase::extractEntityInput(array $args, Youshido\\GraphQL\\Execution\\ResolveInfo $info) in <drupal-dir>/web/modules/contrib/graphql_mutation/src/Plugin/GraphQL/Mutations/CreateEntity.php on line 19`

I use the latest graphql_mutation module, directly from github, if I remember well the same error occurs when installing drupal/graphql_mutation:8.x-1.x-dev from composer.

Is it too early to use mutations with graphql beta5 ? In this case what is the latest beta version of graphql compatible with mutations ?

**Comment by fubhy** [comment]
Hi @rawxx!

Please read https://www.amazeelabs.com/en/blog/extending-graphql-part-3-mutations to learn why we don't expose mutations automatically. The graphql_mutations module will be updated to work with the beta5 and also RC1 and the stable release once its out, HOWEVER, we do NOT recommend to use it. Instead, you should write your own mutations manually as detailed in the blog post that I linked.

That is, until we have time to work on a User Interface for configuring schemas with enough flexibility to be able to compose reasonable mutations.

**Comment by fubhy** [comment]
https://github.com/drupal-graphql/graphql-mutation/pull/6

**Comment by rawxx** [comment]
Hi @fubhy!
Just saw this morning that you actually did it, graphql_mutation is now compatible with graphql. Thank you so much, and thanks for this amazing work you are doing here!
