### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by joaogarin** [drupal-graphql/graphql#526]
Lets start here a discussion around a structure for the documentation site. the idea is to define some sort of folder / documentation structure and we can then even chat in slack so that diff people (if multiple want to contribute) can do on different parts.

Something along the lines of : 

Introduction
Queries 
Mutations
Fields

**Comment by joaogarin** [comment]
I feel like it would be good for the initial part of the docs to focus on getting people quick and easy starting making queries to drupal (especially to nodes). Thats something people can immediately get hooked on and progressively move to more complex stuff.

So I guess my initial approach would be : 

Instructions
- Installation
- Getting started

Queries 
- Querying nodes
- Querying taxonomies

Filters 
- Using filters in queries
- Using entity reference fields

Mutations 
- Creating custom mutation plugins (Article)

I think I normally like when documentation goes very specific..like "thats it. Thats exactly what I want I want to query a list of nodes, I want to filter nodes by entity references etc.." so the names on the folders (topics) needs to be very descriptive.

**Comment by justinlevi** [comment]
This is a good start. I think some overarching ideas we should take into account: 

- Documentation should strive to be written for someone who doesn't know anything. 
We obviously can't teach someone how to code php or install Drupal, but we shouldn't assume a user knows much more than how to install a Drupal module. Reducing the barrier to entry to an absolute beginner, as much as possible. 

- I keep thinking we need a massive list of example queries

- Screencasts are useful, but hard to keep up to date. Maybe after RC

**Comment by joaogarin** [comment]
Definitely I think written queries is such a useful thing, you can copy paste and you are good to start tuning yourself so I love that idea of the huge list of queries.

**Comment by justinlevi** [comment]
Getting Started Outline: 

1. Overview/Introduction : Very high level paragraph describing what the module is and what you can do with it. 
2. Who the module is designed for
3. Super simple example of making a query (I picked the userContact query)
4. Some additional notes

Nothing special, but put a first draft here: 
https://github.com/justinlevi/graphql/blob/311f39afbd4aac718c303d2417681b050784292b/doc/getting-started/readme.md

**Comment by fgm** [comment]
FWIW, the old Gitbook doc is on https://github.com/FGM/graphql-drupal/tree/27-doc_query : I have no problems giving you the reins to the gitbook account if you take over documentation, as I haven't touched it in a long time.

**Comment by fubhy** [comment]
Awesome. Thanks soooo much :)

**Comment by tim-soft** [comment]
I may be a tad biased, but I really like the layout of the [Apollo docs](https://www.apollographql.com/docs/graphql-tools/). Just at a glance I think a section dedicated to actually writing the schema would be really helpful. 

I used this library a super long time ago when it was a little more fringe, but these were big questions to me at the time:

- **Authoring Schema** How do you actually write the schema? -- don't assume in-depth Drupal knowledge
- **3rd Party Libraries** Can you use other libraries such as graphql-tools for writing the schema? 
- **Best Practices** How would you recommend keeping things organized as your schema grows(really big)?
- **Middleware** Authentication/Authorization suggestions?
- **Introspection** How do I access all of my drupal stuff? Will my models already exist in the schema from the get-go?

Examples:

- **Custom Scalars** Illustrate custom scalar usage such as JSON or DATE. 
- **Schema** Defining and using definition, input and enum types
- **Resolvers** Error Handling, Async Drupal API usage, DataLoader-esque practices?

Things that aren't in here(yet?) 

- **Subscriptions?** 
- **File Uploads?** by slipping data into the multi-part section of the request?
- **Schema Stitching** what if I want to combine this drupal schema with an external graphql-tools based schema?

**Comment by joaogarin** [comment]
Yeah I totally agree that the Apollo docs are a super helpful example of documentation done right. that being said the use cases you mention here seem pretty advanced to me..I particularly love in apollo how they make it super simple at first, making the entry easy and not overwhelm you with very complex scenarios right out of the bat.

So Its normal that we try addressing simpler use cases first and have a dedicated section for more advanced stuff, at least to me this seems like a way to more easily bring new people into the module. 

You start by learning what graphql is, how to write some simpler queries, mutations and move progressively to more advanced things like custom schemas or custom field plugins etc

**Comment by fubhy** [comment]
That branch looks really good now already. I am going to start helping next week once we got the next beta out with webonyx as a foundation (we finally merged that). So it's time to prepare for RC (including docs).

**Comment by justinlevi** [comment]
I think we need to create some documentation on authentication. I realize it's orthogonal to the module but I think it would reduce the barrier to entry if we can put together a guide on the different options.

We have a placeholder there now - I'll try to work on this today.

**Comment by joaogarin** [comment]
Yeah I totally agree I can also put something together or at least see if what you write matches my experience..also I think would be nice to make the documentation public via gitbook so there is an easier url for docs then browsing the repo itself.
