### ISSUE TITLE
Handle language in route() and entityById() root fields.

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#53]
The route() field should handle the language based on the incoming path prefix (e.g. en/node/1). The entityById() derived field should handle it through an additional argument with an ENUM for the available languages.

**Comment by fubhy** [comment]
@blazeyo This could also be another issue for you to work on. Or maybe @Xilis?

**Comment by blazeyo** [comment]
@fubhy I'm happy to take this one.

**Comment by fubhy** [comment]
Assign it to you if you feel like working on it :). First come first serve!

**Comment by blazeyo** [comment]
Looks like only admins can do that.
