### ISSUE TITLE
Add cache tags for schema cache invalidation.

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#54]
We can now use cache tags on the fields and types that make up the schema to automatically invalidate it when something changes.

**Comment by fubhy** [comment]
Done.

**Comment by basvdheijden** [comment]
How do we do this? I'm noticing too aggressive caching on my GQL queries. If my node changes, the query is still cached. Any idea how I can set cache tags on my custom field?

**Comment by jesconstantine** [comment]
@basvdheijden I'm experiencing the same thing. Were you able to determine a fix for this?

**Comment by ryandorward** [comment]
> We can now use cache tags on the fields and types that make up the schema to automatically invalidate it when something changes.

Would love to see any hints or documentation on how to do this.
