### ISSUE TITLE
How to access group content fields in a group

### ISSUE THREAD

**Issue by johnreytanquinco** [drupal-graphql/graphql#542]
I have a custom content type enabled/installed as plugin in my group. How can I get these fields inside the group query?

Say, **Content X** has the following fields:
- Title
- Body
- Version

```
{
  groupById(id: "1", language: en) {
    ... on GroupBusinessGroup {
    }
  }
}
```
I can be able to access it outside the groupById using nodeById.
```
  nodeById(id: "10", language: en) {
    ... on NodeContentX {
    }
  }
```

**Comment by johnreytanquinco** [comment]
I tried this query
```
{
  groupById(id: "1", language: en) {
    ... on GroupBusinessGroup {
      reverseGidGroupContent {
        entities {
          ... on NodeContentX {
            fieldTitle
            fieldBody
            fieldVersion
          }
        }
      }
    }
  }
}

```
RESULT
```
{
  "data": {
    "groupById": {
      "reverseGidGroupContent": {
        "entities": [
          [],
          [],
          [],
          []
        ]
      }
    }
  }
}

```

**Comment by fubhy** [comment]
Can you add the __typename field to your reverseGid field and see what entity type it returns?
```gql
{
  groupById(id: "1", language: en) {
    ... on GroupBusinessGroup {
      reverseGidGroupContent {
        entities {
          __typename
          ... on NodeContentX {
            fieldTitle
            fieldBody
            fieldVersion
          }
        }
      }
    }
  }
}
```

**Comment by johnreytanquinco** [comment]
```
Result
{
  "data": {
    "groupById": {
      "reverseGidGroupContent": {
        "entities": [
          {
            "__typename": "GroupContentBusinessGroupGroupMembership"
          },
          {
            "__typename": "GroupContentGroupContentType00d787f27f3b6"
          },
          {
            "__typename": "GroupContentBusinessGroupGroupNodeContentX"
          },
          {
            "__typename": "GroupContentGroupContentType00d787f27f3b6"
          }
        ]
      }
    }
  }
}
```

**Comment by johnreytanquinco** [comment]
The call `... on NodeContentX {` doesn't seems to have values.

But when I add 
`entityLabel` just below `__typename`
```
{
  "data": {
    "groupById": {
      "reverseGidGroupContent": {
        "entities": [
          {
            "__typename": "GroupContentBusinessGroupGroupMembership",
            "entityLabel": "admin"
          },
          {
            "__typename": "GroupContentGroupContentType00d787f27f3b6",
            "entityLabel": "TP 1"
          },
          {
            "__typename": "GroupContentBusinessGroupGroupNodeContentX",
            "entityLabel": "S 1"
          },
          {
            "__typename": "GroupContentGroupContentType00d787f27f3b6",
            "entityLabel": "TP 2"
          }
        ]
      }
    }
  }
}
```

**Comment by fubhy** [comment]
Well and that makes perfect sense if you think about it! When you added __typename, you revealed that the return type of the entities in the "reverse entity reference entity query" for the "group content" field is NOT a always a NodeContentX. In fact, it NEVER is a NodeContentX because the "group content' field references GROUP CONTENT entities. These can be of ANY other content entity type in your system (e.g. as you can see there is a group membership entity in there which references your user (admin).

This is simply how the group module works! Nested WITHIN the group content entity should be a reference to the actual Node, User, etc. entity. This is what you are looking for. However, what you also want is to filter by the entity type and bundle of the target entity for your group content so you can only show NodeContentX entities.

This is possible if you are on the latest dev release (8.x-3.x-dev) of this module: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityReference/EntityReferenceReverse.php

As you can see, that's where I added the ability to also add entity query filtering to reverse entity reference fields. So now you could run a query like:

```gql
{
  groupContentQuery(filter: {
    conditions: {
      field: "type.target_id"
      value: ["{group machine name}-group_node-{content type machine name}"]
    }
  }) {
    entities {      
      ... on GroupContent {
        entityId {
          entity {
            ... on NodeContentX {
              title
              nid
            }
          }
        }
      }
    }
  }
}
```

Make sure to replace ``{group machine name}`` and ``{content type machine name}`` according to your setup. (e.g. if your group was named "my_fancy_group" and your content type "content_x":

```
{
  groupContentQuery(filter: {
    conditions: {
      field: "type.target_id"
      value: ["my_fancy_group-group_node-content_x"]
    }
  }) {
    entities {      
      ... on GroupContent {
        entityId {
          entity {
            ... on NodeContentX {
              title
              nid
            }
          }
        }
      }
    }
  }
}
```

**Comment by fubhy** [comment]
Based on the query that you supplied, this should work for you (after upgrading to 8.x-3.x-dev).

You might see an error for the "entityId" field (or graphiql becoming unusable and an error showing up in your browser console). This might be related to a naming clash between our 'entityId" field and the entity_id base field from the group content module. We will fix that with the next release. It might work for you anyways :).

```gql
{
  groupById(id: "1", language: en) {
    ... on Group {
      reverseGidGroupContent(filter: {
        conditions: {
          field: "type.target_id"
          value: ["business-group_node-content_x"]
        }
      }) {
        entities {      
          ... on GroupContent {
            entityId {
              entity {
                ... on NodeContentX {
                  title
                  nid
                }
              }
            }
          }
        }
      }
    }
  }  
}
```

**Comment by fubhy** [comment]
By the way... The query I posted here is very complex because this is all automatically generated. If you are capable of writing some Drupal 8 PHP code, then you should consider solving this with a custom Plugin instead so you could write a much simpler query like: 

```gql
{
  groupById(id: "1", language: en) {
    ... on GroupBusiness {
      # This would directly target attached group content of type "node:content_x" in code.
      myCustomField {
        entityId
      }
    }
  }  
}
```

**Comment by johnreytanquinco** [comment]
Thanks for your response and that information.

When I hover `{`(line 12), its says 

> Field `entityId` must not have  a selection since type "String" has no subfields

Group machine name: `business_group`
Content type machine name: `symbol`

This is the result im getting:
![screenshot from 2018-03-07 16-31-10](https://user-images.githubusercontent.com/7284893/37081620-05c491aa-2225-11e8-8253-32c3fd977b94.png)

**Comment by fubhy** [comment]
Yep, that's the "bug" I meant. To explain what's happening: We expose a static "entityId" field on all entities in the Graph. However, the Group Content node also exposes a field named "entity_id" which is translated to "entityId" too, causing this conflict. This means that you cannot, currently without a little "hack", make this work. So you can try this until we have released the next version:

Go to ``graphql/modules/graphql_core/src/Plugin/GraphQL/Fields/Entity/EntityId.php``. Open that file and edit it in the Annotation: Change the "name" field from "entityId" to "__entityId" or something. Now, when you clear the caches, it should present you with an __entityId AND an "entityId" field in the graph for GroupContent. The, entityId field will be the one from the GroupContent entity.

**Comment by johnreytanquinco** [comment]
Okay. Thanks will try that!

**Comment by johnreytanquinco** [comment]
Thanks @fubhy , that works!
This result might help giving you some information for the bug.
```
        "entities": [
          {
            "entityId": null
          },
       ...
       ...
 "errors": [
   {
    "message": "Could not resolve type for interface Node."
  }
 ]
```

**Comment by johnreytanquinco** [comment]
Any update on this? Has there a commit applying this change? Thanks!

**Comment by fenetikm** [comment]
Yep, there was a commit so you can now do `entityIdOfGroupContent` instead of `entityId`

**Comment by fenetikm** [comment]
Note that if your `content_type` is longer than a specified max length, the `target_id` value will be something like `group_content_type_1f2747c1739fd` which you can find by navigating to the group content page in Drupal.

**Comment by carolpettirossi** [comment]
Hi all, 
I was using the `entityIdOfGroupContent` successfully. However, my project requires to have the ability to add taxonomies and menus to a specific group. This requirement leads us to this group issue: https://www.drupal.org/project/group/issues/2797793.
If I apply the patch #130 provided in the issue, the entityIdOfGroupContent becomes unavailable. 
This is the query that I have:
```
{
  route(path: "/group/1/content/70") {
    ... on EntityCanonicalUrl {
      entity {
        entityUrl {
          path
        }
        entityIdOfGroupContent {
          entity {
            ... on NodeArticle {
              title
            }
          }
        }
      }
    }
  }
}
```


I would need to replace the code for:
```
{
  route(path: "/group/1/content/70") {
    ... on EntityCanonicalUrl {
      entity {
        entityUrl {
          path
        }
        ... on GroupContent {
          queryEntityId { 
            entities {
              ... on NodeArticle {
                title
              }
            }
          }
        }
      }
    }
  }
}
```

We have lots of queries already implemented using the `entityIdOfGroupContent`. So it would require a big refactor on our side. 

Can someone explain to me how the `entityIdOfGroupContent` works? Is it necessary to implement some additional code on that Group module patch to have this `entityIdOfGroupContent` working properly?

Thanks,
Carol
