### ISSUE TITLE
EntityCanonicalUrl fragment should check if <front> resolves to an entity

### ISSUE THREAD

**Issue by pavlosdan** [drupal-graphql/graphql#544]
In beta1 one could use nodeContext directly on the route query to return a node given a path. In beta5 graphiql complains about this though and instead tried to use the EntityCanonicalUrl fragment.

In the applies method of the fragment this check happens:
```
if (count($parts) !== 3) {
  return FALSE;
}
```
Which returns false since there is only one part in the route name => "<front>"

The following check also fails on the "<front>" route:
"if (($prefix === 'entity' && $suffix === 'canonical') && array_key_exists($entityType, $parameters)) {"
as $prefix is "<front>" and $suffix is null.

**Comment by fubhy** [comment]
Solved in https://github.com/drupal-graphql/graphql/compare/path-validator?expand=1
