### ISSUE TITLE
Multiple create or update using one mutation

### ISSUE THREAD

**Issue by filozofer** [drupal-graphql/graphql#552]
I'm here to report a limitation on the currently generated GraphQL Mutations.
We have a custom entity "Favorite". The module generate for us a query which allow us to do this mutation:

```
mutation create($favorite: FavoriteFavoriteCreateInput!) {
  
  createFavoriteFavorite(input: $favorite) {
    entity {
      ... on Favorite {
        favProspectId
      }
    }
  }
  
}
```

This is great to create a single favorite entity but what if we want to create / update multiple favorite with one request (mutation) ?
At the moment, it is not possible de pass an "inputs" parameters of type [Favorite] to handle multiple create/update directly.
These attribute does not need to replace the current "input" attribute, it can be a new one allowing to pass an array of inputs. Then the logic about the args is handle in the resolve function in order to retrieve the value in the "input" or in the "inputs" parameters.

In order to achieve our goal, we have to create our own mutation which look like this and do the same thing as above but handle multiple inputs for favorite:

```
mutation create($favorites: [FavoriteFavoriteCreateInput]!) {
  
  createMultipleFavoriteFavorite(inputs: $favorites) {
    entity {
      ... on Favorite {
        favProspectId
      }
    }
  }
  
}
```

Do you think the module can handle this feature case in a future version ?

Thanx you for your time

**Comment by fubhy** [comment]
We are currently wrapping up the 8.x-3.x release. This will not be added to 3.x and we don't plan to add it in a future version of 3.x.

However! This is definitely going to be possible with our NEXT release as we are going to provide the ability to create completely custom schemas using the schema definition language.

Hence, I am closing this issue. TLDR: No, not in 3.x but definitely possible in 4.x which we already started working on.
