### ISSUE TITLE
Breaking typed data changes

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#555]
The update to Drupal 8.5 raised an issue with the optimisation of simple fields. Currently a field with only one property will not generate a dedicated GraphQL type but emit the value directly.

This means you can access simple fields with ... 
```
fragment Article on NodeArticle {
  fieldText
}

```

... instead of ...

```
fragment Article on NodeArticle {
  fieldText {
    value
  }
}
```

This is not just a convenience feature, it also reduces schema complexity significantly.

On the other hand it introduces a breaking change whenever a field changes from *simple* to *complex*, as it just happened with file urls, which are not atomic any more, but got an additional `url` property.

This:
```
fragment Article on NodeArticle {
  fieldFile {
	entity {
  	  uri
	}
  }
}
```

Just changed to:
```
fragment Article on NodeArticle {
  fieldFile {
	entity {
  	  uri {
	    value
	  }
	}
  }
}
```

This may happen basically in any field type, both core and contrib. And it's not considered a breaking change for anybody else, but it is for us. So it won't be possible to maintain a compatibility layer for the whole contrib space. You would have to resolve these changes on project level.

Any opinions?

**Comment by pmelab** [comment]
The issue is apparent in the 8.5 compatibility PR: https://github.com/drupal-graphql/graphql/pull/554

**Comment by doublecompile** [comment]
My project is still using alpha7. Without having to change the queries on the client, I threw together a simple override to restore the behavior present in Drupal 8.4.

```php
use Drupal\file\FileInterface;
use Drupal\graphql\Plugin\GraphQL\Fields\FieldPluginBase;
use Youshido\GraphQL\Execution\ResolveInfo;

/**
 * Entity route field override for files.
 *
 * @GraphQLField(
 *   id = "file_uri",
 *   secure = true,
 *   name = "uri",
 *   type = "String",
 *   types = {"File"},
 *   weight = 1
 * )
 */
class FileUri extends FieldPluginBase {

  /**
   * {@inheritdoc}
   */
  public function resolveValues($value, array $args, ResolveInfo $info) {
    if ($value instanceof FileInterface) {
      yield $value->getFileUri();
    }
  }

}
```

**Comment by pmelab** [comment]
This will be resolved along with implementing configurable schemas: https://github.com/drupal-graphql/graphql-sdl
