### ISSUE TITLE
Relay compatibility?

### ISSUE THREAD

**Issue by johnnybgoode** [drupal-graphql/graphql#559]
I'm wondering about the current state of relay compliance in the 3.x branch? I've looked through some of the other issues here related to relay but there isn't much that seems current on the topic.

I've played around with installing the module on a vanilla Drupal site with some devel_generated content and I'm not able to get `relay-compile` to run successfully with the generated schema that's available. The error I get seems to be related to the GraphQL schema: `Expected undefined to be a GraphQL leaf type.`

Any insight here is very much appreciated. If there's already ongoing work in this area I may be able to help out as well.

**Comment by fubhy** [comment]
I believe I answered your question on slack :)
