### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by naitschi** [drupal-graphql/graphql#565]
Hey Guys,

I got a Problem with the Route Method

I'm trying get get the content of a Route but I always get and Internal Error. 
Do you have any Idea what this could be? 

![unbenannt](https://user-images.githubusercontent.com/12916150/38087492-9a734406-3358-11e8-8462-35f8b119629e.PNG)

The Route is right. I tested it also with other routes. 
I also used every URL interface.

**Comment by fubhy** [comment]
Can you enable "development" mode in your local .services.yml? (Check out graphql.services.yml). After that, you need to run "drush cr". Then, you should see more information in graphiql.

**Comment by naitschi** [comment]
Thanks for the quick answer.

Now I'm getting a debug message with the following:

`Argument 1 passed to Drupal\\language\\LanguageNegotiationMethodBase::setCurrentUser() must implement interface Drupal\\Core\\Session\\AccountInterface, null given, called in /var/www/html/pepe-drupal/core/modules/language/src/LanguageNegotiator.php on line 213`

**Comment by naitschi** [comment]
Its working now. I had to add a second language and choose the Contentypes and Paragraphs I want to be translateable in admin/config/regional/content-language. 

Everythings seem now to work.

**Comment by lucasconstantino** [comment]
Relates to https://github.com/drupal-graphql/graphql/pull/605
