### ISSUE TITLE
Enable Error Logging for GraphQL Queries

### ISSUE THREAD

**Issue by WeirdDNA** [drupal-graphql/graphql#566]
When queries return HTTP 500 errors, generally no log is entered into the drupal logging system (admin/reports/dblog).  Please enable (at least the option) to log GraphQL query errors (and mutation, etc) errors.

**Comment by luksak** [comment]
This would be really useful. Is there a temporary workaround to get the errors?

**Comment by clemens-tolboom** [comment]
Trying to debug I see a development variable in

```php
  // \Drupal\graphql\Controller\RequestController::handleRequest
  public function handleRequest($schema, $operations) {
    $development = !empty($this->parameters['development']);
    $development = true;
    $globals = ['development' => $development];

    if (is_array($operations)) {
      return $this->handleBatch($schema, $operations, $globals);
    }

    return $this->handleSingle($schema, $operations, $globals);
  }
```

Not sure yet how to set it. Anyone?

**Comment by clemens-tolboom** [comment]
Next testing with an invalid filter field __ccreated__ (double c)

```graphql
{
  query: nodeQuery(filter: {conditions: {field: "ccreated", value: "2018-04-22T00:00:00", operator: GREATER_THAN_OR_EQUAL}}) {
    entities {
      entityLabel
      entityType
      entityCreated
    }
  },
}
```
producing
```json
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "query",
        "entities"
      ]
    }
  ],
  "data": {
    "query": {
      "entities": null
    }
  }
}
```

which comes from (in my codeflow)

```php
// \Symfony\Component\HttpFoundation\JsonResponse::setData
...
            } else {
                try {
$error_0 = $data->errors[0];
$data->errors[0] = $error_0->toSerializableArray();
$data->errors = [];
                    $data = json_encode($data, $this->encodingOptions);
                } catch (\Exception $e) {
                    if ('Exception' === get_class($e) && 0 === strpos($e->getMessage(), 'Failed calling ')) {
                        throw $e->getPrevious() ?: $e;
                    }
                    throw $e;
                }
            }
```

It seems like `json_encode()` chokes on the error as removing the error(s) works fine (as in getting a NONE 500).

Not sure what to do next :-(

**Comment by clemens-tolboom** [comment]
![drupal-graphql-error](https://user-images.githubusercontent.com/371014/39419961-86ed88b0-4c62-11e8-8ba3-ae3f14c12bee.png)

**Comment by clemens-tolboom** [comment]
From #slack @pavlosdan I learned setting development in `graphql.services.yml` which does give (does it?) somewhat more info but no log entry

```json
{
  "errors": [
    {
      "debugMessage": "'entityCreated' not found", <======
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "query",
        "entities"
      ]
    }
  ],
  "data": {
    "query": {
      "entities": null
    }
  }
}
```

**Comment by clemens-tolboom** [comment]
Hmmm ... the message comes probably from

```bash
grep --recursive --line-number "' not found" core
...
core/lib/Drupal/Core/Entity/Query/Sql/Tables.php:348:    throw new QueryException("'$property' not found");
```

Drupal does not know the field `entityCreated` but graphql knows it. At least as an output field. Not yet as a filter field.

**Comment by clemens-tolboom** [comment]
I've created a PR #590 which only logs when `development: true` is set in `graphql.services.yml`

**Comment by luksak** [comment]
@clemens-tolboom Great, that helped me solve my error. Thank you!

**Comment by pmelab** [comment]
Thanks @clemens-tolboom !
To merge this, we need to change the approach a little.

1. Errors should be logged on a processor level, since not all requests come from the HTTP endpoint (e.g. [graphql_twig](https://github.com/drupal-graphql/graphql-twig)).
2. IMO errors should also be logged when not in debug mode. If they happen in production, I'm even more interested what happened 😃 
3. Right now when debug mode is off, it will only log "Internal Server Error", which is not helpful.

The GraphQL library already accepts custom error handlers, we just have to use them:
http://webonyx.github.io/graphql-php/error-handling/#custom-error-handling-and-formatting

As far as I can tell they have to be added to the `ServerConfig` object: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/GraphQL/Execution/QueryProcessor.php#L133

Do you have time to look into that? Else I will pick it up at some point in the future 😉

**Comment by clemens-tolboom** [comment]
@pmelab I totally agree which the place and function. But I had no clues. Now I have. Can you please post your comment into the PR #590 ? I'll try to fix it.

**Comment by clemens-tolboom** [comment]
@pmelab I added your https://github.com/drupal-graphql/graphql/issues/566#issuecomment-385648742 to #590 as @fubhy responded there too.

**Comment by fubhy** [comment]
I merged https://github.com/drupal-graphql/graphql/pull/662

I am just wondering whether we should enable that even if development mode is NOT enabled. Because error logging should maybe always happen?

**Comment by clemens-tolboom** [comment]
I'd rather have error log on prod for analysis then no logging at all.

**Comment by fubhy** [comment]
RIght. I think I'd agree. Also it would help us to debug errors in user-space.
