### ISSUE TITLE
ImageDerivative aren't expecting null values

### ISSUE THREAD

**Issue by sebas5384** [drupal-graphql/graphql#572]
When the image is null:
`Error: Call to a member function access() on null in` https://github.com/drupal-graphql/graphql/blob/2132807132a0570977b13435b335f6cc31f01335/modules/graphql_core/src/Plugin/GraphQL/Fields/Entity/Fields/Image/ImageDerivative.php#L71

Should each resolver deal with the fact that it's parent's value is `null`? or should be treated on the parent field type?

A simple `!empty($value->entity)` should do the trick but I'm feeling this is going to explode the `is null` thing.

cheers.

**Comment by fubhy** [comment]
Good catch. Fixed this in https://github.com/drupal-graphql/graphql/commit/a46450a56b7fb5a7ee36b6ded5a5c78ad3704e59
