### ISSUE TITLE
Apply entity query filters to entity reference fields.

### ISSUE THREAD

**Issue by scubafly** [drupal-graphql/graphql#573]
@pmelab wrote: entity query has the “exists” condition, but since this is not an operator, its not supported by filters yet.

For example I want to do something like this:
```
{
  nodeQuery(filter: {fieldX:true}) {
    entities {
      ... on NodeArticle {
        onlyNodesWithFieldx: entityLabel
      }
    }
  }
}
```

**Comment by scubafly** [comment]
It looks like it is posible with the example below

`nodeQuery(filter: {conditions: [{field: "status" value: ["1"]}]}) {`

Not sure if this works for the non basic fields. ( custom created field that are specific for a node of type `x`, `article` in this case )

**Comment by lasseborly** [comment]
@scubafly it does not seem to be :/

```graphql
query ($agentId: String!){
  nodeQuery (
    limit: 500
    filter: {
      conditions:[
        { field: "fieldEwarpClientId", value: [$agentId] }
      ]
    }
  ) {
    entities {
      ...on NodeOfficePage {
      	fieldEwarpClientId
      }
    }
  }
}
```

```graphql
{
  "errors": [
    {
      "debugMessage": "'fieldEwarpClientId' not found",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 10,
          "column": 5
        }
      ],
      "path": [
        "nodeQuery",
        "entities"
      ]
    }
  ],
  "data": {
    "nodeQuery": {
      "entities": null
    }
  }
}
```

**Comment by defr** [comment]
Filtering by simple Drupal fields works, *but* in the condition part of the query, you need to put in the real drupal field name, which isn't exposed anywhere. On your query it'd probably be something like

```graphql
query ($agentId: String!){
  nodeQuery (
    limit: 500
    filter: {
      conditions:[
        { field: "field_ewarp_client_id", value: [$agentId] }
      ]
    }
  ) {
    entities {
      ...on NodeOfficePage {
      	fieldEwarpClientId
      }
    }
  }
}
```

The need to convert from camelCase to snake_case is unfortunate, it's documented in https://github.com/drupal-graphql/graphql/blob/8.x-3.x/doc/queries/filters.md#filtering-for-custom-fields-in-the-entity , but there's no easy way to make those fields discoverable for example in Voyager.

**Comment by lasseborly** [comment]
This seems solved then? :smile: @scubafly ?

**Comment by scubafly** [comment]
Sorry for the late response, I was on holiday.

It is almost solved. Still missing the option to filter on entity reference fields. But I guess that is a new/ another issue. Closing this one. I'll create a new issue for entity reference filters.

**Comment by defr** [comment]
@scubafly The syntax for those filter is based on Drupal 8 Entity Query. You're able to filter on referenced entities / their fields by using "."

For example: {conditions: {field: "field_entityreference.entity.name", value: "Test%", operator: LIKE}} will return records where the field_entityreference fields references an entity whose name field starts with Test

**Comment by scubafly** [comment]
Thanks @defr !
The only Issue I still have is that if I have a multiple entityreference field and I cannot filter to get only the referenced published nodes, or referenced node with id = x.

For example:

`{conditions: {field: "field_entityreference.entity.status", value: "1"}}`

This will return published and depublished referenced nodes.

Or
 
`{conditions: {field: "field_entityreference.entity.nid", value: "16"}}`

Will return values if one of the referenced entities has the nid 16. But will also return other referenced nodes.

**Comment by scubafly** [comment]
![graphiql___aerius_monitor](https://user-images.githubusercontent.com/820268/40919312-742a26f8-6809-11e8-9af2-ca446d66abe0.png)
Added a screenshot for the result example.
The required result should not show the panel with id of 12 that is unpublished in my opinion.

**Comment by scubafly** [comment]
![graphiql___aerius_monitor](https://user-images.githubusercontent.com/820268/40920064-c3b0146a-680b-11e8-9e95-9fabad48aa1f.png)
![graphiql___aerius_monitor](https://user-images.githubusercontent.com/820268/40920079-cb206650-680b-11e8-81d0-a5a5ef59338c.png)
Added some more screenshot with different results. It succesfully hides the results if the panel nid is not in the list of the chapter node. But node 16 still shows up if I set the filter to show only nid 12.

Not sure this is a bug, of if I use the filter wrong.

**Comment by fubhy** [comment]
Your query basically finds all chapter that have ANY panels attached to it (in the references) that is published. You then follow the graph further to list all of the panels for each of the resulting chapter, which then loads ALL the attached chapters. Not just the unpublished ones. You would basically have to run ANOTHER entity query on the fieldPanels level that filters for all published panels within the current chapter. We don't currently have such a field but it would be rather trivial to add an entity query based field plugin with a deriver that  adds it for each entity reference field. We actually do something similar already for the REVERSE entity reference field (https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityReference/EntityReferenceReverse.php)

**Comment by fubhy** [comment]
Summoning @pmelab for his opinion on whether we should add such a field. 

I added a pull request that would add this functionality: https://github.com/drupal-graphql/graphql/pull/660

@scubafly Can you check if this solves the problem for you?

Note that running multiple nested entity queries in arbirtrary lists might have a negative performance impact if you overdo it. (E.g. running an entity reference query field withing a list of 10 within a list of 10 => 10x10x ...)

**Comment by fubhy** [comment]
After applying the code from that pull request you should be able to see a "queryFieldPanels" field in your chapter node.

**Comment by fubhy** [comment]
I just merged this pull request after doing some more testing myself. I think this is a good addition to the module. And just like with all of the other nested query fields you just gotta be careful to not overdo it.

**Comment by scubafly** [comment]
Cool, will do some testing later. Probebly tommorrow.
