### ISSUE TITLE
Handling custom fields with Beta6

### ISSUE THREAD

**Issue by bogue** [drupal-graphql/graphql#574]
Getting the following error message trying to port a previously functional custom field to Beta6: `Expected value of type "Question" but got: associative array(1) with first keys: "label"` (note: graphiql autocompletes the label field just fine when building the query). I originally had the following:
```
/**
 * A simple field that generates a list of questions
 *
 * @GraphQLField(
 *   id = "GTest",
 *   secure = true,
 *   type = "[Question]",
 *   name = "GTest",
 *   nullable = true,
 *   multi = false,
 *   arguments = {
 *      "whatever" = "String"
 *   }
 * )
 */
class GTest extends FieldPluginBase {
  /**
   * {@inheritdoc}
   */
  protected function resolveValues($value, array $args, ResolveContext $context, ResolveInfo $info) {
    // this returns a flat associative array from an external source (read: non-Drupal)
    $data = \Drupal::service('custom.service')->getExternalData();
    foreach($data as $q){
      yield $q;
    }
  }
}
```
This is the Question class, pretty standard stuff i believe:
```
/**
 * A Question type.
 *
 * @GraphQLType(
 *   id = "Question",
 *   name = "Question",
 * )
 */
class Question extends TypePluginBase {

  /**
   * {@inheritdoc}
   */
  public function applies($value, ResolveContext $context, ResolveInfo $info = NULL) {
    return $value['type'] == 'Question';
  }
}
```
To which a basic string field is attached:
```

/**
 * A question label.
 *
 * @GraphQLField(
 *   id = "Label",
 *   secure = true,
 *   name = "label",
 *   type = "String",
 *   parents = {"Question"}
 * )
 */
class Label extends FieldPluginBase {

  /**
   * {@inheritdoc}
   */
  public function resolveValues($value, array $args, ResolveContext $context, ResolveInfo $info) {
    yield $value['label'];
  }
}
```
As the error message suggests, i'm guessing GTest needs to yield Question instances as opposed to associative arrays as the way it was originally set up, but i'm wondering what would be the right/Drupal way to handle it. 

Thanks guys!

_Note: i'm not a frequent GitHub user, don't hesitate to let me know if this isn't the appropriate tribune for this type of question._

**Comment by davidwhthomas** [comment]
Hi @bogue 

Just a thought, but have you tried adjusting the annotation so `type` isn't an array?

You might also need to set `multi` to `true` if returning multiple values in the field

i.e
```
/**
 * A simple field that generates a list of questions
 *
 * @GraphQLField(
 *   id = "GTest",
 *   secure = true,
 *   type = "Question",
 *   name = "GTest",
 *   nullable = true,
 *   multi = true,
 *   arguments = {
 *      "whatever" = "String"
 *   }
 * )
 */
```

**Comment by bogue** [comment]
Finally figured it out -- pure luck:  just had to remove the `applies` function on the `Question` class, which i had picked from an example somewhere, and it magically fixed everything *** sigh *** Ah well. Thanks!
