### ISSUE TITLE
Allow for query conditions to be skipped

### ISSUE THREAD

**Issue by pavlosdan** [drupal-graphql/graphql#576]
Usecase: Allow FrontEnds to build listing pages that can be filtered on demand based on filters on the page. 

To achieve the above one would need to write 4 directives to filter on 2 fields (lets say title and category)
e.g:
`query FooQuery($doFilter: Boolean!, $filterValue: String) {
  nodeQuery(foo: $filterValue) @include(if: $doFilter) {
    ...
  }
  
  nodeQuery @skip(if: $doFilter) {
    ...
  }
}`

It would be great if we could allow the FrontEnd to pass a "skip" boolean for the conditions it does not want to filter on so the conditions can be completely skipped.

**Comment by pavlosdan** [comment]
an example of how the above would work: 

`query {
  nodeQuery(
    limit: 1000,
    filter:{
        conditions: [
          {field:"type", value: ["page"], operator: EQUAL, **skip: false**},
          {field:"status", value: ["1"], operator: EQUAL, **skip: true**},
          {field:"sticky", value: ["0"], operator: EQUAL, **skip: true**}
        ]
  }, sort: {
    field: "id",
    direction: "ASC"
  }) {
    count
    entities {
      entityLabel
      entityBundle
    }
  }
}`

**Comment by pavlosdan** [comment]
Had a brief discussion with the team here and it seems "skip" is causing confusion. Debating renaming it to "enable" and the FrontEnd can disable/enable conditions as required. Thoughts?

**Comment by fubhy** [comment]
enabled = true/false with a default of "true" would be fine with me too.

**Comment by pavlosdan** [comment]
Switched 'skip' to 'enabled' and set it to 'true' by default.

**Comment by fubhy** [comment]
Thanks. I reviewed your PR.

**Comment by pavlosdan** [comment]
Updated the PR :)
