### ISSUE TITLE
HTTP Basic auth

### ISSUE THREAD

**Issue by mbajur** [drupal-graphql/graphql#578]
Hello,

just to let you know - i'm not well experienced with drupal nor it's internals so that question might be trivial.

I'm looking for a simplest way to authenticate my drupal-graphql requests without using JWT, Oauth2 or all those "safer" options (i don't need a "safety" like that, consumer application is a backend app not exposed to the world so the simplest solution the better. To be honest - consumer technology is limiting me in terms of choosing a more complex authentication mechanisms and i can't bind there anything more complicated than simple URL prefix (HTTP Basic auth) or some hardcoded headers. 

As far as i can tell, drupal has a built-in http basic auth (https://www.drupal.org/docs/8/core/modules/basic_auth/overview) feature but - is drupal-graphql supporting it? I'm not able to authenticate my requests using username and password prefix in the URL. Endpoint returns 403.

Thanks!

**Comment by fubhy** [comment]
Any authentication mechanism that works in Drupal is also supported by us. These are completely orthogonal things. There is nothing in the GraphQL Module that prevents any form of authentication from working. So yes: Basic auth works with Drupal. Keep in mind, that Basic auth does NOT mean prefixing the Url with username / password. It means adding them in the header of the request.
