### ISSUE TITLE
Fix query maps page (persisted queries)

### ISSUE THREAD

**Issue by sasanikolic90** [drupal-graphql/graphql#579]
When I go to the /en/admin/config/graphql/query-maps/json page, I get the following error message:

> The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">RuntimeException</em>: Controller &quot;Drupal\graphql\Form\JsonQueryMapConfigForm::buildForm()&quot; requires that you provide a value for the &quot;$formState&quot; argument (because there is no default value or because there is a non optional argument after this one). in <em class="placeholder">Drupal\Core\Controller\ControllerResolver-&gt;doGetArguments()</em> (line <em class="placeholder">165</em> of <em class="placeholder">core/lib/Drupal/Core/Controller/ControllerResolver.php</em>).

**Comment by bastnic** [comment]
@sasanikolic90 encountered the same error, PR proposed.
