### ISSUE TITLE
Use Enum argument for image styles.

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#58]
Currently, every image style generates a separate field. Instead, it should be a single field with an Enum argument.

**Comment by webflo** [comment]
👍 Sound good to me, we can get rid of the "original" image style with this.

**Comment by fubhy** [comment]
@webflo what's your email address? Would like to invite you to our #graphql slack channel :)

**Comment by pmelab** [comment]
Solved in #78
