### ISSUE TITLE
Missing code from Config Entities PR

### ISSUE THREAD

**Issue by pavlosdan** [drupal-graphql/graphql#580]
Was trying to find out what happened to the Config Entities support.

Tracked down this which had a message about merging branch 8.x-3.x into the config-entities branch but after that the branch seems to get deleted without being merged back into 8.x-3.x?
https://github.com/drupal-graphql/graphql/pull/477

**Comment by tguilpain** [comment]
Answer from @pmelab in slack graphql chan:
"the approach was dropped, because there are *many* types of config entities, and we would have inflated the schema with a lot of stuff that never gets used.

so, until we have the configurable schema, it’s back to custom fields for config entities."

**Comment by pavlosdan** [comment]
closing this as per @pmelab 's explanation as it solves the mystery of the missing code.
