### ISSUE TITLE
Paragraphs breaks GraphQL in Drupal 8.5.x with GraphQL 8.3.x

### ISSUE THREAD

**Issue by codycraven** [drupal-graphql/graphql#583]
Attempting to use the Explorer or Voyager after adding a [Paragraphs](https://www.drupal.org/project/paragraphs) field to an entity bundle (I specifically tested a node type) results in a broken interface.

The JS error reported is `Uncaught TypeError: Cannot read property 'types' of undefined`.

When inspecting the Drupal settings the following can be found:

<img width="523" alt="screen shot 2018-04-23 at 4 18 36 pm" src="https://user-images.githubusercontent.com/1533965/39157927-13924676-4712-11e8-8f86-e88b23697242.png">

**Comment by freelock** [comment]
We are seeing this as well -- though it might also have to do with metatag...
In any case, for the time being downgrading to beta5 has gotten us back working again... beta6 and beta7 are both broken for us -- easily visible in GraphiQL Explorer, and also broken on the endpoint.

I tried to debug but xdebug kept crashing on me when trying to inspect inside a closure...

On rolling back, I'm seeing that beta6 brought in a different GraphQL library, which makes me suspicious that that is at least partially responsible...

**Comment by fubhy** [comment]
Can you enable the development mode (graphql.services.yml), rebuild the cache and then run a manual query against the endpoint again and check the error message (or check the introspection data as you already did before).

**Comment by pmelab** [comment]
A fresh install of paragraphs doesn't have any bundles. In this case we created the interface *and* the type. #594 Should fix that.
