### ISSUE TITLE
Consider adding entityTranslation() and entityLanguage fields to entity types.

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#59]
We could easily add an entityLanguage field that returns the language object of the current translation of an entity. I think that is a no-brainer and should be added in any case.

In addition to that, we could make translations of an entity accessible via a entityTranslation() field with an Enum language arg.

Thoughts?

**Comment by fubhy** [comment]
I added a language type.

**Comment by blazeyo** [comment]
Hi @fubhy,

First of all, please bare with me. I'm new to the module and even no-brainers are hard to me at this point :).

My code is in #108. It doesn't work yet, so please don't merge it. What I did: 
- Added _Drupal\graphql_content\Plugin\GraphQL\Fields\EntityLanguage_
- Added entityLanguage to _Drupal\graphql_content\Plugin\GraphQL\Interfaces\Entity_'s annotation
- Adjusted _Drupal\Tests\graphql_content\Kernel\EntityBasicFieldsTest_ to test the new field.

As a result I'm getting to **You have specify fields for "entityLanguage"** error when running the test query. I've looked at _Drupal\graphql_core\Plugin\GraphQL\Types\Url_ definition and it's annotation has the fields enumerated **fields  = {"path", "alias", "routed"}** while _Language_ definition only has **data_type = "language"**. Should I add *fields* (name, code, direction and weight) to the language definition as well? If so, is it ok to remove the **dataType**?

**Comment by pmelab** [comment]
You correctly applied the type "Language" to your field. Now GraphQL assumes you are return a object of type GraphQL.  Now you just have to query properties of this object in the query:

```
entityLanguage {
  id
  ...
}
```

... and actually return the language object instead of the id in your resolver function, and you should be good :)

**Comment by blazeyo** [comment]
entityLanguage field is ready for testing. A follow up issue for the entityTranslation has been created (#109).

**Comment by blazeyo** [comment]
@fubhy About the second part of the issue, the entityTranslation, should it look somewhat like this:

```
query ($path: String!) {
  route:route(path: $path) {
    node:nodeContext {
      entityId,
      ...
      entityTranslation("en") {
        entityId,
      }
    }
  }
}
```

**Comment by fubhy** [comment]
@blazeyo Close! Like this:

```graphql
query ($path: String!) {
  route:route(path: $path) {
    node:nodeContext {
      entityId,
      ...
      entityTranslation(language: en) {
        entityId,
      }
    }
  }
}
```

The "language" argument could be of type Enum (you would have to create a Enum type that contains all active languages of a site).

**Comment by blazeyo** [comment]
This issue can be closed. `entityLanguage` has already been merged and for `entityTranslation` there is a follow up issue #109
