### ISSUE TITLE
Handle routes that are handled by the redirect module

### ISSUE THREAD

**Issue by luksak** [drupal-graphql/graphql#591]
We are using the redirect module to handle derpecated URLs. Currently when querieng for routes that are handled by the redirect module, graphql returns null:

```
query RouterQuery {
  route(path: "/test-redirect1") {
    path
  }
}
```

**Comment by peterkeppert** [comment]
Hi @luksak , I have already developed the module, will publish module on drupal.org shortly and post link here.

**Comment by luksak** [comment]
@peterkeppert great! I'm happy to review it!

**Comment by peterkeppert** [comment]
Hi @luksak , I added the module to github for now: https://github.com/peterkeppert/drupal-graphql-redirect Once reviewed, I will publish it on drupal.org.

It is currently dependent on one redirect patch that I have created: https://www.drupal.org/project/redirect/issues/2962966 . Without the patch, path resolution fails with exception.

@fubhy , @pmelab if you could spare some time, your feedback would be also greatly appreciated. Thanks!

**Comment by peterkeppert** [comment]
Hi, I have published the module at https://www.drupal.org/project/graphql_redirect

**Comment by pmelab** [comment]
I'm sorry for the late response @peterkeppert !

The module is technically correct, but it basically turns redirects into aliases. The client will never know that a url has changed. What we did until now is using the properties on the url response object to retrieve status code and redirect headers, and handle the redirect in the frontend application.

Correct me if I'm wrong, but what you do here can also be achieved with url aliases. And e.g. search engines won't get any information about 301s and 302s.

**Comment by tguilpain** [comment]
@peterkeppert , it seems that your solution (patch + module) is not working anymore with the latest version of graphql. Are you able to fix it?
Alternatively @pmelab , can you explain your solution?
When I query a redirect path like so
`route(path: $path) {
    ... on DefaultInternalUrl {
      request: request{
        code
        header
     }
}
`
all I get is 
`
{
  "data": {
    "route": null
  }
}
`
So I do not understand how would the front end work out the redirect from there

**Comment by pmelab** [comment]
@peterkeppert, @luksak : I've created PR #666. Could you check if this works for you?
