### ISSUE TITLE
DEFAULT EntityQueryRevisionMode in nodeQuery does not return the latest unpublished (Draft) revision of an previously already published node

### ISSUE THREAD

**Issue by fedelman** [drupal-graphql/graphql#599]
DEFAULT EntityQueryRevisionMode in nodeQuery does not return the latest unpublished (Draft) revision of an previously already published entity

A node query like

`
query getNews {
	nodeQuery(
		revisions: DEFAULT,
		filter: {
			conjunction: AND
			conditions: [
				{
					field: "type"
					value: ["news"]
				},
				{
					field: "status"
					value: ["0", "1"]
				}
			]
		},
		offset: 0,
		limit: 100,
		sort: [
			{
				field: "nid"
				direction: DESC
			}
		]
	)
	{
		count
		entities {
                         entityId
			... on NodeNews {
                                 title
				nid
				vid
				status
                          }
		}
	}
}`

should return the latest revision of every node of type "news" no matter whether this node is published or unpublished (draft). At the moment (with beta 7) this is not the case, however. It returns the latest revision of an unpublished node (state=0) und the latest revision of every published node of type "news" (state=1). However, if you modify an already published node and save these changes as draft, that is, do not yet publish these modifications, then these draft revisions are not returned. To get them you have to specify the EntityQueryRevisionMode ALL. However, with this option you get back all revisions of every node and not only the latest which is very inefficient if you are only interested in the latest revisions.

I use Drupal decoupled with GraphQL to read the content into an Vue.js App. To provide some kind of preview of content that is not yet published, I need an easy way to get either the latest revision of every published node (state=1) or the latest revision of every node no matter whether it is already published or not (state=1||state=0). This is rather difficult and inefficient with the current implementation of a node query (as described above). Would it be possible to introduce a third EntityQueryRevisionMode LATEST, for example, to provide this functionality? Or is there maybe already a way to create such a query?

**Comment by fubhy** [comment]
Hi there. We are just using the default behavior of entity query. Most of what you see here is just syntax around the core entity query implementation. That's quite visible if you look into this file: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityQuery/EntityQuery.php

For your specific case, this is the place: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityQuery/EntityQuery.php#L225.

If you want, you can play around with that part a bit to see if you can find a solution that works within the boundaries of the core entity query spec and works generically (as you suggested) or, alternatively, you can also override or append EntityQuery field for your specific use-case. Either by overriding the plugin directly or by adding a new, more specialized field.

**Comment by walterjenner** [comment]
Hi!

After a quick check it seems that using the latestRevision method of EntityQuery works here.

However, I wonder if it is really that simple, or if we forgot something. If this really works at it seems (loading and filtering against only the latest revision), then this functionality might be worth to add to the module.

I have attached a patch.

[support-latest-revision.txt](https://github.com/drupal-graphql/graphql/files/1979494/support-latest-revision.txt)

**Comment by walterjenner** [comment]
For a better overview I have created a Pull request here #602
