### ISSUE TITLE
Awkward multi-locale route resolving

### ISSUE THREAD

**Issue by mbajur** [drupal-graphql/graphql#600]
Hello,

i'm moving an old Wordpress site to a decoupled drupal setup - and i decided to go for GraphQL as i know it and really enjoy using it + it's easier to parse than jsonapi responses + drupal implementation is so good i couldn't resist (🙌).

My website has two locales - english and polish and the default one is polish. I can list all the posts for desired locale using `langcode` filter but things get tricky when i wan't to resolve a single article using it's path. My query looks like that:

```
query Article ($path: String!) {
  route(path: $path) {
    ... on EntityCanonicalUrl {
      entity {
        ... on NodeArticle {
          nid
          title
          body {
            value
          }
        }
      }
    }
  }
}
```

and this query returns anything ONLY if graphql endpoint URL used to send it is prefixed with the desired article locale code. So, if i have an article in polish language, the only way to get it using the query above is to prefix graphql endpoint URL with `/pl/`. On the other hand, listing all the articles don't care about the locale prefix of graphql endpoint and returns articles for all the locales (unless i specify a langcode filter) so i can presume it's something with the `route` field.

Is there anything i can do to skip the graphql endpoint prefix thing? That's a complete no-go in my setup as i can't have multiple graphql endpoint URLs and switching them during runtime is not possible.

- Drupal - 8.4.6
- GraphQL - 8.x-3.0-beta3
- GraphQL Core - 8.x-3.0-beta3

**Comment by pmelab** [comment]
Language handling changed drastically in beta 7, basically because of the issues you also face:
https://github.com/drupal-graphql/graphql/blob/8.x-3.x/doc/upgrade/beta6.md

**Comment by fubhy** [comment]
Hi there. Thanks for the flowers! This should be solved already. Try upgrading to the latest version. Please report back if you are still facing issues then!
