### ISSUE TITLE
Route query results in 500 error

### ISSUE THREAD

**Issue by davidwhthomas** [drupal-graphql/graphql#603]
Currently in 8.x-3.0-beta7 the `route` query results in an internal server error

```
{
  route (path:"/node/1") {
    ... on EntityCanonicalUrl {
      entity {
        entityLabel
      }
    }
  }
}
```

After some debugging, it appears to be because `$this->languageNegotiator->getNegotiationMethodInstance` requires the `currentUser` in it's call to `$instance->setCurrentUser($this->currentUser);`

I'll attach a patch shortly to inject and add the current user, which fixes this issue.

Edit: PR added here: #604

**Comment by fubhy** [comment]
It seems that somehow the LanguageRequestSubscriber does not run for you.

I also replied to the PR:

```
That's strange. That should be set automatically by the LanguageRequestSubscriber: https://github.com/drupal/drupal/blob/8.6.x/core/modules/language/src/EventSubscriber/LanguageRequestSubscriber.php

Are you doing a graphql query pre-bootstrap somehow? Or did you remove the langaguage request subscriber from the event registry? Or something else?
```

**Comment by fubhy** [comment]
Please debug with a breakpoint in https://github.com/drupal/drupal/blob/8.6.x/core/modules/language/src/EventSubscriber/LanguageRequestSubscriber.php#L74

If that doesn't run then let's investigate and find out why. I don't think that we should manually inject the current user there because that's apparently the responsibility of the request subscriber there.

**Comment by davidwhthomas** [comment]
Hi @fubhy thanks for checking the issue. You are correct on your analysis.

It appears it is because on a default mono-lingual D8 site, the `LanguageRequestSubscriber` is not added in this line: https://github.com/drupal/drupal/blob/8.5.x/core/modules/language/src/LanguageServiceProvider.php#L23

```
    if ($this->isMultilingual()) {
      $container->register('language_request_subscriber', 'Drupal\language\EventSubscriber\LanguageRequestSubscriber')
```

So, the `currentUser` isn't available there.

Assuming the currentUser can be added for other multilingual cases, as an alternative approach, perhaps the `route` resolver could be updated to skip that language logic part if the site isn't multilingual.

**Comment by davidwhthomas** [comment]
Based on the above, I've added another PR using the approach to skip the additional language negotiation check if the site isn't multilingual in #605

**Comment by fubhy** [comment]
Nice.  Thanks for checking and for the comprehensive analysis and new pull request.
