### ISSUE TITLE
Add a specific class to "Inspect GraphQL query" button and apply styling to it

### ISSUE THREAD

**Issue by sasanikolic90** [drupal-graphql/graphql#607]
Currently, we target `.graphql-twig-debug-wrapper input[type="submit"]` which breaks other input fields on the page, as `graphql-twig-debug-wrapper` wraps the whole content of the page.

I suggest we add a specific class to the button and apply styling to it.

**Comment by pmelab** [comment]
This is related to the `graphql_twig` module, and was fixed in https://github.com/drupal-graphql/graphql-twig/commit/45a9fa37f5ea27081f148be2fb18f924e83093a1
