### ISSUE TITLE
Add delta field to EntityReference type Objects

### ISSUE THREAD

**Issue by prineshaz** [drupal-graphql/graphql#608]
Hi guys,

Thank you for the excellent work you've put into this module. Im currently trying to understand how to create new fields, im having difficulty trying to extend EntityReference Complex object type to include the delta.

Ive followed the implementations of [EntityReference](https://github.com/drupal-graphql/graphql/tree/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityReference), but without much documentation (ie i dont know what GraphQLField annotation properties refer to) its a little hard to try to piece together how everything fits. 

Im trying to add a delta GraphQL field so that the delta for each referenced entity is provided. 

![screen shot 2018-05-16 at 17 16 44](https://user-images.githubusercontent.com/8041188/40130313-8bca9d2c-592e-11e8-8f70-7c9f59c073f7.png)

I've inspected this, but to me (forgive me if im wrong), it looks as if ER field executes a query?

https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityReference/EntityReferenceReverse.php

```
/**
 * @GraphQLField(
 *   id = "entity_reference_reverse",
 *   secure = true,
 *   type = "EntityQueryResult!",
 *   arguments = {
 *     "filter" = "EntityQueryFilterInput",
 *     "sort" = "[EntityQuerySortInput]",
 *     "offset" = {
 *       "type" = "Int",
 *       "default" = 0
 *     },
 *     "limit" = {
 *       "type" = "Int",
 *       "default" = 10
 *     },
 *     "revisions" = {
 *       "type" = "EntityQueryRevisionMode",
 *       "default" = "default"
 *     }
 *   },
 *   deriver = "Drupal\graphql_core\Plugin\Deriver\Fields\EntityReferenceReverseDeriver"
 * )
 */
```

Also what importance does the 'deriver' hold here? 

Thank you in advance.

**Comment by pmelab** [comment]
The query you mentioned is in the `EntityReferenceReverse` field, which provides the relation in the opposite direction.

The fields on the EntityReference complex object type are derived from Drupal's typed data structure. So the best way to add the delta property is actually adding it as a field property to entity reference fields:
https://www.drupal.org/docs/8/api/entity-api/dynamicvirtual-field-values-using-computed-field-property-classes
