### ISSUE TITLE
The "language-graphql" plugin does not exist 

### ISSUE THREAD

**Issue by webflo** [drupal-graphql/graphql#611]
Similar issue to https://github.com/drupal-graphql/graphql/issues/575

Happens again in beta6

**Comment by AndyRead** [comment]
I'm getting this same message trying to install on Drupal 8.5.3.  composer require is fetching graphql 8.x-3.0-beta8.  I get the error when I try to enable graphql, but it's left thinking it installed but not usable (/graphql returns exception error message) and fails to uninstall again!
Composer update has updated drupal to 8.5.4, but no difference.

**Comment by AndyRead** [comment]
But fubhy's commit 8445d04 above seems to fix the issue (clean uninstall and install at least).

**Comment by fubhy** [comment]
So this is fixed? Please re-open if that's not the case.

**Comment by Daveiano** [comment]
I tried to install GraphQL 8.x-3.0-beta8, same problem:

`Drupal\\Component\\Plugin\\Exception\\PluginNotFoundException: The "language-graphql" plugin does not exist. in /var/www/.../core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php on line 52`

**Comment by aaleksan** [comment]
Same problem with GraphQL 8.x-3.0-beta8, which version should we install for a functioning module that works with languages. Thanks

**Comment by naitschi** [comment]
Got the same Problem as @Daveiano .

**Comment by davidspiessens** [comment]
Same problem here.

**Comment by rfnbnkr** [comment]
I have a same problem

**Comment by yookoala** [comment]
I ran into similar issue today. My solution:

Suppose you don't have any data stored in database of this module (which there should be none, to my understanding).

1. Open `core/modules/language/src/LanguageNegotiator.php`.
2. Go to the public function `initializeType()`.
3. Find these line:
    ```php
        if (!isset($this->negotiatedLanguages[$method_id])) {
          $this->negotiatedLanguages[$method_id] = $this->negotiateLanguage($type, $method_id);
        }
    ```
4. Change to 
    ```php
        if (!isset($this->negotiatedLanguages[$method_id])) {
          if ($method_id != 'language-graphql') {
            $this->negotiatedLanguages[$method_id] = $this->negotiateLanguage($type, $method_id);
          }
        }
    ```
5. Use drush to uninstall the graphql module.
6. Do whatever you want (e.g. reinstall the module of later version).

**Comment by yookoala** [comment]
Part of the confusion is that the [language negotiator](https://api.drupal.org/api/drupal/core%21modules%21language%21src%21LanguageNegotiator.php/function/LanguageNegotiator%3A%3AinitializeType/8.2.x) doesn't handle the [PluginNotFoundException](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Plugin%21Exception%21PluginNotFoundException.php/class/PluginNotFoundException/8.2.x) error

It should not have been a site breaking issue. It should be handled in a more graceful manner.

I'm pushing to change the behaviour here:
https://www.drupal.org/project/drupal/issues/3134349 

Please endorse and follow the issue there. Thanks.

**Comment by freality** [comment]
I've run into this issue, but with plugin ID 'language-graphql-operation'. @yookoala solution helps restore your system. But if the problem lingers after uninstalling the graphql module. Remove the offending plugin id from your `language.types` configuration, eliminates the error state.

I hope this tip helps any persons encountering this issue.

**Comment by Rar9** [comment]
@freality  - How to remove this

**Comment by cweiske** [comment]
> Remove the offending plugin id from your language.types configuration, eliminates the error state.

1. Open `/admin/config/regional/language/detection`
2. Click "save"

When using "config:export", `config/default/language.types.yml` will be modified now.
