### ISSUE TITLE
An attempt at subscriptions

### ISSUE THREAD

**Issue by nodeworks** [drupal-graphql/graphql#614]
I made a sandbox module with the purpose of attempting subscriptions with this module. Would love some feedback and help! It's under active development.

https://www.drupal.org/sandbox/ledzepp94/graphql_subscription 

Also:

#613

**Comment by fubhy** [comment]
Great stuff. Will check it out tomorrow.

**Comment by fubhy** [comment]
Thanks! I merged your PR. It lacks test coverage but since it's a straight copy of the existing architecture, I can live with that. I made some small adjustments before merging (code style, etc.).
