### ISSUE TITLE
Entity field schema poisoning

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#615]
BUG
Entity field defined in one bundle is visible under other bundle also.

---
example: fieldTags is defined only on NodeArticle, but fieldTags is displayed under NodePage also (in graphql explorer Docs).
Even querying such fields does not throw any error:
such field returns null or empty array (for multi-value fields).

```
... on NodePage {
        fieldTags {
          targetId
        }
}
```
---

The bug is caused by this commit:
https://cgit.drupalcode.org/graphql/commit/?id=1b1eb9d

Reverting the commit fixes the problem.

**Comment by pmelab** [comment]
@Pasqualle I pushed a new PR that should fix this problem: #640. Are you able to verify it helps?

**Comment by Pasqualle** [comment]
Hi. the PR seems to work for me.. Thanks

**Comment by RoMay** [comment]
Hi @Pasqualle @pmelab, could you please update us when this fix will be released? Thanks

**Comment by pmelab** [comment]
@RoMay The fix should be in the latest dev version of the module. And I think we will tag a new release during Drupal Europe next week.

**Comment by RoMay** [comment]
@pmelab It's great news, thanks guys!
