### ISSUE TITLE
Invalid front page URL alias in "languageSwitchLinks"

### ISSUE THREAD

**Issue by julkue** [drupal-graphql/graphql#617]
Assuming you have installed and enabled the [Redirect module](https://www.drupal.org/project/redirect) and have enabled "Enforce clean and canonical URLs" the following in `/admin/config/search/redirect/settings`:

![topic](https://user-images.githubusercontent.com/8310677/40784107-e7c11734-64e4-11e8-89f9-b26466657802.png)

Then what you get backend-side is that whenever you request `/` you will be redirected to e.g. `/de` or `/en` to avoid duplicate content when the "URL" detection method is enabled (`/admin/config/regional/language/detection`).

So, when requesting `/` in a `route` GraphQL query I would expect the following language switch links:

1. `/de`
2. `/en`

Instead, it will just result in:

1. `/de/node/1`
2. `/de/node/2`

due to the fact that `node/1` was specified as the default front page.

**Example:**

Query:

```graphql
query CurrentPage ($currentPath: String!) {
  content: route(path: $currentPath) {
    ... on EntityCanonicalUrl {
      entity {
        ... on NodeParagraphsPage {
          title
          fieldParagraphs {
            ...ParagraphsEntityFragment
          }
        }
      }
      languageSwitchLinks (language:DE) {
        active
        title
        url {
          path
        }
        language {
          id
        }
      }
    }
  }
}

fragment ParagraphsEntityFragment on FieldNodeFieldParagraphs {
  entity {
    ...ParagraphsEntityFieldsFragment
  }
}

fragment ParagraphsEntityFieldsFragment on Paragraph {
  type {
    targetId
  }
}
```

Then your response will be like:

```json
{
  "data": {
    "content": {
      "entity": {
        "title": "Startseite",
        "fieldParagraphs": [
          {
            "entity": {
              "type": {
                "targetId": "hero"
              }
            }
          },
          {
            "entity": {
              "type": {
                "targetId": "media"
              }
            }
          }
        ]
      },
      "languageSwitchLinks": [
        {
          "active": true,
          "title": "German",
          "url": {
            "path": "/de/node/1"
          },
          "language": {
            "id": "de"
          }
        },
        {
          "active": false,
          "title": "English",
          "url": {
            "path": "/en/node/1"
          },
          "language": {
            "id": "en"
          }
        }
      ]
    }
  }
}
```

Notice that the front page alias is invalid:

![topic](https://user-images.githubusercontent.com/8310677/40784094-d7abfeea-64e4-11e8-88ca-83b3ff21785d.png)

**Comment by fubhy** [comment]
@julmot Sorry for the late reply. And thank your for the detailed description for how to reproduce this problem. We are going to examine in the next few days.
