### ISSUE TITLE
Documention on Auth

### ISSUE THREAD

**Issue by elistone** [drupal-graphql/graphql#618]
Looking for some documentation on how to create login / logout using GraphQL.

Is this built in? Or do you have to create everything manually?

If so could I get some help on what queries to be running to check login/return tokens.

**Comment by scubafly** [comment]
You can install the [simple_oauth](https://www.drupal.org/project/simple_oauth) module.
You can then authenticate with your drupal username and pass.

There is a good tutorial here about oAuth:
https://www.youtube.com/watch?v=rTcC0maPLSA&list=PLZOQ_ZMpYrZtqy5-o7KoDhM3n6M0duBjX
It is a bit outdated so some fieldnames are changed, but it helped me to set this up.

**Comment by joaogarin** [comment]
I did a little blog post a while back on authentication, altough most of the frontend code is in Angular it could be adapted to another framework. Just recently did the same in react. the concepts are the same. Like mentioned by @scubafly the easiest way is to follow Matheo's guides on simple_auth.

http://joaogarin.com/posts/drupal-graphql-with-angular-and-apollo-part1

Hopefully soon we can add some generic docs on authentication

**Comment by justinlevi** [comment]
One caveat is that file uploading is impossible with simple_oauth without
super ugly hacks

**Comment by elistone** [comment]
Sorry for the slow response to this, I have not really had chance to test it but as I believe @scubafly answer for using simple_oauth will solve it I will close this ticket.

**Comment by berliner** [comment]
> I did a little blog post a while back on authentication, altough most of the frontend code is in Angular it could be adapted to another framework. Just recently did the same in react. the concepts are the same. Like mentioned by @scubafly the easiest way is to follow Matheo's guides on simple_auth.
> 
> http://joaogarin.com/posts/drupal-graphql-with-angular-and-apollo-part1
> 
> Hopefully soon we can add some generic docs on authentication

That link is now https://www.joaogarin.com/blog/drupal-graphql-with-angular-and-apollo-part1
