### ISSUE TITLE
Anonomous user can execute queries without permissions.

### ISSUE THREAD

**Issue by scubafly** [drupal-graphql/graphql#621]
**Steps to reproduce:**
1) Create some nodes.
2) Set these permissions for anonomous user. ( none )
<img width="1223" alt="permissions" src="https://user-images.githubusercontent.com/820268/41294552-967a8982-6e58-11e8-982b-2775c19fdb92.png">

**Espected behavoir:**
Anonomous user can not execute query without the permission 'Execute arbitrary GraphQL requests'

**Acctual behavoir**
I'm still able to get results from <sitename>/graphql?query={nodeQuery{entities{entityLabel}}}

I'm not sure this is only on my machine / configuration.

**Comment by pavlosdan** [comment]
I tested this on a couple of our instances but couldn't replicate. Running beta8 here.

**Comment by scubafly** [comment]
Thanks for testing. I'll setup a clean install and try to reproduce it.
For some background information: I'm running drupal 8.5.4 with graphql 3.0.0-beta8

**Comment by pavlosdan** [comment]
ah. still running 8.4 here. unsure if that could cause the discrepancy.

**Comment by fubhy** [comment]
I can't replicate this either. Please re-open this if you can provide steps to reproduce this. Thanks!
