### ISSUE TITLE
Return error message with response

### ISSUE THREAD

**Issue by davidwhthomas** [drupal-graphql/graphql#624]
Currently I have an issue where `EntityById` will return `NULL` if the user doesn't have access to the node, and also if the node doesn't exist. 

It's been requested to add some error message to the response for the access denied case, so the client knows to login for example for an unpublished node.

I've found it doesn't appear possible to add the Exception to the GraphQL response and wondering if any suggestion on it.

For example, in the `resolve` function, throwing an exception always results in the generic error:

```{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "nodeById"
      ]
    }
  ],
  "data": {
    "nodeById": null
  }
}
```

Is there any way to customise the `message` and `category` in the error message there? Thanks!

**Comment by fubhy** [comment]
You can't just throw any exception, you have to use a ResolveException: https://github.com/Youshido/GraphQL/blob/master/src/Exception/ResolveException.php

**Comment by fubhy** [comment]
Retracted. Drunk comments. Blabla. Stupid answer. Scroll down...

**Comment by davidwhthomas** [comment]
Hi @fubhy hey thanks for the quick response, just a question on it.

As the latest `drupal-graphql` version is using the webonyx backend,  the `ResolveException` isn't available there, do we need to use or reimplement it from the Youshido library?

I found one other related thing in my code travels:

in `ProcessQuery`

    $config->setDebug(!empty($this->config['development']));

If this value is set to `TRUE` the resolver exception message is displayed in `debugMessage`

```
{
  "errors": [
    {
      "debugMessage": "Access denied",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 4,
          "column": 3
        }
      ],
      "path": [
        "nodeById"
      ]
    }
  ],
  "data": {
    "nodeById": null
  }
}
```

However, it's not ideal to enable that `development` flag in production.
Perhaps we need another flag for the debug messages there?

Thanks again for the work on the excellent module, great stuff.

**Comment by fubhy** [comment]
Sorry. I am a bit drunk. I looked up the wrong library :D. One second.

**Comment by fubhy** [comment]
You have to use one of these: https://github.com/webonyx/graphql-php/blob/master/src/Error.

Probably https://github.com/webonyx/graphql-php/blob/master/src/Error/UserError.php in your case.

**Comment by davidwhthomas** [comment]
LOL, nice I'll try it and get back shortly, thanks :)

**Comment by fubhy** [comment]
Note the "isClientSafe" flag. That will make sure it is also displayed in a non-dev environment,

**Comment by davidwhthomas** [comment]
It works! great stuff, many thanks @fubhy!

Here's some sample code for reference:
```
use GraphQL\Error\Error;
...
// In resolver
throw new Error('sample message');
```
Result:
```
{
  "errors": [
    {
      "message": "sample message",
      "category": "graphql",
      "locations": [
        {
          "line": 4,
          "column": 3
        }
      ],
      "path": [
        "nodeById"
      ]
    }
  ],
  "data": {
    "nodeById": null
  }
}
```

Will continue tinkering, cheers!

**Comment by fubhy** [comment]
Note that you might want to user a UserError (instead of Error) if you also intend to print it in non-development mode.

**Comment by davidwhthomas** [comment]
Cool, I've updated it to use `use GraphQL\Error\UserError;` and `throw new UserError('sample message');` just in case. It's working well, many thanks!
