### ISSUE TITLE
Entity reference fields that returns null on referenced entities

### ISSUE THREAD

**Issue by sebas5384** [drupal-graphql/graphql#625]
Hi,

entity reference fields are amazing but when someone deletes a referenced entity it doesn't remove itself from the relation. This causes a big problem for the front-end for example, because is easy to cause a bug when you have a result item, but it's value is `null`.

IMO we should remove the entity from the list, for example `productVariations` it's a reference field:
From:
```json
"fieldProducts": [
  {
    "entity": null,
    "__typename": "FieldBlockContentFieldProducts"
  },
  {
    "entity": null,
    "__typename": "FieldBlockContentFieldProducts"
  },
  {
    "entity": null,
    "__typename": "FieldBlockContentFieldProducts"
  }
]
```
To:
```json
"productVariations": []
```

This on GraphQL lang would be the equivalent to `[Entity!]!` following this reference:

```
declaration accepts: | null | []   | [null] | [{foo: 'BAR'}]
------------------------------------------------------------------------
[Vote!]!             | no   | yes  | no     | yes
[Vote]!              | no   | yes  | yes    | yes
[Vote!]              | yes  | yes  | no     | yes
[Vote]               | yes  | yes  | yes    | yes
```

**Comment by sebas5384** [comment]
Issue on Drupal.org about this: https://www.drupal.org/project/drupal/issues/2723323

**Comment by wimleers** [comment]
We recently fixed a related bug in JSON API: https://www.drupal.org/project/jsonapi/issues/2968972 — of course https://www.drupal.org/project/drupal/issues/2723323 would solve it for everyone: JSON API, GraphQL, REST, and really … all of Drupal!

**Comment by fubhy** [comment]
This needs to be fixed in Drupal core because we do not actually have a specific field for entity references and even if we did, we could not validate this case without actually trying to load the referenced entities which has a performance impact that might not be desired in all cases (e.g. when you don't want to load the actual entity but just the id).
