### ISSUE TITLE
Automatic Persisted Queries (APQ)

### ISSUE THREAD

**Issue by lucasconstantino** [drupal-graphql/graphql#626]
I've just release a sandbox project with an [automatic persisted queries](https://www.apollographql.com/docs/engine/auto-persisted-queries.html) implementation based on Apollo Engine's [protocol](https://github.com/apollographql/apollo-link-persisted-queries#protocol):

https://github.com/lucasconstantino/drupal-graphql-apq

**Comment by fubhy** [comment]
Great stuff. I think we should open a section about related modules in the docs? Anyone wanna take a stab at that?

**Comment by joaogarin** [comment]
Do you mean like graphql_metatg, graphql_twig, graphql_redirect and so on? I think thats a great idea. I did add a couple things about the metatag but its interesting having some of the other stuff in there as well.

I wouldn't mind doing some work on that, was wondering if we should make it like use case driven (metatags, handling redirects, persisted queries) and in each of the use cases provide some tip or recommendation for using such modules? The other approach would be to kind of list the modules and describe how they help / complement the core module.

**Comment by pavlosdan** [comment]
Took a stab at this by adding a Related Modules section to the README. Apologies if I missed a module.

I like @joaogarin's idea. Should each module's use-cases and examples though be in a doc on each module instead of part of the core module?
