### ISSUE TITLE
Roadmap to RC/stable release?

### ISSUE THREAD

**Issue by pavlosdan** [drupal-graphql/graphql#629]
Hi guys, 

Was wondering if there's a roadmap to what it would take for the module to get an RC and/or a stable release. Any of the current issues blocking this?

Thanks

**Comment by ddanilets** [comment]
Hi guys,

Any news on this?

**Comment by fubhy** [comment]
Hi there. We are in the process of preparing the release now. So there's no specific roadmaps regarding features but rather us walking through the open issues right now and resolving / closing them.

Once we are done with that we will publish the RC1 in the next few days.
