### ISSUE TITLE
When a node revision is deleted the respective entry in cache_graphql_results is not flushed.

### ISSUE THREAD

**Issue by walterjenner** [drupal-graphql/graphql#636]
Steps to reproduce are:
* Create a draft revision in Drupal
* Query Drupal using nodeQuery and set parameter revisions to LATEST
* Graphql returns (and caches) the correct revision
* Delete the latest revision via the revisions tab in Drupal
* Re-run query
* The same (deleted) content is returned
* Flush cache_graphql_results 
* Re-run query
* The correct content is returned

Tested on Drupal 8.5.3 and graphql 8.x-3.0-beta8

**Comment by pavlosdan** [comment]
Seems like a broader Core issue?
https://www.drupal.org/project/drupal/issues/2879244
https://www.drupal.org/project/drupal/issues/2945928

**Comment by fubhy** [comment]
Yep. Sadly, the only 100% appropriate fix for this would be to fix https://www.drupal.org/project/drupal/issues/2879244

Hence, I am going to close this issue.
