### ISSUE TITLE
Invalid translation language specified

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#647]
If a page has a translatable field and the field is not translated then graphQL query, like router, returns
an error "Invalid translation language (xx) specified." for that field, and the field value is null.

There are 3 options how to fix this problem
1. Add hasTranslation() check before getTranslation() call [explained on stackexchange](https://drupal.stackexchange.com/questions/215358/invalid-translation-language-fa-specified)

Therefore graphQL will just return the original untranslated entity.

2. Add hasTranslation() and return null if translation does not exists.

3. Use the language fallback as Drupal core does, with [entityRepository->getTranslationFromContext](https://cgit.drupalcode.org/drupal/tree/core/lib/Drupal/Core/Entity/EntityRepository.php#n82)

I would go with option 3, and maybe the Drupal's language fallback can be modified in case someone would like to go with option 2, to return nothing if there is no translation.

**Comment by pmelab** [comment]
Merged, thanks!

**Comment by Kingdutch** [comment]
@pmelab The PR that you merged said "Warning: do not merge. This will display entities with original language." and this issue recommended option 3 rather than the option implemented in the PR.

Could you elaborate on why option 1 was chosen anyway? Especially when choosing between option 1 and 3 for #1176 as well? :)

**Comment by pmelab** [comment]
🤔 I suppose there where conversations outside of this PR, but i can't remember it. Let's move the conversation to #1176 ...
