### ISSUE TITLE
QUESTION: Schema Stiching

### ISSUE THREAD

**Issue by dirtystylus** [drupal-graphql/graphql#648]
Hi folks, I was wondering if anyone has documentation on merging remote endpoints into GraphQL. I have a system that needs to pull some data from an external API and merge it with Drupal data before returning output. This sounds like schema stiching, [described here in the Apollo documentation](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html). Is this something that can be done with an existing hook in the Drupal 8 GraphQL module?

**Comment by Pasqualle** [comment]
We are using a separate graphQL server to stitch Drupal 8 schema and other graphQL and REST servers.
This gives us a security benefit, that our Drupal installation is not publicly accessible.

**Comment by fubhy** [comment]
You can use schema stitching (apollo feature) if you like. Or you write your own plugins and handle the remote API in Drupal directly. Up to you. If the other endpoints are also GraphQL endpoints, stitching might make sense. In that case, however, you need to do that outside of Drupal.

**Comment by dirtystylus** [comment]
@fubhy Thanks for the note. Particularly interested in this:

> Or you write your own plugins and handle the remote API in Drupal directly

I was attempting to use the alter hooks described here: https://www.amazeelabs.com/en/blog/extending-graphql-part-2 but those don’t seem to fire, I’m wondering if that’s because the 8.x-3.x version no longer uses them?

Would love any examples/documentation about extending a type via Plugin (I’ve done it for a field, but I’m a little hazy on how I would do it at the content type level)

**Comment by benfalk** [comment]
@dirtystylus Did you ever find a solution to stitch another schema as a plugin from inside Drupal?  I'm also looking into this and was wondering if you were ever able to uncover anything.

**Comment by dirtystylus** [comment]
@benfalk Not really — in the end we moved away from GraphQL for the project that prompted the question. We wrote our own API controllers since the products accessing the API had fairly rigid schema needs. If there was the potential need for more flexibility we would have probably explored further.
