### ISSUE TITLE
Custom query - To get current user

### ISSUE THREAD

**Issue by elistone** [drupal-graphql/graphql#649]
Could any one point me in the correct direction for creating a custom end point that would allow me to call something like `getCurrentUser`.

I am using simple oauth to authenticate and I get back access token & refresh but I need away to get the current user via GraphQL. Due to my permission settings at the moment when I run 'get all users' it is limited to the current user, but that will not work in the future for admin users who can view all account.

What the best way to go around this?

**Comment by nodeworks** [comment]
use the currentUserContext query

**Comment by joaogarin** [comment]
You can find an example in the docs : https://github.com/drupal-graphql/graphql/blob/8.x-3.x/doc/queries/readme.md#queries feel free to close if this addresses your issue ;)

**Comment by elistone** [comment]
Thanks, that should help.
