### ISSUE TITLE
Rename root operation type names to default names

### ISSUE THREAD

**Issue by mtodor** [drupal-graphql/graphql#650]
Currently, we are using custom root operation names. Following names are used:
- `QueryRoot`
- `MutationRoot`
- `SubscriptionRoot`

The GraphQL specification defines default names for root operations. `Default Root Operation Type Names` under [Root Operation Types](http://facebook.github.io/graphql/June2018/#sec-Root-Operation-Types).

The main problem is that custom root operation type names are not good supported by GraphQL Tools. For example, if you use `graphql-cli` to download schema for endpoint and then run `diff` between saved schema file and that endpoint, it will always throw an error, because loaded schema from file doesn't take in account custom root operation names. I have also experienced problems with other tools.

The workaround for us is custom `GraphQLSchema` plugin, but it would be better to change it in the module.

**Comment by fubhy** [comment]
Although the error is clearly with the "custom tooling" (because custom root type names are not invalid), I am fine with "fixing" this on our end. It won't hurt us.
