### ISSUE TITLE
Sort by expression

### ISSUE THREAD

**Issue by nodeworks** [drupal-graphql/graphql#654]
I've been needing to implement some natural sorting for certain entity columns and I came up with a simplistic implementation that (I think) can be possibly merged in with a pull request without issue if the need is there.

Since the only way to add an expression to an entity query in Drupal is to alter the query itself, I came up with a solution to tag the query if an expression exists on the sort, and then alter the query through an alter hook to add the expression sort.

Here's what I came up with:

New module file (one doesn't exist already): ```graphql_core.module```

```
<?php

/**
 * @file
 * GraphQL Core Module Functionality.
 */

/**
 * Implements hook_query_alter().
 */
function graphql_core_query_alter(Drupal\Core\Database\Query\AlterableInterface $query) {
  $is_graphql_expression_sort = $query->hasTag('graphql_sort_expression');
  if ($is_graphql_expression_sort) {
    $metadata = $query->getMetaData('sort_expressions');
    foreach ($metadata as $sort_expression) {
      $query->addExpression($sort_expression['expression']['expression'], $sort_expression['expression']['alias']);
      $query->orderBy($sort_expression['expression']['alias'], $sort_expression['direction']);
    }
  }
}
```
New InputType for EntityQuery: ```EntityQuerySortExpressionInput.php```

```
<?php

namespace Drupal\graphql_core\Plugin\GraphQL\InputTypes\EntityQuery;

use Drupal\graphql\Plugin\GraphQL\InputTypes\InputTypePluginBase;

/**
 * @GraphQLInputType(
 *   id = "entity_query_sort_expression_input",
 *   name = "EntityQuerySortExpressionInput",
 *   fields = {
 *     "expression" = "String",
 *     "alias" = "String!"
 *   }
 * )
 */
class EntityQuerySortExpressionInput extends InputTypePluginBase {

}
```

Update the EntityQuery: ```EntityQuery.php```

```
/**
   * Apply the specified sort directives to the query.
   *
   * @param \Drupal\Core\Entity\Query\QueryInterface $query
   *   The entity query object.
   * @param mixed $sort
   *   The sort definitions from the field arguments.
   *
   * @return \Drupal\Core\Entity\Query\QueryInterface
   *   The entity query object.
   */
  protected function applySort(QueryInterface $query, $sort) {
    if (!empty($sort) && is_array($sort)) {
      $expressions = [];
      foreach ($sort as $item) {
        if (isset($item['expression'])) {
          $query->addTag('graphql_sort_expression');
          $expressions[] = $item;
        }
        else {
          $direction = !empty($item['direction']) ? $item['direction'] : 'DESC';
          $query->sort($item['field'], $direction);
        }
      }

      $query->addMetaData('sort_expressions', $expressions);
    }

    return $query;
  }
```

Update the EntityQuerySortInput to allow expressions: ```EntityQuerySortInput.php ```

```
<?php

namespace Drupal\graphql_core\Plugin\GraphQL\InputTypes\EntityQuery;

use Drupal\graphql\Plugin\GraphQL\InputTypes\InputTypePluginBase;

/**
 * @GraphQLInputType(
 *   id = "entity_query_sort_input",
 *   name = "EntityQuerySortInput",
 *   fields = {
 *     "expression" = "EntityQuerySortExpressionInput",
 *     "field" = "String!",
 *     "direction" = {
 *       "type" = "SortOrder",
 *       "default" = "DESC"
 *     }
 *   }
 * )
 */
class EntityQuerySortInput extends InputTypePluginBase {

}
```

With this you can then add an expression sort like so:

```
query SomeQuery($filters: [EntityQueryFilterConditionInput]) {
  someQuery(limit: 100, offset: 0, filter: {
    conditions: $filters
  }, sort: [{ 
    field: "expression1", 
    direction: ASC, 
    expression: { 
      expression: "LENGTH(SUBSTRING_INDEX(natural_id, '-', 1))", 
      alias: "expression1" 
    } 
  },
  { 
    field: "expression2", 
    direction: ASC, 
    expression: { 
      expression: "CAST(SUBSTRING_INDEX(natural_id, '-', -1) as UNSIGNED)", 
      alias: "expression2" 
    } 
  }]) {
    ...
  }
}
```

**Comment by fubhy** [comment]
Your implementation approach (metadata and then query altering) sounds reasonable and is indeed probably the only way to achieve what you are after. I would not accept a pull request with this feature though, because I do think that this is a bit too much and too specific for our module. We already do too much imho (we will fix that in a next release with SDL based schemas). But that's why we made this all extendable: So that you can build this if needed. And your implementation actually looks good. 

One thing I noticed though (and you should definitely validate that it's not the case): You are currenlty NOT escaping the expression input. And I am not sure whether addExpression actually takes care of that for you or not. If not, your code basically enables sql query injection. Make sure that's not the case!

Thanks for commenting and offering to contribute this :-). Greatly appreciated.
