### ISSUE TITLE
Add hook_graphql_result_alter

### ISSUE THREAD

**Issue by mirhamzah** [drupal-graphql/graphql#656]
Add a hook hook_graphql_result_alter to let other modules overwrite result.

**Comment by fubhy** [comment]
Such a hook would contradict graphql in big parts. We do not intend to add the ability to alter the results through a hook (or event, for that matter). If you want to manipulate values in the response, you have to manipulate them at their origin - namely, the plugin / field that produces them.

**Comment by dspachos** [comment]
@fubhy and is there any way to create a custom field formatter plugin, and this plugin have affect in the value that is returned by a GraphQL query?
