### ISSUE TITLE
Not implementing hook_query_alter?

### ISSUE THREAD

**Issue by edouardgab** [drupal-graphql/graphql#657]
Hi!

I am currently in the process to make a lot of tests with Graphql to find out how to implement this. One thing that I am trying to understand is that if it is normal or not that a GraphQL query doesn't go through the hook_query_alter ?

Thanks!

Ed

**Comment by pmelab** [comment]
A GraphQL query has nothing to do with `hook_query_alter` since it's not an SQL query, but an invocation of several resolvers.

**Comment by edouardgab** [comment]
Ok that is interesting, thanks for the answer.

Is there any way to do something similar to this then? For example, I use the `hook_query_alter` to manage content access (a bit like domain entity access would do). This is not something that can be managed in each queries (even more in the scenario of a public API) but we need to make sure that a user only has access to the content related to him.

I understand that GraphQL is not a SQL query, but shouldn't it uses a logic similar to SQL queries to make sure query results are consistent over the different entry points/devices?

Thanks!

Ed

**Comment by pmelab** [comment]
Under the hood, GraphQL is just using the entity api. All Drupal access restrictions will just apply in GraphQL queries. But I don't think `hook_query_alter` is the right place to implement access control. This should be done with [`hook_entity_access`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_entity_access/8.6.x) or [`hook_node_access`](https://api.drupal.org/api/drupal/core%21modules%21node%21node.api.php/function/hook_node_access/8.6.x).

**Comment by edouardgab** [comment]
Unfortunately `hook_entity_access` is required but not enough in this scenario. Without a query_alter, each content I don't have access to simply returns null. It is a requirement to make sure a user will never have access to a content he shouldn't have. But here, we are talking to content that are in the same database but absolutely not shared across users. So when a user is querying his products, it should only get his products, not all products, and simply removing the access to the content.

This is how domain_entity implements it in D7 for example (I am moving from D7 to D8, I was using domain access, not anymore).

```php
/**
 * Implements hook_query_alter().
 *
 * Alter the enabled entities select query,
 * add domain access conditions.
 */
function domain_entity_query_alter(&$query) {
  // Check for ajax/admin and skip if permissions and situation call for it.
  if (
    (path_is_admin(current_path())
      && user_access('bypass domain access check for admin and ajax'))
    || (isset($_SERVER['HTTP_X_REQUESTED_WITH'])
      && !empty($_SERVER['HTTP_X_REQUESTED_WITH'])
      && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest' && user_access('bypass domain access check for admin and ajax'))
  ) {
    return;
  }
  // Check if user can bypass entity access via perm or variable.
  if (!variable_get('domain_entity_bypass_access_conditions', FALSE)
    && !user_access('bypass domain access check')
    // Checks the nescessary method is available on the query.
    && method_exists($query, 'getTables')
  ) {
    $tables = $query->getTables();
    $base_table_alias = key($tables);
    $base_table = $tables[$base_table_alias]['table'];

    // Have we to check access for this entity types.
    $domain_entity_base_tables = domain_entity_allowed_entity_types_base_tables();
    if (!in_array($base_table, array_keys($domain_entity_base_tables))) {
      return;
    }

    // This is an enabled domain entity,
    // prepare our custom access conditions.
    // Get the accessible domain id's by the current user, in the current path.
    $accessible_domain_ids = domain_entity_get_user_available_domains();
    // Show to all user the entities that are assigned to all domains,
    // add the joker domain entity value to the list of the domain id's.
    $accessible_domain_ids[] = DOMAIN_ENTITY_SEND_TO_ALL;
    // Get the entity_type and key for this base_table:
    $entity_type = $domain_entity_base_tables[$base_table]['entity type'];
    $entity_key = $domain_entity_base_tables[$base_table]['entity key'];
    // Get the field name for this entity:
    $field_instance = domain_entity_entity_field_instance($entity_type);
    $field_instance_name = $field_instance['name'];

    // Add our subquery condition:
    $domain_query = db_select('field_data_' . $field_instance_name, 'dom');
    $domain_query->where('dom.entity_id = ' . $base_table_alias . '.' . $entity_key);
    $domain_query->condition('dom.' . $field_instance_name . '_domain_id', $accessible_domain_ids, 'IN');
    $domain_query->fields('dom', array($field_instance_name . '_domain_id'));
    $query->exists($domain_query);
  }
}
```

**Comment by pmelab** [comment]
For nodes, that's what the node grant system ([`hook_node_grants`](https://api.drupal.org/api/drupal/core%21modules%21node%21node.api.php/function/hook_node_grants/8.6.x)) is there for. But this is not there for all entity types. There is an ongoing [issue](https://www.drupal.org/project/drupal/issues/777578) about that.

**Comment by edouardgab** [comment]
Ho I see. I wasn't aware of this. We are not using nodes at all so I didn't look into that.

Thanks!

Ed

**Comment by edouardgab** [comment]
If anyone comes around here at some point looking for info about `hook_query_alter`. I was completely wrong, GraphQL queries does go through the `hook_query_alter`. This was my mistake because of a caching issue. All good now :)
