### ISSUE TITLE
Mutation updating node adding new paragraph content

### ISSUE THREAD

**Issue by elistone** [drupal-graphql/graphql#664]
Hi,

I'm trying to create a mutation that will insert a new paragraph field into an existing node but I am having issues and cannot quite get it to work.

Here is what I have tried:

```
/**
 *
 * @GraphQLMutation(
 *   id = "add_new_paragraph",
 *   entity_type = "node",
 *   entity_bundle = "resource",
 *   secure = true,
 *   name = "addNewParagraph",
 *   type = "EntityCrudOutput!",
 *   arguments = {
 *     "id" = "String",
 *     "input" = "ParagraphInput"
 *   }
 * )
 */
class AddNewParagraph extends UpdateEntityBase {

  /**
   * {@inheritdoc}
   */
  protected function extractEntityInput($value, array $args, ResolveContext $context, ResolveInfo $info) {

    $paragraph = Paragraph::create(['type' => 'details']);
    $paragraph->set('field_name', $args['input']['name']);
    $paragraph->set('field_count', $args['input']['count']);
    $paragraph->set('field_description', $args['input']['description']);
    $paragraph->isNew();
    $paragraph->save();

    return [
      'field_details' => $paragraph->id()
    ];
  }
}
```

But it was giving this warning and no information gets added:

> Warning: Illegal string offset 'target_id' in Drupal\entity_reference_revisions\Plugin\DataType\EntityReferenceRevisions->setValue()

**Comment by fubhy** [comment]
Try setting a breakpoint here: https://github.com/drupal-graphql/graphql/blob/188be525a007f385a3d3c4f8d2900b62a0150a5f/modules/graphql_core/src/Plugin/GraphQL/Mutations/Entity/UpdateEntityBase.php#L89

You are probably using an invalid format for the field input.

So field_details should probably be ```'field_details' => ['target_id' => $paragraph->id()]```

**Comment by elistone** [comment]
Hi @fubhy I have been trying this recently without any success.

It currently looks like the following:

```
/**
 *
 * @GraphQLMutation(
 *   id = "add_new_paragraph",
 *   entity_type = "node",
 *   entity_bundle = "resource",
 *   secure = true,
 *   name = "addNewParagraph",
 *   type = "EntityCrudOutput!",
 *   arguments = {
 *     "id" = "String",
 *     "input" = "ParagraphInput"
 *   }
 * )
 */
class AddNewParagraph extends UpdateEntityBase {

  /**
   * {@inheritdoc}
   */
  protected function extractEntityInput($value, array $args, ResolveContext $context, ResolveInfo $info) {

    $paragraph = Paragraph::create(['type' => 'details']);
    $paragraph->set('field_name', $args['input']['name']);
    $paragraph->set('field_count', $args['input']['count']);
    $paragraph->set('field_description', $args['input']['description']);
    $paragraph->isNew();
    $paragraph->save();

    return [
      'field_details' => $paragraph->id(),
      'target_revision_id' => $paragraph->getRevisionId(),
    ];
  }
}
```

I am getting the following returned from explorer:

```
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addNewParagraph"
      ]
    }
  ],
  "data": []
}
```

With a warning in the drupal logs:

> Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->getFromStaticCache() (line 139 of C:\IE\Acquia\project\core\lib\Drupal\Core\Entity\EntityStorageBase.php) 

I have been trying break points but nothing is jumping out at me as problem.
