### ISSUE TITLE
How to load paraghraph entity

### ISSUE THREAD

**Issue by rfnbnkr** [drupal-graphql/graphql#676]
Hi. i have a content type with "artist" and i have a paragraph type with "album" name. in album i have two field 1. name 2. release date. 
i create a field with "field_album"  name in "artist" content type that this field reference to paragraph. now i want write a query that show artist name and all albums with name and release date.
I create this query to load artist but i cant load paragraph.

```
query{
  nodeQuery(filter: {conditions:[{field:"title",value: ["artistname"], operator: EQUAL}]}){
    count
    entities {
      ...on NodeArtist{
        nid
        title
      }
    }
  }
}
```

**Comment by fubhy** [comment]
```
query{
  nodeQuery(filter: {conditions:[{field:"title",value: ["artistname"], operator: EQUAL}]}){
    count
    entities {
      ...on NodeArtist{
        nid
        title
        fieldAlbum {
          ... on ParagraphAlbum {
            fieldName
            fieldReleaseDate
          }
        }
      }
    }
  }
}
```

**Comment by rfnbnkr** [comment]
Thanks fubhy. this solved my problem
