### ISSUE TITLE
Several test classes missing @group annotation; causing PHP error on testing page

### ISSUE THREAD

**Issue by chrisferagotti** [drupal-graphql/graphql#678]
The following files are missing the @group annotation:

modules/graphql_core/tests/src/Kernel/Entity/BundleLessEntityTest.php
modules/graphql_core/tests/src/Kernel/Entity/EntityRevisionsTest.php
tests/src/Kernel/Extension/ResolveContextTest.php
tests/src/Kernel/Framework/InvalidPayloadTest.php
tests/src/Kernel/Framework/LanguageContextTest.php

**Comment by rthideaway** [comment]
Have the same problem. Wrote some test for our module which uses graphql as dependency, and the test is failing on Drupal CI due to missing groups. See the build:
https://dispatcher.drupalci.org/job/drupal_contrib/337738/console

**Comment by rthideaway** [comment]
My apologies! Just noticed this is already covered in dev version -> http://cgit.drupalcode.org/graphql/commit/?id=ab4f496087a48ad4f2ef2315b73254b9a395b731
