### ISSUE TITLE
Schema Download / Export for PHPStorm Integration

### ISSUE THREAD

**Issue by ayalon** [drupal-graphql/graphql#680]
Hi
Is it possible to somehow access the schema on an URL or to download the schema?
I would love to integrate the schema with PHPStorm and I'm curious if someone has done something similar.

**Comment by fubhy** [comment]
There is no such plugin for PHPStorm as far as I am aware. You can ofc generate a SDL Schema file from the introspection query using https://graphql.org/graphql-js/utilities/#printschema - And then there are plugins for e.g. Visual Studio Code that do some fun stuff with that: https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode
