### ISSUE TITLE
File system discovery does not work

### ISSUE THREAD

**Issue by ayalon** [drupal-graphql/graphql#681]
I created several GraphQL files, merged them into a valid query.json that can also be successfully uploaded.

I put the JSON file into folder on my installation and set the path according to the documentation:
https://www.drupal.org/docs/8/modules/graphql/query-maps

Unluckily the file never gets imported. Clearing the cache does not help. How is this intended to work? I set several breakpoints in the discovery code but it never was entered.

**Comment by fubhy** [comment]
Setting a breakpoint here: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/GraphQL/QueryProvider/QueryProvider.php#L27 should give you clues.

**Comment by ayalon** [comment]
This was exactly where I set a breakpoint but this line of code was never reached.
I visited all routed of graphQL, I deleted caches several times but it never was executed. The function "addProvider" is called using the service tag. But not the function above.

**Comment by ayalon** [comment]
Still no clue, how to autodiscover my json file.

**Comment by fubhy** [comment]
Then check here https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/GraphQL/Execution/QueryProcessor.php#L186

**Comment by fubhy** [comment]
Did that help?

**Comment by ayalon** [comment]
Unfortunatly not. I'm not able to trigger the breakpoint. What route / url or what action has to be taken, to get to that point. What I need is an information how to trigger the import.

**Comment by fubhy** [comment]
The import happens the first time the API is called with a previously unknown query id. Then the provided file system path is crawled to find all query map files there. Setting a breakpoint at this line https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/GraphQL/Execution/QueryProcessor.php#L186 HAS to trigger the xdebug debugger when you run a graphql query. There is no way for it to NOT reach that point unless it blows up somewhere before. This is before the query is actually evaluated and always comes by this point.

**Comment by ayalon** [comment]
Now I understood how trigger it. If you have an empty query map, it's not so obvious to send a nonsense query just to trigger the import. But now its clear. Thx.

**Comment by fubhy** [comment]
The key is that there is NO import. It's just a cached lookup on demand.
