### ISSUE TITLE
Image style with dashes cause an error:

### ISSUE THREAD

**Issue by FatherShawn** [drupal-graphql/graphql#682]
Similar to #461, I have the following error in the console of Explorer:
 [Show/hide message details.] Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "LANDSCAPE-LARGE_1280_1_5X" does not.

`landscape-large_1280_1_5x` is a workable image style name to Drupal.  Does graphql disallow the dash in a name?

**Comment by FatherShawn** [comment]
Renaming all image styles with dashes clears the error.

**Comment by fubhy** [comment]
Thanks! Good catch.

Fixed in https://github.com/drupal-graphql/graphql/pull/683
