### ISSUE TITLE
RE: Mutation updating node adding new paragraph content

### ISSUE THREAD

**Issue by elistone** [drupal-graphql/graphql#689]
Hi @fubhy I have been trying this recently without any success.

It currently looks like the following:

```
/**
 *
 * @GraphQLMutation(
 *   id = "add_new_paragraph",
 *   entity_type = "node",
 *   entity_bundle = "resource",
 *   secure = true,
 *   name = "addNewParagraph",
 *   type = "EntityCrudOutput!",
 *   arguments = {
 *     "id" = "String",
 *     "input" = "ParagraphInput"
 *   }
 * )
 */
class AddNewParagraph extends UpdateEntityBase {

  /**
   * {@inheritdoc}
   */
  protected function extractEntityInput($value, array $args, ResolveContext $context, ResolveInfo $info) {

    $paragraph = Paragraph::create(['type' => 'details']);
    $paragraph->set('field_name', $args['input']['name']);
    $paragraph->set('field_count', $args['input']['count']);
    $paragraph->set('field_description', $args['input']['description']);
    $paragraph->isNew();
    $paragraph->save();

    return [
      'field_details' => $paragraph->id(),
      'target_revision_id' => $paragraph->getRevisionId(),
    ];
  }
}
```

I am getting the following returned from explorer:

```
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addNewParagraph"
      ]
    }
  ],
  "data": []
}
```

With a warning in the drupal logs:

> Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->getFromStaticCache() (line 139 of C:\IE\Acquia\project\core\lib\Drupal\Core\Entity\EntityStorageBase.php) 

I have been trying break points but nothing is jumping out at me as problem.

**Comment by fubhy** [comment]
That error is caused by an ::load() or ::loadMultiple() happening somewhere. Not by the code you pasted here. Please set a breakpoint in getFromStaticCache() and figure out what is calling the entity load and where.

**Comment by fubhy** [comment]
Did you find the root cause of the issue? Let me know if I can help further (feel free to re-open).

**Comment by elistone** [comment]
@fubhy sorry for the slow reply, been a while to get back working on this. Turns out as you rightly said it was nothing todo with the GraphQL code. Instead it is something wrong with one of the custom modules on this site that does a lot of data processing when a node is saved. Just thought I would let you know.

**Comment by urbgimtam** [comment]
As its my first time building mutations for paragraphs, and I had a hard time finding documentation, I ended up here, which help big time. In my case, however, I had to add multiple Paragraph items, and found out that using the above code caused an issue with the database references in the entity_revisions. 

I solved it by passing the $paragraphs object directly in the "field_details". Here's my take on the above code, for future reference:

`
    use Drupal\paragraphs\Entity\Paragraph;

    /**
     *
     * @GraphQLMutation(
     *   id = "create_new_paragraph",
     *   entity_type = "node",
     *   entity_bundle = "articles",
     *   secure = true,
     *   name = "createNewParagraph",
     *   type = "EntityCrudOutput!",
     *   arguments = {
     *     "id" = "String",
     *     "input" = "ParagraphInput"
     *   }
     * )
     */
    class createNewParagraph extends CreateEntityBase {

      /**
       * {@inheritdoc}
       */
      protected function extractEntityInput($value, array $args, ResolveContext $context, ResolveInfo $info) {

        $paragraph = Paragraph::create(['type' => 'details']);
        $paragraph->set('field_name', $args['input']['name']);
        $paragraph->set('field_count', $args['input']['count']);
        $paragraph->set('field_description', $args['input']['description']);
        $paragraph->isNew();
        $paragraph->save();

        return [
          'field_details' => $paragraph  //the full object contains all necessary details
        ];
      }
    }`


For multiple (unlimited) Paragraphs subitems, here's what I ended up with:

`      use Drupal\paragraphs\Entity\Paragraph;

    /**
     *
     * @GraphQLMutation(
     *   id = "create_new_paragraph",
     *   entity_type = "node",
     *   entity_bundle = "articles",
     *   secure = true,
     *   name = "createNewParagraph",
     *   type = "EntityCrudOutput!",
     *   arguments = {
     *     "id" = "String",
     *     "input" = "[ParagraphInput]"
     *   }
     * )
     */

    class createNewParagraph extends CreateEntityBase {

    /**
     * {@inheritdoc}
     */
     protected function extractEntityInput($value, array $args, ResolveContext $context, ResolveInfo $info) {


        // Loop to catch array
        // Note that 'input' is an array of objects 
        $i=0;
        foreach ($args['input] as $items) {
            $paragraph[$i] = Paragraph::create(['type' => 'details']);
            $paragraph[$i]->set('field_name', $items['name']);
            $paragraph[$i]->set('field_count', $items['count']);
            $paragraph[$i]->set('field_description', $items['description']);
            $paragraph[$i]->isNew();
            $paragraph[$i]->save();
            $i++;
         }

        return ['field_details' => $paragraph  //the full object contains all necessary details];
       }
    }`

This helped me out tremendously. Hope it helps someone else.
