### ISSUE TITLE
webonyx/graphql-php component not found

### ISSUE THREAD

**Issue by pitxels** [drupal-graphql/graphql#690]
Hello,

Would someone be so kind of giving instructions on how to install dependencies without composer, drush, or a cli at all. There are people that don't have the ideal scenarios you guys have.

Thanks.

**Comment by pitxels** [comment]
Ok I guess I will have to install a local drupal in my pc and use composer there to see where does it install the library and then do the process manually in my shared server, and only because someone thinks his way is the only way acceptable.

**Comment by fubhy** [comment]
Yeah.

**Comment by pitxels** [comment]
Please allow me to share my findings before shooting down the issue. I think people have the right to install this module in other ways. Thanks

**Comment by fubhy** [comment]
The alternative you described (install locally, download dependencies with composer to your machine, then upload) is correct.

**Comment by markosiilak** [comment]
Easiest way is with composer run in terminal/console on Drupal root 
_composer require webonyx/graphql-php_
After this flush all cache in Drupal admin.

**Comment by laurencefass** [comment]
this failed on my installation.

composer require webonyx/graphql-php
No composer.json in current directory, do you want to use the one at /var/www/html? [Y,n]? y
    1/2:        https://packages.drupal.org/8/drupal/provider-2019-1$444006229832dbbd3f664d2bccb942c0e48c94e31e4cc927840f353d128e0078.json
    2/2:        https://packages.drupal.org/8/drupal/provider-2018-3$967a689b59b726aa04bc58841d28374e39712d14e669a5f6cebd2dd1adc33912.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
    1/3:        http://repo.packagist.org/p/provider-latest$3c1cc5ec6702fcb9b2d56c4852a8e351ad827479ca646cb3c0ca4f04a0dc1002.json
    2/3:        http://repo.packagist.org/p/provider-2019-01$abe45699516efa7f6c74f4b84e25ee4504bdd12ca41ec809292dd9527ff38234.json
    3/3:        http://repo.packagist.org/p/provider-2017$13043c17c67b389a8074b1d1fec335c6f56323160b412c948aafeec388b051e3.json    Finished: success: 3, skipped: 0, failure: 0, total: 3
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^0.13.0 for webonyx/graphql-php
./composer.json has been updated
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/graphql 3.0.0-rc2 requires webonyx/graphql-php ^0.12.5 -> satisfiable by webonyx/graphql-php[0.12.x-dev].
    - drupal/graphql 3.0.0-rc2 requires webonyx/graphql-php ^0.12.5 -> satisfiable by webonyx/graphql-php[0.12.x-dev].
    - drupal/graphql 3.0.0-rc2 requires webonyx/graphql-php ^0.12.5 -> satisfiable by webonyx/graphql-php[0.12.x-dev].
    - Can only install one of: webonyx/graphql-php[v0.13.0, 0.12.x-dev].
    - Installation request for webonyx/graphql-php ^0.13.0 -> satisfiable by webonyx/graphql-php[v0.13.0].
    - Installation request for drupal/graphql (locked at 3.0.0-rc2, required as @dev) -> satisfiable by drupal/graphql[3.0.0-rc2].

Installation failed, reverting ./composer.json to its original content.

**Comment by laurencefass** [comment]
worked with @dev version... remember to flush cache.

**Comment by Milindmtg** [comment]
> 
> 
> Easiest way is with composer run in terminal/console on Drupal root
> _composer require webonyx/graphql-php_
> After this flush all cache in Drupal admin.

I have run the command and cleared the cache
Still I am getting the same error "webonyx/graphql-php component not found"
Please help.

**Comment by bastianhilton** [comment]
as of 3/6/2020 i'm receiving the same issue on Drupal 8.6.3 and i have the GraphQL plugin
