### ISSUE TITLE
Disable redirects on the /graphql route

### ISSUE THREAD

**Issue by luksak** [drupal-graphql/graphql#696]
I am currently working on a multilingual site and need to have the "URL" language detection enabled for the backend to work properly.

Having this enabled redirects the `/graphql` URLs to eg. `/en/graphql`. This is not what I want since I handle the languages in the contexts of the GraphQL queries. Should we disable those redirects?

**Comment by pmelab** [comment]
Does the prefixed path still work? We know of some cases where language is handled on an endpoint level by using prefixed paths.

**Comment by pmelab** [comment]
Tested and merged! Thanks!
