### ISSUE TITLE
Mutation - Creating comment entity

### ISSUE THREAD

**Issue by ratvas** [drupal-graphql/graphql#698]
I'm struggling to create comment(s). Plugin is created like it's described in examples for Article creation. (I've tried to create article, that works as well). I am not sure what to put for entity_type and entity_bundle as "comment" doesn't work or maybe problem isn't there? I am getting "Internal server error" message on GraphQL explorer and "Call to a member function get() on null" in log.

**Comment by LeStatV** [comment]
```
/**
 * Simple mutation for creating a new comment.
 *
 * @GraphQLMutation(
 *   id = "create_comment",
 *   entity_type = "comment",
 *   entity_bundle = "",
 *   name = "createComment",
 *   type = "EntityCrudOutput!",
 *   arguments = {
 *     "input" = "CommentInput"
 *   }
 * )
 */
```

Here is an example, which works for us. As comment entity have no bundles, entity_bundle is empty.
