### ISSUE TITLE
GraphQL Entity Definitions

### ISSUE THREAD

**Issue by nodeworks** [drupal-graphql/graphql#700]
Hey all,

Wanted to reach out and get feedback on a new module utilizing Drupal GraphQL:

https://www.drupal.org/project/graphql_entity_definitions

Basically the point is to expose content entity definitions. The use case I currently have for this is automatically building forms based on entity fields and settings. I'm sure there are many other use cases and i'd love to hear them.

I realized that this wouldn't be a good candidate to merge into the Drupal GraphQL core module since it adds overhead. Anyway, would love some feedback if any!

Thanks.

**Comment by joaogarin** [comment]
@nodeworks this is great will definitely be giving it a try as I have the same use case right now coming up on a new project ;) I would gladly also help with documentation as I go and try the module out =)

**Comment by lucasconstantino** [comment]
@nodeworks awesome work dude... at our company we are doing some great stuff related to GraphQL and Drupal, we'll sure have a look at your project and perhaps discuss how to push it forward together ;)

**Comment by joaogarin** [comment]
I think would be really great to push this conversation to slack and maybe discuss how cooperation can be done on this front, my company would also really be super interested in pushing this forward = ) its a big use case for us also

**Comment by pmelab** [comment]
Added this to the related projects section in the main README and closed the issue. Thanks!
