### ISSUE TITLE
Diverging commits between drupal git repo and github repo

### ISSUE THREAD

**Issue by cenoura** [drupal-graphql/graphql#704]
Hello,

Just to give some context: at the moment, we're using the GraphQL module - through composer approach - that points to the `8.x-3.0-rc2` tag.
So, there are some issues that have been resolved after that on the Github repo and some on the Drupal repo.
As the specific issue we're facing now is fixed on the GitHub side and I haven't found the fix on Drupal side, I would like to know if there's some kind of automatically commit syncing between repos and/or what approach should I use to make it available on the Drupal side.

If you need any other info, please let me know and I'll be glad to contribute :smile:

**Comment by fubhy** [comment]
Hey @cenoura,

Sorry, I just pushed the latest 8.x-3.x version to d.o (commit # ffd4845).

**Comment by fubhy** [comment]
> I would like to know if there's some kind of automatically commit syncing between repos and/or what approach should I use to make it available on the Drupal side.

No, we just manually push to both repos currently.
