### ISSUE TITLE
jsonapi 2.x and jsonapi_extras 3.x break graphql  8.x-3.0-rc2

### ISSUE THREAD

**Issue by bisonbleu** [drupal-graphql/graphql#708]
I installed **jsonapi** & **jsonapi_extras** to play around with Gatsby. I was not aware of the recent releases (jsonapi, jsonapi_extras). Seeing numerous issues and/or discrepancies (between Gatsby's GraphiQL and graphql.module) I thought the issues I was seeing in **GraphiQL** & Gatsby were related to jsonapi 2.x. So I thought that downgrading to jsonapi 8.x-1.24 and jsonapi_extras 8.x-2.x would fix these issues.

For example with jsonapi 2.x installed on the drupal website the body field is not available in the following query:

```
query {
  allNodeArticle {
    edges {
      node {
        id
        title
        body {
          value
          format
          processed
          summary
        }
      }
    }
  }
}
```

**Comment by bisonbleu** [comment]
Downgrading jsonapi did not fix anything simply because that was not the issue.

The issue I was seeing stemmed from the fact that I was mixing and confusing the 2 instances of GraphiQL, namely the instance that is built in Gatsby and the other instance that comes with the Drupal GraphQL module.

They don't work exactly the same and in any case you don't use them for the same reasons; the first instance is a Gatsby tool to explore existing schemas, the second instance (the module) is a Drupal tool to build and extend schemas. At least, that's how I understand it.

Please correct me if I'm wrong. Otherwise this issue is good to close.

**Comment by urbgimtam** [comment]
I also have both installed and didn't felt any problem in my installation.

**Comment by fubhy** [comment]
> They don't work exactly the same and in any case you don't use them for the same reasons; the first instance is a Gatsby tool to explore existing schemas, the second instance (the module) is a Drupal tool to build and extend schemas. At least, that's how I understand it.
> 
> Please correct me if I'm wrong. Otherwise this issue is good to close.

Correct. JSON API and GraphQL are two separate modules and the GraphiQL interface from Gatsby points at JSON API.
