### ISSUE TITLE
Call to undefined method Drupal\\Core\\Routing\\LocalRedirectResponse::getResult()

### ISSUE THREAD

**Issue by sebas5384** [drupal-graphql/graphql#709]
Hi!

we are having an internal server error on some queries like `currentUserContext` when user is anonymous.

`Call to undefined method Drupal\\Core\\Routing\\LocalRedirectResponse::getResult()`

I xdebug it and this is the line which is firing the exception:
https://github.com/drupal-graphql/graphql/blob/33a905afdce6cb14808044ac3fd53588f5ed03e4/src/GraphQL/Buffers/SubRequestBuffer.php#L119

Maybe it's related to this issue https://github.com/drupal-graphql/graphql/pull/705

Should we check if the method `getResult()` exist? help? 😄

**Comment by NickDJM** [comment]
I've been getting this error as well, but for all users; not just anonymous users.

**Comment by sebas5384** [comment]
@NickDJM do you have a redirect somewhere? I can't figure it out why we are getting a local redirect response on graphql requests which aren't even route related.

**Comment by fubhy** [comment]
Fields like "currentUserContext" / "nodeContext" ARE route related. They basically run a subrequest on the current  context's route (e.g. within a "node" object (e.g. nodeById(id: 5) { nodeContext { ... } }) it runs subrequest on the node's canonical entity url and then fetches the "current node" in that context, which obviously is "node 5" again (so doesn't make much sense in this example but you get the idea). So if there is then a redirect iwthin that route, it seems we are currently not handling them correctly. I think what we should be doing is to then recursively resolve the redirect until we reach a "non-redirect" response.

**Comment by sebas5384** [comment]
@fubhy I implemented a recursive handler like you suggested:

```php
/** @var \Drupal\graphql\GraphQL\Buffers\SubRequestResponse $response */
    $response = $this->httpKernel->handle($request, HttpKernelInterface::SUB_REQUEST);

    while ($response instanceof \Symfony\Component\HttpFoundation\RedirectResponse) {
      $response = $this->httpKernel->handle(Request::create($response->getTargetUrl()), HttpKernelInterface::SUB_REQUEST);
    }
```

but now I'm having a different error which is:
```
Call to undefined method Drupal\\Core\\Render\\HtmlResponse::getResult()
```
and this is because the final response is the homepage's html.

This issue is no longer active for me because we had as a front page url `/user` which redirect to `/user/login` when the user is anonymous. After changing the front page url to `/user/login` it got solved.

Even though GraphQL shouldn't have a problem with redirects of any kind I'm guessing this is an edge case.

**Comment by fubhy** [comment]
Does it resolve the issue?

**Comment by sebas5384** [comment]
@fubhy not yet, since it throws a new error
```
Call to undefined method Drupal\\Core\\Render\\HtmlResponse::getResult()
```
maybe the new Request I'm creating is incomplete.

**Comment by sebas5384** [comment]
Actually when the response has a redirect is not worth evaluating with `getResult` since it doesn't get resolved as a graphql result. The `resolveBufferArray()` should return anything if the response is a redirect?

**Comment by NickDJM** [comment]
@sebas5384 Ah I also was using /user as the home page. Once I changed it to something else the query started to work just fine.

**Comment by fubhy** [comment]
> Actually when the response has a redirect is not worth evaluating with `getResult` since it doesn't get resolved as a graphql result. The `resolveBufferArray()` should return anything if the response is a redirect?

You may be right there. I think we want to check if the response is instanceof SubrequestResponse (https://github.com/drupal-graphql/graphql/blob/188be525a007f385a3d3c4f8d2900b62a0150a5f/src/GraphQL/Buffers/SubRequestResponse.php) and otherwise just return NULL.

**Comment by fubhy** [comment]
Sorry, misclick. Can you open a Pull Request that adds this check?

**Comment by fubhy** [comment]
This pull request should fix it. Please give it a try! #716

**Comment by sebas5384** [comment]
For anyone who got to this issue and needs to fix this on `rc2` here's a patch.
[graphql-fix_redirect-r2.txt](https://github.com/drupal-graphql/graphql/files/2792885/graphql-fix_redirect-r2.txt)

**Comment by akshitggrwl** [comment]
I applied the above patch but then i get these errors

> Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: No route found for the specified format _graphql_subrequest. Supported formats: html. in Drupal\Core\Routing\RequestFormatRouteFilter->filter() (line 65 of /var/www/html/drupal/web/core/lib/Drupal/Core/Routing/RequestFormatRouteFilter.php).

and 

$current is undefined in createRequest method
