### ISSUE TITLE
Error using nested fields in entity query filtering

### ISSUE THREAD

**Issue by walter-0** [drupal-graphql/graphql#710]
I'm trying to query a node by its url path, which is formatted as `/YYYY/MM` but I'm having trouble accessing the path field, which is nested under entityUrl. I'm able to query using non-nested fields such as title, but I get the error `Call to a member function getColumns() on boolean` when I try to filter by a nested field.

This doesn't work
```
{
  nodeQuery(sort: [{field: "nid", direction: DESC}], filter: {conditions: [{field: "type", value: "issue"}, {field: "entityUrl.path", value: "/2018/11"}]}) {
    entities {
      ... on NodeIssue {
        nid
        title
        entityUrl {
          path
        }
      }
    }
  }
}
```
and returns this

```
{
  "errors": [
    {
      "debugMessage": "Call to a member function getColumns() on boolean",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "nodeQuery",
        "entities"
      ]
    }
  ],
  "data": {
    "nodeQuery": {
      "entities": null
    }
  }
}
```

This does work

```
{
  nodeQuery(sort: [{field: "nid", direction: DESC}], filter: {conditions: [{field: "type", value: "issue"}, {field: "title", value: "November-December 2018"}]}) {
    entities {
      ... on NodeIssue {
        nid
        title
        entityUrl {
          path
        }
      }
    }
  }
}
```

returns

```
{
  "data": {
    "nodeQuery": {
      "entities": [
        {
          "nid": 54094,
          "title": "November-December 2018",
          "entityUrl": {
            "path": "/2018/11"
          }
        }
      ]
    }
  }
}
```

**Comment by urbgimtam** [comment]
Aren't you missing a conjunction? And defined operators?
It kind of the operator of the conditions.

Something like:

```
{
  nodeQuery( sort: { field: "nid", direction: DESC }],
         filter: {
            conjunction: AND,
            conditions: [
                {operator: EQUAL, field: "type", value: "issue"}, 
                {operator: LIKE, field: "entityUrl.path", value: "/2018/11"}]
           }) {
    entities {
      ... on NodeIssue {
        nid
        title
        entityUrl {
          path
        }
      }
    }
  }
}

```

**Comment by urbgimtam** [comment]
You can also refer to this documentation, its the most current.

[https://github.com/drupal-graphql/graphql/blob/8.x-3.x/doc/queries/filters.md
](https://github.com/drupal-graphql/graphql/blob/8.x-3.x/doc/queries/filters.md
)

**Comment by walter-0** [comment]
I used the conjunction and removed the sort and still get the same error.
```
{
  nodeQuery(filter: {
    conjunction: AND,
    conditions: [
      {operator: EQUAL, field: "type", value: "issue"}, 
      {operator: LIKE, field: "entityUrl.path", value: "/2018/11"}
    ]
  }) {
    entities {
      ... on NodeIssue {
        nid
        title
        entityUrl {
          path
        }
      }
    }
  }
}
```
returns 
```
{
  "errors": [
    {
      "debugMessage": "Call to a member function getColumns() on boolean",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 9,
          "column": 5
        }
      ],
      "path": [
        "nodeQuery",
        "entities"
      ]
    }
  ],
  "data": {
    "nodeQuery": {
      "entities": null
    }
  }
}
```

**Comment by akshitggrwl** [comment]
You can only query the fields available on the entity. 
entityUrl is not a field on entity but a graphql field.

And as the documentation says
> this will be transformed into an EntityQuery and so it easily relate this to how that query will end up like.

**Comment by walter-0** [comment]
@akshitggrwl So you're saying there currently isn't a way to query a GraphQL field?

**Comment by akshitggrwl** [comment]
Not in entity query. You can create a custom query though. 
Checkout the query code at Drupal\graphql_core\Plugin\GraphQL\Fields\EntityQuery::buildFilterConditions()

You can extend this code to create your own query that can handle your path field.

PS: You can use alias manager service to lookup the internal path and get the node id.

**Comment by walter-0** [comment]
I'm not exactly sure how to create a custom query, but if that's the solution, I'll figure out how to do it.

**Comment by walter-0** [comment]
My answer was in the docs: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/doc/queries/routes.md. I can query a route directly.

```
query {
  route(path: "/2018/11") {
    ...on EntityCanonicalUrl {
      nodeContext {
        nid
        title
        entityType
      }
    }
  }
}
```
returns
```
{
  "data": {
    "route": {
      "nodeContext": {
        "nid": 54094,
        "title": "November-December 2018",
        "entityType": "node"
      }
    }
  }
}
```
