### ISSUE TITLE
How to retrieve 'plain text' value of a text field?

### ISSUE THREAD

**Issue by urbgimtam** [drupal-graphql/graphql#711]
When querying text fields, the object returned includes 'value', 'format' and 'processed' (plus 'summary' and 'summaryProcessed' if summary is suported on the field).

But the values of 'value' and 'processed' are very similar. 

This may not be a bug, but shouldn't the 'value' be a 'plain text' version of the content? 
Or is 'value' the raw value that was stored and the 'processed' is the text processed with the text format rules it was saved?
If it's the later, its not that usable, I think, as most visitors interface write the text in the final format already.  

And then, how can we retrieve a 'plain text' format of a field populated with 'rich_text' format, for example? This is something that Views can do when defining a field to be displayed. 

Anyway, thanks for all the hard work on this module, its definitely changing the way we can interface with Drupal 👍

**Comment by pmelab** [comment]
Hi! Sorry for the late response. GraphQL doesn't handle these properties at all. They come from Drupal itself and are picked up automatically. `value` is as you already guessed the raw input data, and `processed` the one with text filters applied. I assume *"Plain text"* would be something without any markup. Drupal doesn't provide this out of the box. But there would be multiple ways to achieve that.

1. Add a computed field property to rich text fields that filters the text and outputs plain text. GraphQL will just pick it up.
2. Add a GraphQL field to the rich text field types that does the same.
3. If you don't need the "processed" output with HTML, you could just configure the text processors to filter everything. Then `value` will contain all HTML and `processed` plain text.
