### ISSUE TITLE
Relay and schema.graphql

### ISSUE THREAD

**Issue by neurotic** [drupal-graphql/graphql#719]
Hi,

there somewhere exposed the schema.graphql to run the relay compiler?

Or i need to create it manualy?

thanks!

**Comment by fubhy** [comment]
You need to run an introspection query against the API endpoint for that.

**Comment by neurotic** [comment]
Thanks,

I finally used GraphQL-cli https://github.com/graphql-cli/graphql-cli, it makes the introspection query very simple

**Comment by drubb** [comment]
@neurotic Did it work for you using the GraphQL CLI? For me the generated schema seems to throw multiple syntax errors. Example from schema.graphql:

```
  """The custom block ID."""
  id: Int

  """The custom block UUID."""
  uuid: String


  """The revision ID."""
  revisionId: Int

```
I'm using the GraphQL JS plugin for PhpStorm, and it doesn't accept this format, especially the strings/comments:

Error:(32, 3) Syntax Error GraphQL (32:3) Expected Name, found String

Thanks a lot!

**Comment by neurotic** [comment]
I had another error with relay compiler but i fixed it with this:
https://stackoverflow.com/questions/49965663/expected-undefined-to-be-a-graphql-leaf-type

But i'm finally using apollo client instead relay.
