### ISSUE TITLE
Query Fields with No Results Causes Error

### ISSUE THREAD

**Issue by skp3zl** [drupal-graphql/graphql#721]
Since query field results are [required](https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityReference/EntityReferenceQuery.php#L14), when no results are returned, due to an empty field, filters, etc., an error is thrown, e.g: 

> Cannot return null for non-nullable field User.queryFieldTeams.

Expected an empty array of entities and count of 0 returned [here](https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityReference/EntityReferenceQuery.php#L51)

**Comment by jayza** [comment]
I'm running into the same issue, does anyone have a patch for this?
