### ISSUE TITLE
How to query entity references?

### ISSUE THREAD

**Issue by Firebrand** [drupal-graphql/graphql#723]
Hi guys. I have a content type (ex. bookshelf) that nests other content types (ex. books) via entity reference. How do I query for this using the GraphQL module? How do I get a bookshelf and all its books?

Thanks so much!

**Comment by ebitsdev** [comment]
Hello @Firebrand,

I just created two content types Author and Book, where I can have multiple books referenced under an author or vice versa.

I was able to get the books per author by doing the following:

```
{
  nodeQuery(filter: {conditions: [{operator: EQUAL, field: "type", value: ["author"]}]}) {
    entities {
      ... on NodeAuthor {
        title
        nid
        fieldBooks {
          entity {
            ... on NodeBook {
              title
              entityBundle
            }
          }
        }
      }
    }
  }
}
```
Let me know if this helps you. I got inspiration from the documentation located at: [Drupal GraphQL Module Documentation](https://github.com/drupal-graphql/graphql/blob/8.x-3.x/doc/queries/filters.md).

Thanks,

**Comment by joaogarin** [comment]
Yeap this query does look like something that would work. Normally entity references have this "entity" property inside them and you should use fragments "... on NodeBundle" to get the fields inside that entity..this would work as well with taxonomy or other things that are not necessarily nodes. I recommend using graphiql (in /graphql/explorer) to test some of these out as it will autocomplete / suggest things you can query for. As mentioned by @ebitsdev   the docs https://github.com/drupal-graphql/graphql/tree/8.x-3.x/doc have some info

**Comment by Firebrand** [comment]
@ebitsdev  @joaogarin   You guys rock. That worked like a charm.  I'm going to try to figure out mutations (create, update, delete) now on that same type of structure. I'll be back for follow-up questions if I have any trouble.

**Comment by ebitsdev** [comment]
Thanks @Firebrand. It may be better to close this question since it worked for you. You can still ask a new question when necessary.

**Comment by Firebrand** [comment]
Cheers. Closed
