### ISSUE TITLE
Field query on entity reference doesnt sort after field delta.

### ISSUE THREAD

**Issue by jayza** [drupal-graphql/graphql#729]
I'm encountering an issue where EntityReference queries don't come out sorted after the delta on the field.

I'm using the following field query.
```
...
queryFieldMicrositePages {
  entities {
    entityId
  }
}
...
```
And I'm expecting the following result.
```
"queryFieldMicrositePages": {
   "entities": [
      {
         "entityId": "93" // Delta 0
      },
      {
         "entityId": "90" // Delta 1
      },
      {
         "entityId": "78" // Delta 2
      },
      {
         "entityId": "95" // Delta 3
      },
      {
         "entityId": "98" // Delta 4
      },
      {
         "entityId": "237" // Delta 5
      }
    ]
}
```

But instead I get this result.
```
"queryFieldMicrositePages": {
   "entities": [
      {
         "entityId": "98" // Delta 4
      },
      {
         "entityId": "95" // Delta 3
      },
      {
         "entityId": "90" // Delta 1
      },
      {
         "entityId": "78" // Delta 2
      },
      {
         "entityId": "93" // Delta 0
      },
      {
         "entityId": "237" // Delta 5
      }
    ]
}
```

So I dug a bit deeper into the code and looked at the [EntityReferenceQuery.php](https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityReference/EntityReferenceQuery.php) file and dumped out the ids that it gets from the field and I get the correct order on the nodes.

```
Array ( 
  [0] => 93 
  [1] => 90 
  [2] => 78 
  [3] => 95 
  [4] => 98 
  [5] => 237 
)
```

So somewhere along the way it scrambles the result into a random(?) order, and I cannot figure out where it does this. I'm not very familiar with the code at the moment, but I would like to add a fix for this, so does anyone have a clue or any pointers for which file I should look into?

**Comment by fubhy** [comment]
This is probably cause by the buffered loading we use there. We need to re-sort the returned entities in the deferred result (produced by the entity load buffer). Do you want to look into that yourself and provide a PR? I can help out if you want.

The place you want to look at is this line: 

https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityQuery/EntityQueryEntities.php#L143

Instead of directly passing `$resolve()` to the method, you want to sort the output of `$resolve()` (list of entities) according to the given array of `$ids` from line 141.

**Comment by jayza** [comment]
@fubhy 
Seems at that stage the ``$ids`` are already scrambled. When I dump the ``$result`` on [line 109](https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityQuery/EntityQueryEntities.php#L109) I get the following array:

```
Array
(
    [0] => Array
        (
            [115] => 98
            [119] => 95
            [179] => 90
            [180] => 78
            [181] => 93
            [334] => 237
        )
)
```

So I believe the arrays are getting sorted by their version id in the node table before ever reaching this point. So is it an issue with the query then? 

If we would add the original $ids as metadata to the query and then pass that into the ``resolveFromEntityIds`` and sort it, would that be a clean/possible solution?

**Comment by jayza** [comment]
@fubhy I've added a new PR. In the EntityReferenceQuery.php file I add the original sorting order to the context. Then I retrieve it in the resolver and add sort it.

**Comment by fubhy** [comment]
Hi @jayza. Thanks for the PR. I adapted it a bit. Can you check https://github.com/drupal-graphql/graphql/pull/743 if you get a chance?

**Comment by jayza** [comment]
@fubhy 

When can we expect this to be available in the drupal/graphql repository?
