### ISSUE TITLE
Explorer is broken [ Drupal 8.6.10 ]

### ISSUE THREAD

**Issue by miiimooo** [drupal-graphql/graphql#733]
I've just enabled latest 3.x-dev version and get an error message when accessing /graphql/explorer

```
Uncaught TypeError: Cannot read property '__schema' of undefined
    at i (bundle.min.js?v=8.6.10:1)
    at Object.attach (bundle.min.js?v=8.6.10:1)
    at drupal.js?v=8.6.10:25
    at Array.forEach (<anonymous>)
    at Object.Drupal.attachBehaviors (drupal.js?v=8.6.10:22)
    at drupal.init.js?v=8.6.10:16
    at HTMLDocument.t (ready.min.js?v=1.0.8:4)
i	@	bundle.min.js?v=8.6.10:1
attach	@	bundle.min.js?v=8.6.10:1
(anonymous)	@	drupal.js?v=8.6.10:25
Drupal.attachBehaviors	@	drupal.js?v=8.6.10:22
(anonymous)	@	drupal.init.js?v=8.6.10:16
t	@	ready.min.js?v=1.0.8:4
setTimeout (async)		
Drupal.throwError	@	drupal.js?v=8.6.10:12
(anonymous)	@	drupal.js?v=8.6.10:27
Drupal.attachBehaviors	@	drupal.js?v=8.6.10:22
(anonymous)	@	drupal.init.js?v=8.6.10:16
t	@	ready.min.js?v=1.0.8:4
```

**Comment by miiimooo** [comment]
Works in fresh install with minimal profile

**Comment by cidicles** [comment]
Any suggestions for getting around this issue without being able to do a fresh install? I'm getting the same thing.

**Comment by jalama** [comment]
I'm seeing this issue on a non-minimal install (which isn't really an option for an already in place project :( )

**Comment by jalama** [comment]
I'm on version 8.6.13

**Comment by MurzNN** [comment]
I got same issue, seems the source of problem is enabled `layout_builder` module because of `Missing type layout_section` error in Drupal dblog.

@jalama Can you lookup if this module is enabled on your site, and uninstalling solve the issue?

**Comment by ameshkin** [comment]
This should not be closed. The issue still exists when layout_builder is enabled.

**Comment by MurzNN** [comment]
Before this issue is fixed via right way, here is my patch (quick workaround) for fix Layout Builder to not break GraphQL Explorer:
```
diff --git a/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php b/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php
index dc60dd9..802ab50 100644
--- a/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php
+++ b/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php
@@ -439,7 +439,11 @@ abstract class SchemaPluginBase extends PluginBase implements SchemaPluginInterf
    * {@inheritdoc}
    */
   public function processFields(array $fields) {
-    return array_map([$this, 'buildField'], $fields);
+    $processFields = array_map([$this, 'buildField'], $fields);
+    foreach($processFields as $key => $processField) {
+      if($processField === false) unset($processFields[$key]);
+    }
+    return $processFields;
   }
 
   /**
@@ -506,6 +510,7 @@ abstract class SchemaPluginBase extends PluginBase implements SchemaPluginInterf
    *   The field definition.
    */
   protected function buildField($field) {
+    if($field['definition']['type'][0] == "layout_section") return false;
     if (!isset($this->fields[$field['id']])) {
       $creator = [$field['class'], 'createInstance'];
       $this->fields[$field['id']] = $creator($this, $this->fieldManager, $field['definition'], $field['id']);

**Comment by timothyjoh** [comment]
> Before this issue is fixed via right way, here is my patch (quick workaround) for fix Layout Builder to not break GraphQL Explorer:
> 
> ```
> diff --git a/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php b/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php
> index dc60dd9..802ab50 100644
> --- a/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php
> +++ b/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php
> @@ -439,7 +439,11 @@ abstract class SchemaPluginBase extends PluginBase implements SchemaPluginInterf
>     * {@inheritdoc}
>     */
>    public function processFields(array $fields) {
> -    return array_map([$this, 'buildField'], $fields);
> +    $processFields = array_map([$this, 'buildField'], $fields);
> +    foreach($processFields as $key => $processField) {
> +      if($processField === false) unset($processFields[$key]);
> +    }
> +    return $processFields;
>    }
>  
>    /**
> @@ -506,6 +510,7 @@ abstract class SchemaPluginBase extends PluginBase implements SchemaPluginInterf
>     *   The field definition.
>     */
>    protected function buildField($field) {
> +    if($field['definition']['type'][0] == "layout_section") return false;
>      if (!isset($this->fields[$field['id']])) {
>        $creator = [$field['class'], 'createInstance'];
>        $this->fields[$field['id']] = $creator($this, $this->fieldManager, $field['definition'], $field['id']);
> ```

This worked great. Did you make a PR of it?

**Comment by justclint** [comment]
thanks @MurzNN, that worked great!

**Comment by MurzNN** [comment]
Here https://github.com/drupal-graphql/graphql/pull/1144 is my pull request with changes from https://github.com/drupal-graphql/graphql/issues/733#issuecomment-636876458
