### ISSUE TITLE
Security access

### ISSUE THREAD

**Issue by lukamoura** [drupal-graphql/graphql#735]
I have enabled the cors to only access the server where my application reactjs is and disabled the 'Bypass field security' permission and all of the anonymous profile permissions.
To ensure access to the endpoint do you use JWT? 

I'm sorry write about this here but I don't see much about the Drupal GraphQL endpoint security... only about REST.

**Comment by pmelab** [comment]
`Bypass field security` is only about allowing certain risky operations in an insecure environment.

When using JWT for authentication, you could just give this user the `Execute arbitrary GraphQL queries` permission.
