### ISSUE TITLE
currentUserContext cached - is it possible to cache the Schema but not the query results ?

### ISSUE THREAD

**Issue by rawxx** [drupal-graphql/graphql#737]
There are probably two questions in that issue, but they're related.

First quick question : since version beta6 of the module, `result_cache`, `schema_cache` and `development` parameters have been combined into one only `development` parameter. Is there still a way to cache the schema but not the results ?

My actual issue : I am using Appollo and [simple_oauth](https://www.drupal.org/project/simple_oauth) module to log into Drupal. Once logged in, I use `currentUserContext` to retrieve the user information. Everything worked fine until I updated the module from beta5 to latest dev version. `currentUserContext` appears to be `null` for certain roles. I have tried a different way, changing this query : 
```
{
  currentUserContext {
    entityId
  }
}
```
to this one : 
```
{
  route(path:"/user") {
    ...on InternalUrl {
      currentUserContext {
        entityId
      }
    }
  }
}
```
It seemed to work at first, but I realized the second query was cached for some roles (the same roles for which the first query returns `null`).

Why do some roles have a null `currentUserContext` ? Could it be a question of permissions ?

**Comment by sppera** [comment]
In regards to currentUserContext null result. 

After debugging it was found out that changing the priority of event subscriber in https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/EventSubscriber/SubrequestSubscriber.php#L32 above 100 (not determined exactly) fixed the issue. 

```
public static function getSubscribedEvents() {
   return [KernelEvents::REQUEST => ['onKernelRequest', 100]];
}
```

Caching issues still remain.

**Comment by sppera** [comment]
An additional observation regarding caching. Caching results can be disabled by setting
`$settings['cache']['bins']['graphql_results'] = 'cache.backend.null';`
in settigns.php

**Comment by sppera** [comment]
A further observation regarding caching.

Passing 
```
response_cache_contexts={"user"}
```
in https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/Context/Context.php#L17

GraphQLField annotation per
https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/Annotation/GraphQLAnnotationBase.php#L77

or checking the ResolveInfo fieldName and adding cache context manually in ```resolveValues```

```
 if ($info->fieldName === 'currentUserContext') {
      $context->addCacheContexts(['user']);
    }
```

solved the issue.

**Comment by Thommusa** [comment]
hello there I try to use response_cache_contexts annotation but it doesn't work, maybe miss something ? But alter the $context object in resolveValues work fine :)

**Comment by uxweb** [comment]
> An additional observation regarding caching. Caching results can be disabled by setting
> `$settings['cache']['bins']['graphql_results'] = 'cache.backend.null';`
> in settigns.php

Hi @sppera 

I did this but when rebuilding the cache it says:

```bash
In ContainerBuilder.php line 1063: 
                                                                    
  You have requested a non-existent service "cache.backend.null".   
```

I'm using Drupal 8.7.4

Thanks

**Comment by uxweb** [comment]
@sppera 

I'm also using cookie authentication to make graphql requests.

When I log in with a user, drupal creates a session cookie that is shared with the decoupled front-end React app. This app shows the information of the logged-in user.

The issue happens when the current user log out from Drupal and a second user logs in. At this point the front-end app still shows the previous user data.

This is the graphql query executed:

```graphql
{
  route(path: "/user") {
    ... on InternalUrl {
      currentUserContext {
        id: uid
        name
        aboutMe: fieldAboutMe
        mail
        avatar: userPicture {
          width
          height
          alt
          title
          url
          entity {
            filename
            filemime
            filesize
          }
        }
        roles {
          entity {
            entityId
            entityLabel
          }
        }
      }
    }
  }
}
```

**Comment by davidwhthomas** [comment]
Unless I'm missing something, it appears the `user` cache context is added in `\Drupal\user\ContextProvider\CurrentUserContext` but after that, it isn't added to the `response_cache_contexts` GQL field definition in `\Drupal\graphql_core\Plugin\Deriver\Fields\ContextDeriver`. 
Adding the cache context there should solve this issue. 

https://github.com/drupal-graphql/graphql/pull/865

**Comment by fubhy** [comment]
Thanks for the fix! Merged and pushed to 3.x-dev on d.o
