### ISSUE TITLE
New release required to make the dependent tests being executed on Drupal CI

### ISSUE THREAD

**Issue by rthideaway** [drupal-graphql/graphql#738]
We are building small module on top of GraphQL and JWT, see https://www.drupal.org/project/graphql_jwt

We also wrote a small test to confirm the feature works. The problem is that Drupal-CI refuses to run our test since dependent graphql module is missing @group annotations on some test classes in latest release, see https://dispatcher.drupalci.org/job/drupal_contrib/337738/console

The issue is already fixed in dev release of GraphQl module, see http://cgit.drupalcode.org/graphql/commit/?id=ab4f496087a48ad4f2ef2315b73254b9a395b731
But Drupal CI does not use dev releases. That being said, it would be amazing to have latest rc3 release of GraphQL module so also our (and other related) tests are executed on Drupal CI.

**Comment by pmelab** [comment]
Just released RC3.
