### ISSUE TITLE
Custom argument types

### ISSUE THREAD

**Issue by joaogarin** [drupal-graphql/graphql#748]
hello,

in 4.x while builidng my schema I have the need to define arguments to a query, some of those arguments are a custom type. Perhaps I am doing this wrong but here is the idea : 

``` 
type Query {
  route(path: String!): Response
  menu(name: String!): Menu
  searchAPISearch(index_id: String!, fulltext: FulltextInput, language: [String]): SearchAPIResult
}

type FulltextInput {
  keys: [String]!
  fields: [String]
  conjunction: String
}

type SearchAPIResult {
  ...
}

...

```

The fulltext here breaks. Is there another way to do this in the 4.x Sdl schema?

**Comment by pmelab** [comment]
How does it break? And where is the schema definition for `FulltextInput`?

**Comment by pmelab** [comment]
Scratch, that, its one line below 😆 

But it has to be an input type definition: https://graphql.org/learn/schema/#input-types

**Comment by joaogarin** [comment]
🤦‍♂️  Thanks I will try it out. I wondered maybe its just my noobness graphql here..previously (in 3.x) this was indeed an InputType 👍

**Comment by joaogarin** [comment]
Thanks that fixes it! Closing 🎉
