### ISSUE TITLE
Menu Link Atribute: Expected a value of type "String" but received: ["class1","class2, ..."]

### ISSUE THREAD

**Issue by sixtyniner-official** [drupal-graphql/graphql#752]
I use [Link Attributes](https://www.drupal.org/project/link_attributes) and I've added class to Menu Item.

Now when run following query:

```
query {
  menuByName(name: "facility-best-choice") {
    links {
      attribute(key: "class")
    }
  }
}
```
Got: "Internal server error"
Drupal Log says: "Expected a value of type "String" but received: ["class1","class2"]"

`MenuLinkAttribute.php` code:

```php
<?php

namespace Drupal\graphql_core\Plugin\GraphQL\Fields\MenuLink;

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Menu\MenuLinkTreeElement;
use Drupal\graphql\GraphQL\Execution\ResolveContext;
use Drupal\graphql\Plugin\GraphQL\Fields\FieldPluginBase;
use GraphQL\Type\Definition\ResolveInfo;

/**
 * Retrieve specific attributes of a menu link.
 *
 * @GraphQLField(
 *   id = "menu_link_attribute",
 *   secure = true,
 *   name = "attribute",
 *   type = "String",
 *   parents = {"MenuLink"},
 *   arguments = {
 *     "key" = "String!"
 *   }
 * )
 */
class MenuLinkAttribute extends FieldPluginBase {

  /**
   * {@inheritdoc}
   */
  protected function resolveValues($value, array $args, ResolveContext $context, ResolveInfo $info) {
    if ($value instanceof MenuLinkTreeElement) {
      $options = $value->link->getOptions();
      yield NestedArray::getValue($options, ['attributes', $args['key']]);
    }
  }

}
```

**Comment by pmelab** [comment]
I think this should be resolved in 2 steps:
1. the `attribute` field should have a check that implodes the classes array to a classes string
2. there should be a new `classes` field on the menu link type that returns a list of classes as `[String]`

**Comment by mohit-rocks** [comment]
@pmelab This seems already fixed in this commit.
https://github.com/drupal-graphql/graphql/commit/a6ba72d66c90cd8a6534e3435a2b9eca43bdfeee#diff-2a296ae90b74489206402fd4831a4135

Also, I tried to reproduce it with the latest graphql 3.x branch, seems working fine.
https://send.firefox.com/download/16ad7d23b1eb9218/#DjuJXGsr7j0Mw_OXCKJXTg

You can find configuration and graphql query in following snapshots.
https://ibb.co/0cnfhwB
https://ibb.co/t8wqPYx

**Comment by pmelab** [comment]
Great, thanks for checking @mohit-rocks! Scratching this off the list.

**Comment by sixtyniner-official** [comment]
As ticket creator, can also approve that issue is fixed in the latest version (8.x-3.0-rc3).
Thank you @mohit-rocks, @pmelab
