### ISSUE TITLE
Documentation site

### ISSUE THREAD

**Issue by joaogarin** [drupal-graphql/graphql#761]
Hello,

I would like to start a definite discussion to make a decision on how and where the official documentation for graphql should live. 

As you know we are using the module and will definitely need a good documentation for it, since we might have people jumping into the codebase that will need guidance.

We are committed to helping not only writing the docs but I think having a good place to browse them is key in getting more people involved.

We started the topic in slack (probably already gone the conversation) where I posted a small prototype / suggestion for gitbook : https://joao-graphql.gitbook.io/drupal-graphql/v/8.x-3.x/

@pmelab I remember you talked about vuepress I think? That could also be an option. I think would be nice for us to have this process defined so we can start documenting also 4.x features.

So on this we could come up with a good place for docs where 3.x and 4.x can live together (ideally) and people using either one can easily contribute back.

I think on any option is good that docs live in this repo anyway..these tools just read from the docs folder here to put the doc site live.

**Comment by pmelab** [comment]
Sorry, this kind of fell under the table. It's important to separate 3.x and 4.x documentation. And Gitbook has this feature out of the box, so i think we should go for that. https://drupal-graphql.gitbook.io already points to your setup. Where does it read from? Can we move it somehow?

**Comment by joaogarin** [comment]
I can either make one and request access or you can also make a space directly in gitbook. I don't mind setting that up. but needs read access to the repo. I will send an invite link for admin access through chat in slack.

**Comment by pmelab** [comment]
Closing this issue since https://drupal-graphql.gitbook.io/graphql/ is alive and kicking!
