### ISSUE TITLE
PHP notice / warnings

### ISSUE THREAD

**Issue by rm-bergmann** [drupal-graphql/graphql#770]
When I clear cache with Drush I am getting this PHP warning:

```[warning] Invalid argument supplied for foreach() EntityReferenceQueryDeriver.php:100```

And when I clear cache with drupal console I get this notice which points to the same line of code:

```PHP Notice:  Undefined index: field_files_over_ajax in /modules/contrib/graphql/modules/graphql_core/src/Plugin/Deriver/Fields/EntityReferenceQueryDeriver.php on line 100```

A stack trace is also output:
```
PHP Stack trace:
PHP   1. {main}() /vendor/drupal/console/bin/drupal:0
PHP   2. require() /vendor/drupal/console/bin/drupal:4
PHP   3. Drupal\Console\Application->run() /vendor/drupal/console/bin/drupal.php:89
PHP   4. Drupal\Console\Application->doRun() /vendor/symfony/console/Application.php:148
PHP   5. Drupal\Console\Application->doRun() /vendor/drupal/console/src/Application.php:64
PHP   6. Drupal\Console\Application->doRun() /vendor/drupal/console-core/src/Application.php:185
PHP   7. Drupal\Console\Application->doRunCommand() /vendor/symfony/console/Application.php:255
PHP   8. Drupal\Console\Command\Cache\RebuildCommand->run() /vendor/symfony/console/Application.php:978
PHP   9. Drupal\Console\Command\Cache\RebuildCommand->execute() /vendor/symfony/console/Command/Command.php:255
PHP  10. Drupal\Console\Utils\DrupalApi->drupal_rebuild() /vendor/drupal/console/src/Command/Cache/RebuildCommand.php:104
PHP  11. drupal_flush_all_caches() /vendor/drupal/console/src/Utils/DrupalApi.php:355
PHP  12. Drupal\Core\ProxyClass\Routing\RouteBuilder->rebuild() /core/includes/common.inc:1160
PHP  13. Drupal\Core\Routing\RouteBuilder->rebuild() /core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php:83
PHP  14. Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() /core/lib/Drupal/Core/Routing/RouteBuilder.php:184
PHP  15. call_user_func:{/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111}() /core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
PHP  16. Drupal\graphql\Routing\QueryRoutes->onAlterRoutes() /core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
PHP  17. Drupal\graphql\Routing\QueryRoutes->alterRoutes() /core/lib/Drupal/Core/Routing/RouteSubscriberBase.php:37
PHP  18. Drupal\graphql\Plugin\SchemaPluginManager->getDefinitions() /modules/contrib/graphql/src/Routing/QueryRoutes.php:41
PHP  19. Drupal\graphql\Plugin\SchemaPluginManager->findDefinitions() /core/lib/Drupal/Core/Plugin/DefaultPluginManager.php:175
PHP  20. Drupal\Core\Plugin\Discovery\ContainerDerivativeDiscoveryDecorator->getDefinitions() /core/lib/Drupal/Core/Plugin/DefaultPluginManager.php:284
PHP  21. Drupal\Core\Plugin\Discovery\ContainerDerivativeDiscoveryDecorator->getDerivatives() /core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php:87
PHP  22. Drupal\graphql\Plugin\Deriver\PluggableSchemaDeriver->getDerivativeDefinitions() /core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php:101
PHP  23. Drupal\graphql\Plugin\Deriver\PluggableSchemaDeriver->buildFieldAssociationMap() /modules/contrib/graphql/src/Plugin/Deriver/PluggableSchemaDeriver.php:103
PHP  24. Drupal\graphql\Plugin\FieldPluginManager->getDefinitions() /modules/contrib/graphql/src/Plugin/Deriver/PluggableSchemaDeriver.php:230
PHP  25. Drupal\graphql\Plugin\FieldPluginManager->findDefinitions() /core/lib/Drupal/Core/Plugin/DefaultPluginManager.php:175
PHP  26. Drupal\Core\Plugin\Discovery\ContainerDerivativeDiscoveryDecorator->getDefinitions() /core/lib/Drupal/Core/Plugin/DefaultPluginManager.php:284
PHP  27. Drupal\Core\Plugin\Discovery\ContainerDerivativeDiscoveryDecorator->getDerivatives() /core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php:87
PHP  28. Drupal\graphql_core\Plugin\Deriver\Fields\EntityReferenceQueryDeriver->getDerivativeDefinitions() /core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php:101
```

Not sure if this has been reported before, and not sure if anyone has had this before. If not, any idea why I would be getting these warnings / notices?

Thanks.

**Comment by sunderhaus** [comment]
@rm-bergmann, were you able to resolve this problem? I'm experiencing something similar with a field I've removed. Despite it being absent from my configuration. I still get the same error you have, but specific to my field machine name.

**Comment by rm-bergmann** [comment]
@sunderhaus unfortunately I have not resolved it yet, still getting the error. Not sure where to start.
I definitely didn't create/delete a field call 'field_files_over_ajax' so maybe it came from installing and uninstalling a 3rd party module. So maybe there is a reference to the field somewhere that needs to be removed?

**Comment by sunderhaus** [comment]
@rm-bergmann I started to see this clear up after I removed the field references as described before and then resetting the cache. I don't mean to presume you haven't already, but perhaps searching through your site's configuration for the `field_files_over_ajax` to locate whatever reference is hanging around could help.

**Comment by rm-bergmann** [comment]
@sunderhaus thanks for the tip. I found some references to that field in a module called entity_browser. I wasn't using it so I uninstalled it, removing those references. I also found some references in the database to that field, which I've now deleted. It hasn't cleared up yet so I am still getting the notice. I'll check the db again, but at least I know what to do to get round this. Thanks.

**Comment by mhmhartman** [comment]
@sunderhaus @rm-bergmann I just had the same issue. Entity browser test module has added some config, which wasn't removed after uninstall. Simply removing the config files did the trick.
