### ISSUE TITLE
No route found for the specified format _graphql_subrequest

### ISSUE THREAD

**Issue by ArneSaknussemm89** [drupal-graphql/graphql#771]
On a fresh Drupal 8.7.0-rc1 site install, getting this error when trying to run the `currentUserContext` query:

```
Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: 
No route found for the specified format _graphql_subrequest. 
Supported formats: html. in Drupal\Core\Routing\RequestFormatRouteFilter->filter() 
(line 65 of /var/www/docroot/core/lib/Drupal/Core/Routing/RequestFormatRouteFilter.php).
```

Running this query from postman, using a Basic Auth header. The error shows the correct user in the Drupal logs message, but always returns:
```
{
  "data": {
    "currentUserContext": null
  }
}
```

Using GraphQL version 8.x-3.0-rc3.

Any one else seen this error? I can't seem to find where the `currentUserContext` query is defined in the `graphql` or `graphql_core` modules.

**Comment by sppera** [comment]
@ArneSaknussemm89 

Could you try the following solution: https://github.com/drupal-graphql/graphql/issues/737#issuecomment-484409616 ?

**Comment by ArneSaknussemm89** [comment]
@sppera 

That totally worked! Will this be merged soon, or should I go ahead and create an issue on Drupal.org and provide a patch?

**Comment by sppera** [comment]
@ArneSaknussemm89 

Hi. Don't know if it will be merged soon. Didn't create the issue on Drupal.org. If you don't mind go ahead and create the issue on Drupal.org.

**Comment by davidwhthomas** [comment]
Just had a related error with `null` current user context for anon users and error msg `"Call to undefined method Drupal\Core\Routing\LocalRedirectResponse::getResult()",`

Changing the event subscriber weight to run earlier (`100`) fixed the issue

**Comment by davidwhthomas** [comment]
Added PR for the weight order adjustment here: https://github.com/drupal-graphql/graphql/pull/867

**Comment by pmelab** [comment]
I just tried to reproduce the problem, but I was not successful:

* Fresh install of Drupal 8.7.8
* Enabled the GraphQL and GraphQL Content and Basic Auth modules

- [x] `currentUserContext` returns the correct user in explorer
- [x] `currentUserContext` returns the correct user in an anonymous request
- [x] `currentUserContext` returns the correct user in an authenticated request

Please feel free to reopen if I am wrong.
