### ISSUE TITLE
Can't install the 3.0-RC3

### ISSUE THREAD

**Issue by Thommusa** [drupal-graphql/graphql#775]
Hello when I try to update graphql i get this error
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/graphql_core 3.x-dev requires drupal/graphql == 3.9999999.9999999.9999999-dev -> satisfiable by drupal/graphql[3.x-dev].
    - drupal/graphql_core 3.x-dev requires drupal/graphql == 3.9999999.9999999.9999999-dev -> satisfiable by drupal/graphql[3.x-dev].
    - drupal/graphql_core 3.x-dev requires drupal/graphql == 3.9999999.9999999.9999999-dev -> satisfiable by drupal/graphql[3.x-dev].
    - Can only install one of: drupal/graphql[3.0.0-rc3, 3.x-dev].
    - Can only install one of: drupal/graphql[3.0.0-rc3, 3.x-dev].
    - Can only install one of: drupal/graphql[3.0.0-rc3, 3.x-dev].
    - Installation request for drupal/graphql 3.0-rc3 -> satisfiable by drupal/graphql[3.0.0-rc3].
    - Installation request for drupal/graphql_core (locked at 3.x-dev) -> satisfiable by drupal/graphql_core[3.x-dev].

Installation failed, reverting ./composer.json to its original content.
`

**Comment by Breuls** [comment]
Which command are you using to update? 

It's relevant to update both `drupal/graphql` and `drupal/graphql_core` at the same time, as the latter requires the same version as the former.

You might want to try listing the dependencies like this:

        "drupal/graphql": "^3.0@RC",
        "drupal/graphql_core": "^3.0@RC",

And then running an update for both packages:

    composer update drupal/graphql_core drupal/graphql --with-dependencies

**Comment by Thommusa** [comment]
thanks  it's work
