### ISSUE TITLE
How to execute query into drupal programmatically

### ISSUE THREAD

**Issue by Thommusa** [drupal-graphql/graphql#780]
Hello there I woud like to know if it's possible to execute graphql query into drupal with php?

**Comment by pmelab** [comment]
Yes, you can just use the graphql processor service directly. The graphql twig module does that for example: https://github.com/drupal-graphql/graphql-twig/blob/8.x-1.x/src/GraphQLTemplateTrait.php#L85-L88

Thats the service you have to use: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/graphql.services.yml#L44
