### ISSUE TITLE
GraphQL module doesn't supports JWT 

### ISSUE THREAD

**Issue by quexpl** [drupal-graphql/graphql#782]
I have installed the JWT module, and I'm able to login using JSON Web Token. But each time when I request /grapqh I get 403, on page preview I can confirm that I'm logged in. Permissions are fine. I don't have this problem with basic_auth.

**Comment by Thommusa** [comment]
hello there see https://www.drupal.org/project/graphql_jwt and also apply this patch for rc3 https://www.drupal.org/project/graphql_jwt/issues/3053823

**Comment by fubhy** [comment]
Resolved with #774
