### ISSUE TITLE
How to create new schema type

### ISSUE THREAD

**Issue by williamjieh** [drupal-graphql/graphql#784]
Hi,

How to create a new type use this module? Is there any code example?
Let's say, I want to make a query like this:

```
{
  headlinelist {
    img
    postId
    postTitle
  }
}
```
And the schema is like this:

```
type Post {
  img: String!
  postId: Int!
  postTitle: String!
}

type Query {
  headlinelist(sizeOfTotal: Int=10): [Post!]!
}
```
How to create Post type and headlinelist field with graphql module?
Thank you!

**Comment by Pasqualle** [comment]
The graphQL module version 3, will generate the schema for you, no code needs to be written.

If you consider this schema, which is very similar to yours
```
type NodeBlog {
  nid: Int,
  title: String!,
  fieldSubtitle: String,
  fieldCategory: [String]
  ...
}

type NodeBlogQueryFilterInput {
  fieldCategory: [String]
  ...
}

type NodeBlogQueryResult {
  count: Int
  results: [NodeBlog]
}

query blogList(
  page: Int = 0,
  pageSize: Int = 10,
  filter: NodeBlogQueryFilterInput = null
): NodeBlogQueryResult

```
then this can be achieved with the following steps:
1. Create a blog node
 - add fields subtitle and category (or anything you need)
2. Create blog listing view
 - Enable the graphql_views module 
 - Create a view with machine name node_blog_query
 - Add graphql display to the view
 - Configure view exposed filters as you like
 - Configure view pagination
 - Change the graphql query name

done

notes:
- If you do not want to use graphql_views module then a similar query can be done with nodeQuery
https://github.com/drupal-graphql/graphql/blob/8.x-3.x/doc/queries/querying-nodes.md
- if you do not like the generated graphql field names, it can be changed with the hook_graphql_fields_alter() hook
- if you do not like that the graphQL schema is automatically constructed for you (based on your Drupal content settings), then the version 4 will allow to define the schema, but there is no stable release yet.

**Comment by pmelab** [comment]
For reference I'll also reference the documentation on how to create a custom schema in V4:
https://drupal-graphql.gitbook.io/graphql/v/8.x-4.x/getting-started/custom-schema
