### ISSUE TITLE
Nested queries : how to get parent/ancestor object in resolveValues()

### ISSUE THREAD

**Issue by rawxx** [drupal-graphql/graphql#789]
Hi,

Let's say have a query like : 

```
query($marketId:String!) {
  taxonomyTermById(id:$marketId) {
    ...on TaxonomyTermMarket {
      availableProducts {
        ... on NodeProduct {
          priceByMarket(market_id: $marketId)
        }
      }
    }
  }
}
```

Basically, this retrieves, for a given country, all availables products, and for each product its price in this country.
As you see, I use the variable `$marketId` twice in the query, first in root query `taxonomyTermById` then in my custom field `priceByMarket`. Unfortnuately, for data model design reasons, I have no choice but to use this variable in `priceByMarket`.

Is there any way in my PriceByMarket class's `resolveValues` to retrieve the already resolved TaxonomyTermMarket's `entityId` ?

The problem is I'm unable to run this query on all markets : 
```
query {
  taxonomyTermQuery(filter: {conditions: [{field: "vid", value: ["market"]}]}) {
    entities {
      ...on TaxonomyTermMarket {
        availableProducts {
          ... on NodeProduct {
            priceByMarket(market_id: $marketId) #this should not be an arg, but the TaxonomyTermMarket's entiyId
          }
        }
      }
    }
  }
}
```

Now to be honest, my real query is more nested than this, so I'd need to be able to get not the parent but any ancestor within `resolveValues()`, I guess the problem remains the same.

**Comment by pmelab** [comment]
Yes, the GraphQL executor maintains a context object that can be used to pass values down the tree:
https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/GraphQL/Execution/ResolveContext.php

The `Route` field for example writes the language to the context ...

https://github.com/drupal-graphql/graphql/blob/8.x-3.x/modules/graphql_core/src/Plugin/GraphQL/Fields/Routing/Route.php#L131

... so other fields can use it.

**Comment by rawxx** [comment]
Thank you @pmelab for these details, but I'm still not sure how to pass a different value in every branch of the tree (as each branch has a different ancestor value from the same query).

This is what I naively tried in at the end of my custom field's _resolveValues()_ :

```
   protected function resolveValues($value, array $args, ResolveContext $context, ResolveInfo $info): \Generator {

    $tids = \Drupal::entityQuery('taxonomy_term')
        ->condition('vid', 'market')
        ->execute();

    $markets = Term::loadMultiple($tids);

    foreach ($markets as $tid => $market) {
      $context->setContext('market_id', $tid, $info);//naively trying to pass a value down the tree
      yield $market;
    }
  }
```
Then in a descendant field I call `$context->getContext('market_id', $info)`, but of course the value is always the last that was set : there's one value for the whole tree, not one per branch.

I have hundreds of _market_ Taxonomy Terms loaded in this query, but in every of their children fields, the 'market_id' passed is not the ancestor _market_'s tid, just the last loaded _market_'s tid.

Did I miss something or is it just not possible ?
