### ISSUE TITLE
GraphQL 3.x redirect loop

### ISSUE THREAD

**Issue by duartegarin** [drupal-graphql/graphql#806]
Hi folks, I’m encountering a very strange behaviour with redirects and hoping someone can help me out.

Basically I have a piece of content which had the url changed and a redirect created. Thing is, when I have two “route” queries for some reason I seem to get a redirect loop.

For example:

```
fragment QueryGroupContentMeta on Query {
  __typename
  meta: route(path: $path) {
    __typename
  }
}


fragment QueryGroupContentMasthead on Query {
  __typename
  masthead: route(path: $path) {
    __typename
  }
}



query GroupContentContainer($path: String!) {

  ...QueryGroupContentMasthead
  ...QueryGroupContentMeta

}
```

This yields:

```
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 4,
          "column": 3
        }
      ],
      "path": [
        "meta"
      ]
    }
  ],
  "data": {
    "__typename": "Query",
    "masthead": {
      "__typename": "RedirectUrl"
    },
    "meta": null
  }
}
```

And in Drupal I can see `Redirect loop identified at /group/2/career-planning/career-advice-for-law-students-in-new-zealand for redirect 2959`

However if I remove any of those two fragments, I get no error.

Using 3.x version.

Thanks!

**Comment by fubhy** [comment]
Seems like there is a context unaware stack for loop detection somewhere. Sadly a lot of places in Drupal core are not RequestStack aware and hence do not realize whrn they are executed in different contexts (e.g. subrequests). That leads to reusing of static caches across execution boundaries

**Comment by fubhy** [comment]
Did you check with xdebug for where this error is thrown? I am currently only on my phone

**Comment by duartegarin** [comment]
I'll debug and report back. Thanks!

**Comment by duartegarin** [comment]
Hi @fubhy ,
Here is where this gets triggered (Redirect module, RedirectRepository.php):

```      // Check if this is a loop.
      if (in_array($rid, $this->foundRedirects)) {
        throw new RedirectLoopException('/' . $source_path, $rid);
      }
      $this->foundRedirects[] = $rid;
```

When I have the two routes, the debug passes twice on that code. The first time it passes through it fine (the foundRedirects array is empty), but the second time the array has the rid that's being set at the end of that code snippet and so it triggers the exception.

What do you think next steps are?

Cheers and thanks again

**Comment by fubhy** [comment]
This sounds like a bug in the redirect module. It should allow two independent processes. Thr array with the foundRedirects should be scoped somehow.

**Comment by fubhy** [comment]
Is there a way to clear it?

**Comment by duartegarin** [comment]
Opened issue in Redirect module here:

https://www.drupal.org/project/redirect/issues/3061173

**Comment by duartegarin** [comment]
This has now been fixed by Redirect.
