### ISSUE TITLE
Allow query configuration entities

### ISSUE THREAD

**Issue by omarlopesino** [drupal-graphql/graphql#810]
Hello. I would like to help drupal GraphQL integration by allowing query config entities.

I have a work in progress, not stable, in [this repository](https://github.com/mistermoper/graphql_configuration). Now it lets obtain config entities by id:

```graphql
query {
  configEntitiesByType(type:"node_type") {
    name
  }
}
```

and returns

```json
{
  "data": {
    "configEntitiesByType": [
      {
        "name": "Article"
      },
      {
        "name": "Basic page"
      }
    ]
  }
}
```
It needs tests and also the fields set in query are every fields available in config entities instead of the fields available in the specific config entity that we need.

So before to start a pull request: would you like to add this to graphql main module, so the WIP can be moved to a PR?

**Comment by omarlopesino** [comment]
arg, I've just realised the 4.x versions changes the api completely in order to use data producers, but the code i was working is done for 3.x.

It could be worth doing this feature for both versions 3.x and 4.x?

**Comment by Pasqualle** [comment]
https://github.com/drupal-graphql/graphql/issues/64
https://github.com/drupal-graphql/graphql/pull/477
https://github.com/drupal-graphql/graphql/issues/580

> the approach was dropped, because there are many types of config entities, and we would have inflated the schema with a lot of stuff that never gets used. 
so, until we have the configurable schema, it’s back to custom fields for config entities.

That means configuration entities should be done in 4.x
