### ISSUE TITLE
Introduce file upload service to be used in mutations

### ISSUE THREAD

**Issue by rthideaway** [drupal-graphql/graphql#819]
Currently there is no way to handle upload file within mutations in 4.x version except doing it all by yourself.

Would be cool if GraphQL provides some service to handle file uploads. Ideally to work with UploadedFile objects which are automatically instantiated in Symfony during file upload requests and can be accessed in resolvers.

**Comment by rthideaway** [comment]
This PR could be (hopefully) a good start with resolving the problem -> https://github.com/drupal-graphql/graphql/pull/818

It introduces a service which can handle file upload by providing UploadedFile object and respective file settings (destination dir, max upload size, list of allowed extensions, etc).

**Comment by fubhy** [comment]
Yes, we will be writing uploaded files into the ResolveContext object and will then make them available contextually via the FieldContext parameter on a per-field level (where the file is referenced via the graphql file upload spec). We will be using an Upload! input type for that.

**Comment by bird-cage** [comment]
👍

**Comment by franmako** [comment]
Is this ready to be used ?
I can see the FileUpload utility class (in src/GraphQL/Utility/FileUpload.php), but I can't seem to find in the docs, how to use it.

**Comment by hunteryun** [comment]
Yes, I would also like to know how to use it

**Comment by Kingdutch** [comment]
The module implements the file upload specification since #818. I'm closing this in favour of #811 which can be used to track the task of updating the documentation.

**Comment by jcmiller09** [comment]
Why is there no documentation on how to implement file uploads within Mutations? Seems like since someone added it, it could be mentioned in the docs and the example code.
