### ISSUE TITLE
Attach views fields to matching types

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#82]
Views displays that expose a contextual argument of a certain entity type (argument validation options), should be attached to matching types.

Example:

```
fragment ArticleFragment on NodeArticle {
  title
  body
  relatedArticles {
    title
  }
}
```

**Comment by Leksat** [comment]
@fubhy @pmelab I work on tests, but you can already review my approach in #175.

**Comment by Leksat** [comment]
@pmelab as #175 got merged, this issue can be closed?

**Comment by pmelab** [comment]
Yes, this can be closed.
