### ISSUE TITLE
Expose views field displays

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#83]
We could generate types for field-based views displays, that work the same as types generated from entity displays. Rendering strings for all fields by default and using the same formatter based enhancers (`graphql_image`, `graphql_entity_reference` ...).

This could help with performance and exposing non-entity data (e.g. Solr results).

**Comment by fubhy** [comment]
Work in progress here: https://github.com/fubhy/graphql-drupal/pull/313
