### ISSUE TITLE
Class 'Drupal\language\LanguageNegotiationMethodBase' not found in /var/www/html/web/modules/contrib/graphql/src/Plugin/LanguageNegotiation/OperationLanguageNegotiation.php on line 19

### ISSUE THREAD

**Issue by Cryt1c** [drupal-graphql/graphql#834]
I get this fatal error on the current 8.x-4.x branch:
![image](https://user-images.githubusercontent.com/8447640/60395497-c6f41380-9b34-11e9-897a-a392a5cf6df0.png)

If I uncomment `extends LanguageNegotiationMethodBase` it works once again. Unfortunately I have no clue what could be wrong since this is available when navigating through the code:
`use Drupal\language\LanguageNegotiationMethodBase;`

Using Drupal version 8.7.3

Is this happening to someone else too?

**Comment by fubhy** [comment]
Whoops, same problem as we had a day ago with https://github.com/drupal-graphql/graphql/issues/833

Happens when the language module is not installed. I'll provide a fix in a few moments.
