### ISSUE TITLE
Unify test suites

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#84]
Move the `GraphQLFileTestTrait` to the root `graphql` module and somehow merge with the existing `QueryTestBase`.

**Comment by martinfrances107** [comment]
When I look at the  8.x-3.x branch

1) GraphQLFileTestTrait is in the root graphql module.
2) QueryTestBase in no longer in the branch?

If all the tasks have been resolved elsewhere ... then maybe this issue can be closed?

**Comment by pmelab** [comment]
I'm working on the testuite in this PR: https://github.com/drupal-graphql/graphql/pull/489
When it's merged we can close this ticket i guess.
