### ISSUE TITLE
Image styles no longer contain underscores

### ISSUE THREAD

**Issue by danielgittings** [drupal-graphql/graphql#841]
Hi there,

I've updated from 8.x-3.0-rc2 to 8.x-3.0-rc3 and noticed that image styles no longer contain underscores.

I've tested with a clean Drupal install (8.7.4) and a dummy image style.

The screenshots below show the difference that I'm seeing between 8.x-3.0-rc2 and 8.x-3.0-rc3.

#### 8.x-3.0-rc2
![Screenshot 2019-07-04 at 14 22 27](https://user-images.githubusercontent.com/7735084/60669831-33d61900-9e67-11e9-82de-a84a5dcd4efb.png)

#### 8.x-3.0-rc3
![Screenshot 2019-07-04 at 14 21 31](https://user-images.githubusercontent.com/7735084/60669839-39cbfa00-9e67-11e9-9a19-faaa94663f76.png)

Is this an intended change or a bug? Just wanted to check before I go forward with updating any queries.

**Comment by fubhy** [comment]
That sucks. Sorry about the BC break. It's not a bug though, just an unintentional, BC breaking change. Sorry about that!

**Comment by fubhy** [comment]
Changing it back again would probably be worse since the RC3 is also out for a while now. So I'd vote for keeping it without the underscores now and upgrade old queries accordingly. Again, sorry for that!
