### ISSUE TITLE
Example for entity_reference not working #1 (4.x)

### ISSUE THREAD

**Issue by alesbencina** [drupal-graphql/graphql#842]
Greetings,

first of all thank you for contribution.

I have enabled your module and tested it. But I cannot get the tags from article. I always get NULL. Do I do something wrong? What can I do to make it right? 
Bellow is my schema and resolvers which are already provided in example.

```
type Article implements NodeInterface {
    id: Int!
    uid: String
    title: String!
    render: String
    creator: String
    tags: [TagTerm]
}

type TagTerm {
    id: Int
    name: String
}
```

```
$registry->addFieldResolver('Article', 'tags',
      $builder->produce('entity_reference', [
        'mapping' => [
          'entity' => $builder->fromParent(),
          'field' => $builder->fromValue('field_tags'),
        ],
      ])
    );

    $registry->addFieldResolver('TagTerm', 'id',
      $builder->produce('entity_id', ['mapping' => [
        'entity' => $builder->fromParent(),
      ]])
    );
```
```
{
      "message": "Missing input mapper for argument entity.",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "articles",
        "items",
        0,
        "render"
      ]
    },
```

**Comment by fubhy** [comment]
Hi, can you test this with the code from the actual example module? This should work: https://github.com/drupal-graphql/graphql/blob/8.x-4.x/examples/src/Plugin/GraphQL/Schema/ExampleSchema.php

You can just enable the example module to try it out.

**Comment by fubhy** [comment]
I updated the documentation accordingly.

**Comment by hirani89** [comment]
Hi,

How were you able to get this working. The link provided does not work. I am using example code provided in the module. But I can not get it working.
