### ISSUE TITLE
Get body value, formatter, summary from formatted text field (4.x)

### ISSUE THREAD

**Issue by alesbencina** [drupal-graphql/graphql#843]
Greetings,

amazing work for 4.x version so far!

Can we add some example to documentation how to get values from body field which has value, format, summary please?

**Comment by fubhy** [comment]
Hi there

There already are examples for how to access nested field properties. You can do that through the generic typed data property path plugin:

```
$registry->addFieldResolver('Article', 'foo',
  $builder->produce('property_path')
    ->map('type', $builder->fromValue('entity:node'))
    ->map('value', $builder->fromParent())
    ->map('path', $builder->fromValue('field_foo.value'))
);
```

Note the `field_foo.value` path.

**Comment by jordonedavidson** [comment]
Tried this: 
```
$registry->addFieldResolver('Article', 'body',
        $builder->produce('property_path')
          ->map('type', $builder->fromValue('entity:node'))
          ->map('value', $builder->fromParent())
          ->map('path', $builder->fromValue('body.value'))
    );
```

It results in the error `"Cannot return null for non-nullable field Article.body."`

Perhaps a more detailed explanation is in order?

**Comment by alesbencina** [comment]
@jordonedavidson do you have field body as String! in schema?

**Comment by fubhy** [comment]
Correct. If String! (required string output) is set in the schema (note the exclamation mark) it HAS to be returned at least as an empty string.

```
$builder->produce('property_path')
          ->map('type', $builder->fromValue('entity:node'))
          ->map('value', $builder->fromParent())
          ->map('path', $builder->fromValue('body.value'))
```

This returns `NULL` if there is no body field or the body field has never had any date stored in it. You could set a breakpoint (xdebug) in the PropertyPath data producer to check why it returns NULL. 

https://github.com/drupal-graphql/graphql/blob/8.x-4.x/src/Plugin/GraphQL/DataProducer/TypedData/PropertyPath.php#L49

**Comment by fubhy** [comment]
Please open a new issue specific to your problem if this doesn't help you find the answer yet!

**Comment by jordonedavidson** [comment]
Ah, well that does make sense. I misunderstood String! to be "String or Null" not "Must be string".

It is returning things correctly now. 

I think it would be a good addition to the examples to add comments explaining what each line is doing to make it more clear what we need to do to build our own queries. 

Thanks for the quick turnaround.
