### ISSUE TITLE
Enforce GraphQL view mode for entities

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#86]
Instead of falling back to default view mode, only include entity types with a `graphql` view mode in the schema.

Also auto-add this view mode for all entities.

**Comment by pmelab** [comment]
@fubhy Another option: We could make the "graphql view mode" configurable per bundle. With an option for "don't expose". That feels more explicit and intuitive than hiding entity types when a certain view mode is not present.

**Comment by fubhy** [comment]
Yes that makes sense.

**Comment by yann-yinn** [comment]
Hello ! that's make sense for me as a site builder to have an explicit "graphql" display mode for entities, and use it to expose or hide fields in the outputted Json. Keep up the great work,  having graphql on D8 can make it a very good choice to use it as a backoffice !
