### ISSUE TITLE
menuByName doesn't not return translated name label.

### ISSUE THREAD

**Issue by sixtyniner-official** [drupal-graphql/graphql#862]
Drupal: 8.7.1
GraphQl: Version: 8.x-3.0-rc3

Seems like query **menuByName** doesn't return translated menu **name** and description labels, only **links**.

I have translated menu:

![tranlsated-menu](https://user-images.githubusercontent.com/14074280/62131268-2469b480-b2db-11e9-9f1e-05a406fb2101.png)

and following queries:

**EN**

![EN](https://user-images.githubusercontent.com/14074280/62131390-67c42300-b2db-11e9-8857-f3aa2c159151.png)

**DE**

![DE](https://user-images.githubusercontent.com/14074280/62131405-6e529a80-b2db-11e9-8016-336fbc318c24.png)

As you can see name and description is not translated in GraphQL response.

Reference: https://github.com/drupal-graphql/graphql/commit/cda8bc5f3d94cbf0bca4db06e8675e2e4a22f97e#diff-516746c704da2fcf4b1208b2b84b81dc

@fubhy

**Comment by JohnAlbin** [comment]
This has already been fixed in the -dev version.  #773

**Comment by sixtyniner-official** [comment]
Thank you @JohnAlbin, a ticket can be closed.
