### ISSUE TITLE
How to enable the `DisableIntrospection` validation rule

### ISSUE THREAD

**Issue by davidwhthomas** [drupal-graphql/graphql#866]
I'd like to restrict schema introspection to a whitelist of IP addresses.

The `DisableIntrospection` rule was added to webonyx here https://github.com/webonyx/graphql-php/pull/131/files

and documented here https://github.com/webonyx/graphql-php/blob/master/docs/security.md#disabling-introspection

Just wondering on the recommended way to add that validation rule (and potentially other validation rules) during query execution time to `drupal-graphql`.

If not possible add during execution, just the recommended way to enable addition query validation rules.

Some relevant code in `SchemaPluginBase` with `$config->setValidationRules` - perhaps need to override the schema to add somehow?

**Comment by davidwhthomas** [comment]
Updating to add this approach appears to work, with the custom schema plugin:

```
<?php

namespace Drupal\MODULE\Plugin\GraphQL\Schemas;

use GraphQL\Language\AST\DocumentNode;
use GraphQL\Server\OperationParams;
use GraphQL\Server\ServerConfig;
use GraphQL\Validator\DocumentValidator;
use GraphQL\Validator\Rules\DisableIntrospection;
use GraphQL\Validator\Rules\QueryComplexity;
use GraphQL\Validator\Rules\QueryDepth;
use Drupal\graphql\Plugin\GraphQL\Schemas\SchemaPluginBase;
use Drupal\MODULE\Plugin\Deriver\PublicSchemaDeriver;

/**
 * Generated GraphQL schema for public access.
 *
 * @GraphQLSchema(
 *   id = "public",
 *   name = "Public GraphQL schema",
 *   path = "/api/graphql/public",
 *   deriver = "Drupal\MODULE\Plugin\Deriver\PublicSchemaDeriver",
 * )
 */
class PublicSchema extends SchemaPluginBase {

  /**
   * Get schema server configuration
   */
  public function getServer() {
    // Get default server config from parent base
    $config = parent::getServer();
    // Add default and extra validation rules
    $config->setValidationRules(function (OperationParams $params, DocumentNode $document, $operation) {
      // Query already validation when using persistent ID
      if (isset($params->queryId)) {
        return [];
      }
      // Default rules
      $rules = array_values(DocumentValidator::defaultRules());
      // Extra validation
      $extra_rules = array_values($this->getExtraValidationRules());
      return array_merge($rules, $extra_rules);
    });

    return $config;
  }

  /**
   * Additional validation
   * @see  https://github.com/webonyx/graphql-php/blob/master/docs/security.md
   * @return array
   */
  private function getExtraValidationRules() {
    // These setting values can also be configurable to enable/disable or tweak.
    return [
      DisableIntrospection::class => new DisableIntrospection(),
      QueryDepth::class => new QueryDepth(10),
      QueryComplexity::class => new QueryComplexity(200),
    ];
  }

}
```

In addition, I used a custom schema deriver to limit the included items, however without introspection, the default schema and associated access control may be sufficient.

**Comment by fubhy** [comment]
Yes, this is the right approach. In 4.x it works similar and is also possible through the schema / server instance. But for 3.x this is absolutely right.

**Comment by akhomy-jq** [comment]
Hey @fubhy , still, I don't know if it is similar in 4.x. The server is executed through the controller and Drupal wrapper of the server. I guess, to implement rules it is required to override Entity/Server.php or every request in RequestController.php. Which isn't flexible. 

Correct me if I'm wrong.

**Comment by klausi** [comment]
fubhy is not maintaining graphql module anymore, so won't have time to answer here.

I think we should build a config option directly into the graphql server entity. Then implement https://webonyx.github.io/graphql-php/security/#disabling-introspection when it is set. Every Drupal production site should disable introspection, since that can come up in security audits otherwise.
