### ISSUE TITLE
Error handling in case of invalid querymap id

### ISSUE THREAD

**Issue by tguilpain** [drupal-graphql/graphql#868]
I am getting a lot of the following error when Front End requests for queries on querymap that does not exist
```PHP message: Uncaught PHP Exception LogicException: "The persisted query loader must return query string or instance of GraphQL\Language\AST\DocumentNode but got: null." at /var/www/drupalvm/docroot/modules/contrib/graphql/src/GraphQL/Execution/QueryProcessor.php line 434```
As per fubhy, we should use Error and RequestError instead of \LogicException in order to return a normal graphql response with an "error" field.

**Comment by fubhy** [comment]
Thanks!
