### ISSUE TITLE
Raw field data formatter

### ISSUE THREAD

**Issue by pmelab** [drupal-graphql/graphql#87]
Add a special field formatter that exposes raw field data in GraphQL.
We will require type and field derivers that generate types for all configured field types.

**Comment by shawnmmatthews** [comment]
Is the idea of this to strip the html before it gets to Graphql regardless of the D8 theme?

I've been currently handling this using a function to generate a new stipped version of props in React (or worse dangerously setting innerhtml if its more practical). It would be super helpful to be able to do this prior to sending everything over via field formatting from the UI.

Is there currently a better way of handling this?

**Comment by pmelab** [comment]
This feature is actually *about* getting non-sanitised values. **Not** using it (and therefore receiving the rendered field) will invoke Drupal filters and should - depending on your text formats configuration - already return safe values.

So you probably won't use this on a rich text field, but on something more complex like address fields, as discussed in #144.
