### ISSUE TITLE
How to modify the GraphQL schema definition?

### ISSUE THREAD

**Issue by Kwadz** [drupal-graphql/graphql#873]
I’d like to use [Apollo Federation][1] to federate multiple GraphQL schemas including a Drupal 8 one.

As I understood, we need to modify the schema definition, to add the [@key directive](https://www.apollographql.com/docs/apollo-server/federation/core-concepts/#entities-and-keys). I’m wondering how to do it with a Drupal GraphQL schema.

I saw in [this issue](https://github.com/drupal-graphql/graphql/issues/677) that we can define our own schema using SDL (Schema Definition Language).

How to modify the schema definition for example to add the `@key` directive?

  [1]: https://www.apollographql.com/docs/apollo-server/federation/introduction/

**Comment by fubhy** [comment]
For that you would have to use version 4.x of this module, develop your own schema and then define the directives and use them like so: https://www.apollographql.com/docs/apollo-server/features/directives/

You cannot do this in 3.x.

**Comment by fubhy** [comment]
https://drupal-graphql.gitbook.io/graphql/v/8.x-4.x/getting-started/custom-schema

**Comment by fubhy** [comment]
bc
