### ISSUE TITLE
Stable 3.x release?

### ISSUE THREAD

**Issue by mike-potter** [drupal-graphql/graphql#876]
We have a client using the 3.x-rc3 version of the GraphQL module (which has been very very helpful).  This client is launching in a couple months and is auditing their contrib modules for security coverage.  Is there any chance of getting a 3.0 stable release covered by Drupal security policy soon while you continue to make improvements in the 4.x branch?

**Comment by fubhy** [comment]
Hi @mike-potter,

That's a good question. I think we should do a stable release indeed but there are still open issues that we'd like to solve before doing that and since none of us (the maintainers) currently has a 3.x project we are a bit short on time to work on that. @klausi any chance you can help out here? What are your thoughts? Should we just tag a stable release? We've been on RCs for quite a while now. I'd like to fix at least the entity query information disclosure problem that was raised a few weeks ago before we tag the stable release. Anything else can happen in 3.1 I'd say ...

**Comment by klausi** [comment]
Yep, I would release as soon as possible.

If you tag 3.0 now without the entity query security fix then 3.1 will have to be a security release I think? At least then users get a notification that they must update.

On the other hand releasing 3.0 with a known security issue is not a good look. It depends how fast you can roll a fix for that?

**Comment by fubhy** [comment]
https://github.com/drupal-graphql/graphql/pull/877

That should fix the problem. I don't have a running 3.x site. Can someone quickly validate that this works as expected? (Does not allow comparison / wildcard operators except when logged in as admin or when the "bypass field security" permission is set).

**Comment by mike-potter** [comment]
Yeah, please do not release with a known security issue ;)

**Comment by fubhy** [comment]
@mike-potter It's actually not as bad as it sounds. There are compelling benefits of actually doing the opposite and releasing with the security issue and then directly releasing the fix as that would cause the security notification system to kick in and notify all users of the module that they should upgrade. Whereas if we don't do that it might look better to the outside but is actually arguably worse.

**Comment by fubhy** [comment]
In our specific special case since we are currently not covered by the d.o security policy and security team (because we don't have a single stable release yet) we do not get that automatically which is a bummer.

**Comment by mike-potter** [comment]
Just speaking from experience that once it is stable then you'll have to go through the full security team process which might be slower than just fixing it now if you have a fix. You'd have to move the issue into a non-public place and deal with the fact that it's a known public issue already.  Just makes it messy imho.  The whole purpose of alpha, beta, rc is to be able to fix those kind of things more quickly.

It's possible to coordinate with the security team to still flag the 3.0 stable release as a "security fix" even with no SA or private issue and then sites using the module will see the security update status in their reports.  Feel free to email the security team with questions on this (I'm a member of the team but currently on hiatus so can't really give an official answer)

**Comment by klausi** [comment]
@mike-potter unfortunately that is not correct, the security team does not do security releases for the first security team supported release. So there will be no update status security notification for 3.0. See https://groups.drupal.org/node/535107 for background info.

The security team only flags a release as security update if there is an advisory to not cause confusion.

**Comment by fubhy** [comment]
Both options are on the table: 

- Release now with the fix (see pull request, pending testing / confirmation from @pmelab or someone else)

- Release without the fix and release 3.1 right afterwards.

I don't feel strongly for either of the two options. Both are fine for me.

**Comment by fubhy** [comment]
I'd defer the decision to @klausi and @pmelab as I am not actively using 3.x either (I know that @klausi isn't too but at least he has the experience for security releases ;-) )

**Comment by mike-potter** [comment]
Yep, I defer to @klausi on this as he has more experience than I.

**Comment by fubhy** [comment]
@klausi @pmelab can one of you check out the pull request I opened?

**Comment by klausi** [comment]
Done, reviewed #877 , but we should check field access if we can somehow.

**Comment by klausi** [comment]
3.0 has been released, yay!

Closing this.
