### ISSUE TITLE
Find day and time for recurring contributor meeting.

### ISSUE THREAD

**Issue by fubhy** [drupal-graphql/graphql#88]
We used to have a weekly meeting. Let's bring that back now that we've picked up traction again. We are actively working on numerous features and improvements and want to get to a stable 3.x release asap. Obviously, we are looking for additional contributors, too. Let us know when would be a good time for you.

For me, I could free up time at any week day between 2PM and 3PM UTC.

**Comment by fgm** [comment]
The previous saturday 11:30-12:30 UTC schedule is just fine for me. Weekdays won't be possible, working on customer sites.

**Comment by fubhy** [comment]
At the beginning of this year, I've made a pledge (for myself) to not force work on me on weekends. So Saturday sadly doesn't work for me, sorry :(.

**Comment by pmelab** [comment]
Saturday is problematic for me too 😦

**Comment by dawehner** [comment]
Random idea: automatic reverts of github commits based upon the time of commit.

**Comment by alesrebec** [comment]
Thursdays
2:00 PM - 2:30 PM (CET) ?

**Comment by fubhy** [comment]
Thursday would work for me.

**Comment by fubhy** [comment]
Okay I think I'll just make the call then... Thursday 3:00 PM - 3:30 PM (CET). This will allow people in the US to join us too. If you are interested in joining, please send me your e-mail address for the google calendar invite to "sebastian (at) amazeelabs.com".

**Comment by fubhy** [comment]
We will start with these meetings next Thursday (June 1st).
