### ISSUE TITLE
4.x: How to get field value from Menu Item

### ISSUE THREAD

**Issue by justin-longbottom** [drupal-graphql/graphql#881]
I defined the schema, [as per this doc](https://drupal-graphql.gitbook.io/graphql/v/8.x-4.x/queries/menus), and now I want to add a field that appears on each menu item.

```
// Menu item icon.
    $registry->addFieldResolver('MenuItem', 'icon',
      $builder->produce('property_path')
        ->map('type', $builder->fromValue('entity:menu_link_content'))
        ->map('value', $builder->fromParent())
        ->map('path', $builder->fromValue('field_icon_menu.value'))
    );
```
I tried this, but it is not working. Any suggestions?

**Comment by fubhy** [comment]
Did you also define the field in the Schema file (SDL)? Can you paste your Schema here too?

**Comment by justin-longbottom** [comment]
Schema - again, taken from the docs as-is. All I did was add `icon: String`

```
schema {
  query: Query
}

type Query {
  menu(name: String!): Menu
}

type Menu {
  name: String!
  items: [MenuItem]
}

type MenuItem {
  title: String!
  url: Url!
  icon: String
  children: [MenuItem]
}

type Url {
  path: String
}

```

**Comment by fubhy** [comment]
@justin-longbottom That looks correct. Can you elaborate a bit more what "it doesn't work" means? Are you getting any errors? Is the field not showing up in the schema? Did you maybe not clear the cache after making these changes? Note that there is a "enable caching" and "enable development mode" checkbox on the server configuration. Remove the checkmark at "enable caching" and enable development for the best dev experience.

**Comment by justin-longbottom** [comment]
The field appears in the schema, but I always get `NULL` as the icon value, despite the field being populated on several menu items. I tried clearing the cache too and also changing those server settings.

query
```
{
  menu(name: "main") {
    name
    items {
      title
      icon
      url {
        path
      }
    }
  }
}
```

results
```
{
  "data": {
    "menu": {
      "name": "Main navigation",
      "items": [
        {
          "title": "Home",
          "icon": null,
          "url": {
            "path": "/us/en/"
          }
        },
        {
          "title": "Test",
          "icon": null,
          "url": {
            "path": "/us/en/"
          }
        }
      ]
    }
  }
}
```

**Comment by fubhy** [comment]
Did you try to set a breakpoint with xdebug in the property_path plugin? You can also set breakpoints in the local compose chain like so:

```
// Menu item icon.
    $registry->addFieldResolver('MenuItem', 'icon',
      $builder->compose(
        $builder->tap($builder->callback(function ($parent) {
           echo('Set a breakpoint here (before plugin execution)');
        })),
        $builder->produce('property_path')
          ->map('type', $builder->fromValue('entity:menu_link_content'))
          ->map('value', $builder->fromParent())
          ->map('path', $builder->fromValue('field_icon_menu.value')),
        $builder->tap($builder->callback(function ($parent) {
           echo('Set a breakpoint here (after plugin execution)');
        }))
    );
```

**Comment by justin-longbottom** [comment]
`Unable to apply data selector 'field_icon_menu.value' at 'field_icon_menu': Unable to get unknown property field_icon_menu.`

Is `entity:menu_link_content` the correct type?

**Comment by justin-longbottom** [comment]
Fo what its worth, I have no issue pulling in field values from nodes, but menu items do not seem to work with `property_path`.

**Comment by fubhy** [comment]
I will give it a try myself and report back tomorrow. Not at my laptop currently.

**Comment by fubhy** [comment]
@justin-longbottom the answer is that the menu_links producer does not return an array of menu_link_content entities but a list of MenuLinkTreeElement objects. Menu links are not necessarily based on entities. They can be based on route config, etc.. Hence, you need to build more sophisticated logic (a custom data producer), to get your icons. The data producer would have to conditionally load the menu_link_content entity from the MenuLinkTreeElement if (and only if) it is even based on an entity.

**Comment by fubhy** [comment]
Also check out the Menu related data producer plugins in this module to get an idea of what's happening:

https://github.com/drupal-graphql/graphql/tree/8.x-4.x/src/Plugin/GraphQL/DataProducer/Menu

**Comment by justin-longbottom** [comment]
@fubhy  Thanks for the help!

For anyone else, here was my solution:

Schema
```
$registry->addFieldResolver('MenuItem', 'icon',
      $builder->produce('menu_link_icon')
        ->map('content', $builder->produce('menu_link_content')
          ->map('link', $builder->produce('menu_tree_link')
            ->map('element', $builder->fromParent())
        )));
```

Menu Link Content producer
```
public function resolve(MenuLinkInterface $link) {
    $uuid = $link->getDerivativeId();
    if ($uuid) {
      return \Drupal::entityManager()->loadEntityByUuid('menu_link_content', $uuid);
    }
    return NULL;
  }
```

Menu Link Icon producer
```
public function resolve(MenuLinkContent $content) {
    return $content->field_icon_menu->value;
  }
```
