### ISSUE TITLE
403 error on postman request

### ISSUE THREAD

**Issue by luismareze** [drupal-graphql/graphql#888]
hi, I am trying to use the graphql query on my postman.

1- I send a post query to create a new token via oauth2
2- I send a post graphql query using the bearer token on header.

All the persmission are enable on my admin but I still getting a 403 error on my request. Anyone can help me?

![image](https://user-images.githubusercontent.com/13120053/63480916-20f4c380-c46a-11e9-8448-624a518600e1.png)

**Comment by fubhy** [comment]
Does the user you are logging in with have access (configure permissions) for the graphql endpoint?

**Comment by fubhy** [comment]
Nevermind, didn't see the  last line before the screenshot. 

Regarding authentication: This module does not have any custom logic for handling that. If you can run requests against your Drupal instance with the login flow you described then it will work here too. Have you tried sending requests to postman for other URLs on your website that require authentication? If those work, then the one for the graphql endpoint also works assuming that you've set the permissions accordingly.
