### ISSUE TITLE
Is there a generic "default schema" module?

### ISSUE THREAD

**Issue by mglaman** [drupal-graphql/graphql#903]
I'm aware that the 4.x branch makes no assumptions on your GraphQL schema, whereas 3.x provided a generic schema for existing Drupal entity structures. I understand this decision and I think it makes sense; however, this can make the initial onboarding a bit difficult.

I'm working on some content for Drupal as an API platform and I want to cover the GraphQL module. The problem is that it has a bit of an "install & go" problem to explain without also having to and cover writing schemas in depth.

I was just wondering if there is a plan or thought to create a `graphql_defaults` module or something which adds the 3.x schema for 4.x.

**Comment by fubhy** [comment]
As discussed in slack the other day there's currently not.

I am very open to accepting a pull request that adds a basic, derived schema based on the available entity types. Maybe even exposing some configuration to adjust it a bit. For now, this is not planned to be done by me or the other maintainers (afaik) though as the whole point of this module is actually to make it easy for everyone to build a custom schema according to the exact requirements of the API. A generic schema is somewhat against that idea. That said, however, I would totally be open to accepting a sub-module that adds this.
