### ISSUE TITLE
nodeQuery unable to filter by language

### ISSUE THREAD

**Issue by d0190535** [drupal-graphql/graphql#906]
I am using nodeQuery but I am unable to query the specific node id by language.
The example below is just a simple demo of what I am seeing, the actual query is a lot more complicated and thus I cannot use NodeById.

![image](https://user-images.githubusercontent.com/1388438/66233573-8e6a5580-e6a0-11e9-869a-ce4518c3cc78.png)

The nid 6586 has multiple languages published and for some reason it always returns the en-gb and not what I specified in the query.
![image](https://user-images.githubusercontent.com/1388438/66233596-a04bf880-e6a0-11e9-90b3-751d0b27b465.png)

It appears to be a bug but is there any workaround for this?  Thanks

**Comment by d0190535** [comment]
It appears that it only pulls the entity by the website's default language.  Is there any way to fix this?  Thanks

**Comment by fubhy** [comment]
This is not a bug. You are querying for entities that HAVE a translation of that language, but then you are not actually fetching the translation, just the default. The "entities"  field has an argument for "translation" or "language". Use the same value as in the filter there ("zh-hans") and you get the xpected result.

**Comment by d0190535** [comment]
> This is not a bug. You are querying for entities that HAVE a translation of that language, but then you are not actually fetching the translation, just the default. The "entities" field has an argument for "translation" or "language". Use the same value as in the filter there ("zh-hans") and you get the xpected result.

Thanks.  Is there anyway to fetch the "translated" entity for all its fields?  Similar to how the language filter with NodeQueryById works?
