### ISSUE TITLE
Schema is not configured for mutations

### ISSUE THREAD

**Issue by lhguerra** [drupal-graphql/graphql#908]
I'm getting this message when trying to run a mutation in the explorer. In the docs tab, mutations are not shown either. I saw in the release notes something about deprecating automatic mutations, but shouldn't my custom ones be accessible?

**Comment by fubhy** [comment]
What version of the module are you using?

**Comment by lhguerra** [comment]
Boy I'm distracted these days :sweat_smile: 

I'm using 8.x-3.0-rc3

**Comment by lhguerra** [comment]
If it helps, I created an example repository https://github.com/lhguerra/drupal-graphql-mutations-test

It is built with a boilerplate that depends on Docker, Docker-compose and Make. If you need an example without these dependencies I can work on that.

**Comment by lhguerra** [comment]
@fubhy if it helps, I created an example repository https://github.com/lhguerra/drupal-graphql-mutations-test

It is built with a boilerplate that depends on Docker, Docker-compose and Make. If you need an example without these dependencies I can work on that.

**Comment by lhguerra** [comment]
Nvm, my declaration was mistaken. Sorry wasting your time.
