### ISSUE TITLE
I want to query webform fields titles and options for the for select

### ISSUE THREAD

**Issue by odm275** [drupal-graphql/graphql#914]
I want to be able to query the element titles from my contact webform. Ex: For my contact webform, I want to query Name(text field), Email(text field), Help(select). Such that, I can build a form from this in my front-end.

First I tried to query the webform by nodeid, and now via graphql_webform apis.
Right now I installed the [graphql_webform](https://github.com/duartegarin/graphql_webform) module, and tried the following:
```
{
  webformById(webform_id: "contact") {
    webform {
      reverseWebformIdWebformSubmission{
        entities{
          entityBundle
        }
      }
    }
  }
}
```
But I keep getting errors like
```
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "webformById",
        "webform",
        "reverseWebformIdWebformSubmission"
      ]
    }
  ],
  "data": {
    "webformById": {
      "webform": null
    }
  }
}
```
Cannot return null for non-nullable field Webform.reverseWebformIdWebformSubmission.
--

I'm also trying something like:
```
{
  nodeById(id: "16") {
    ...ContactUs
  }
}

fragment ContactUs on NodeWebform {
  title
  body {
    value
  }
  webform{
    entity{
      entityAccess
    }
  }
}

fragment ContactUsWebform on Webform{
  elements{
    keys
  }
}
```
But can't quite get to the webform fields.

Help is highly appreciated.

**Comment by fubhy** [comment]
Sorry I have no experience with that module at all. Have you tried contacting the maintainer of graphql_webform?

**Comment by fubhy** [comment]
Please try to reach out to @duartegarin directly.
