### ISSUE TITLE
How to load a single entity from an entity reference field?

### ISSUE THREAD

**Issue by Kwadz** [drupal-graphql/graphql#922]
[The entity reference data producer](https://drupal-graphql.gitbook.io/graphql/v/8.x-4.x/data-producers/built-in#entity-reference-data-producers) is used to load entities from an entity reference field.

[An example](https://drupal-graphql.gitbook.io/graphql/v/8.x-4.x/queries/references) in the documentation show us how to use it to get the _tags_ of an _article_.

But this returns an array. How to load a single entity from a field?
For example when we limit to 1 the allowed number of values and define the following schema:

```
type Article implements NodeInterface {
    id: Int!
    title: String!
    creator: String
    tag: TagTerm
}
```

**Comment by gnikolovski** [comment]
For single entity reference fields you can do this:

```
$registry->addFieldResolver('Article', 'category',
   $builder->produce('property_path')
     ->map('type', $builder->fromValue('entity:node'))
     ->map('value', $builder->fromParent())
     ->map('path', $builder->fromValue('field_category.entity'))
);
```

**Comment by Kwadz** [comment]
Works perfectly! Thanks @gnikolovski.
