### ISSUE TITLE
GraphiQL Explorer Whitescreen

### ISSUE THREAD

**Issue by justinlevi** [drupal-graphql/graphql#944]
Seeing the following error recently on a project

```
drupal.js?v=8.7.9:13 Uncaught Error: Must provide Array of types or a function which returns such an array for Union ViewResult.
    at n (bundle.min.js?v=8.7.9:1)
    at C (bundle.min.js?v=8.7.9:1)
    at e.getTypes (bundle.min.js?v=8.7.9:1)
    at o (bundle.min.js?v=8.7.9:1)
    at Array.reduce (<anonymous>)
    at new e (bundle.min.js?v=8.7.9:1)
    at i (bundle.min.js?v=8.7.9:1)
    at Object.attach (bundle.min.js?v=8.7.9:1)
    at drupal.js?v=8.7.9:25
    at Array.forEach (<anonymous>)
n @ bundle.min.js?v=8.7.9:1
C @ bundle.min.js?v=8.7.9:1
e.getTypes @ bundle.min.js?v=8.7.9:1
o @ bundle.min.js?v=8.7.9:1
e @ bundle.min.js?v=8.7.9:1
i @ bundle.min.js?v=8.7.9:1
attach @ bundle.min.js?v=8.7.9:1
(anonymous) @ drupal.js?v=8.7.9:25
Drupal.attachBehaviors @ drupal.js?v=8.7.9:22
(anonymous) @ drupal.init.js?v=8.7.9:16
t @ ready.min.js?v=1.0.8:4
setTimeout (async)
Drupal.throwError @ drupal.js?v=8.7.9:12
(anonymous) @ drupal.js?v=8.7.9:27
Drupal.attachBehaviors @ drupal.js?v=8.7.9:22
(anonymous) @ drupal.init.js?v=8.7.9:16
t @ ready.min.js?v=1.0.8:4
```

Debug mode is switched on and I'm not seeing anything else in the console. I'll keep digging in to try and figure out what's wrong with the schema. 

Any tips or help on how to debug this is greatly appreciated.

**Comment by justinlevi** [comment]
Quick update, I don't think this has anything to do with our codebase specifically as I'm seeing this issue doing `drush --yes site-install standard` and enabling 
* GraphQL 8.x-3.0
* GraphQL Core 8.x-3.0
* GraphQL Twig 8.x-1.0-beta13
* GraphQL Views 8.x-1.0

**Comment by justinlevi** [comment]
Hmm, seems to be an issue with graphql_views. Reverting back to beta2 fixes the issue. I'll move the conversation over there.

**Comment by Dhoot** [comment]
Facing the same issue any update on it ?

**Comment by seismicmike** [comment]
I started from a minimal install and everything was fine until I installed Taxonomy. After I did that, GraphiQL broke. When I uninstalled Taxonomy again, GraphiQL came back.

**Comment by tranepura** [comment]
i had the same issue and  uninstalling  graphql_views module ("drupal/graphql_views": "^1.0") resolved it .

**Comment by urbgimtam** [comment]
@tranepura Thanks, this saved my life.
