### ISSUE TITLE
Documentation change from 3.0 to 4.0

### ISSUE THREAD

**Issue by Thommusa** [drupal-graphql/graphql#960]
Hello
Is there any documentation about what does it change seens the version 3.0 to 4.0 ?
I create lot of plugin field and deriver and I would like to know if it's compatible with 4.0

**Comment by Kingdutch** [comment]
Hi @Thommusa ,

The project page contains an explanation of the differences. I hope you've been able to find an answer since posting this issue. If you have more questions, please let us know.
