### ISSUE TITLE
nodeQuery internal server error

### ISSUE THREAD

**Issue by ormarek** [drupal-graphql/graphql#961]
Just did fresh drupal install (v. 8.8.1) installed everything and the only thing that is not working properly is nodeQuery which causes internal server error when fetched by apollo.
The only way I found to make it work is to select Bypass field security.
Do you have any other solution?

Steps to reproduce:
Fresh install drupal 8.8.1, install webonyx/graphql-php, install drupal-graphql, enable it, fetch nodeQuery with apollo

**Comment by fabianderijk** [comment]
> Just did fresh drupal install (v. 8.8.1) installed everything and the only thing that is not working properly is nodeQuery which causes internal server error when fetched by apollo.
> The only way I found to make it work is to select Bypass field security.
> Do you have any other solution?
> 
> Steps to reproduce:
> Fresh install drupal 8.8.1, install webonyx/graphql-php, install drupal-graphql, enable it, fetch nodeQuery with apollo

We've got the same issue. Is there any progress or solution?

**Comment by ormarek** [comment]
So far had no time to investigate it further so just kept bypass option on :/

**Comment by fabianderijk** [comment]
can you elaborate on your bypass option? What did you do to make it work anyhow?

**Comment by ormarek** [comment]
> can you elaborate on your bypass option? What did you do to make it work anyhow?

So in the People > Permissions you have this "Bypass field security" option. I just selected it for user and anonymous.
