### ISSUE TITLE
Clarify documentation for custom producers

### ISSUE THREAD

**Issue by Kwadz** [drupal-graphql/graphql#962]
The documentation states at the bottom of [Custom producers page](https://drupal-graphql.gitbook.io/graphql/v/8.x-4.x/data-producers/custom):

> (For this to actually work we would need to add resolves to the User object to resolve the id and name properties).

Do you mean "resolvers" instead of "resolves"?

**Comment by Kwadz** [comment]
Of course it is... 
I've just made a PR to fix the typo, see #963.

**Comment by Kwadz** [comment]
> add resolvers to the User object

By the way, can someone clarify this? Which `User` object are we talking about here?

**Comment by joaogarin** [comment]
Yes that is indeed a typo. its resolvers : https://drupal-graphql.gitbook.io/graphql/v/8.x-4.x/data-producers/producers#add-the-resolver

Regarding the sentence : 

> (For this to actually work we would need to add resolves to the User object to resolve the id and name properties).

Yes every field needs to have a resolver, nothing automatically maps to anything. so one would have to add the `id` and `name` resolver for the example to actually work and return data for the id and name there (maybe the sentence just ads confusion)

Welcome any suggestions in making that clearer, feel free to add it to the existing PR. its always good getting a fresh set of eyes in the docs, unfortunately haven't had a whole lot of time to improving it. But it+s on the agenda.

**Comment by joaogarin** [comment]
Closed in https://github.com/drupal-graphql/graphql/pull/963
