### ISSUE TITLE
How to add resolvers to the Root Value

### ISSUE THREAD

**Issue by nathanharper** [drupal-graphql/graphql#973]
I'm using the alpha3, and I need to implement federation so that I can connect via ApolloGateway. I'm using this package, and trying to follow along with the example in the README:

https://github.com/pascaldevink/php-graphql-federation

You'll notice there are two steps. The first is calling `extendSchema`. I was able to get this working by copying the example, extending SdlSchemaPluginBase and overriding the `getSchema` method. This seems to be working, insofar as i see the `_service` property added to the root query.

The second step is calling `addResolversToRootValue`, but it's unclear to me how I can override the default for this. Any suggestions?

**Comment by nathanharper** [comment]
just so people don't need to click through, here's teh code snippet:
```
# First, build your existing schema
$existingSchema = BuildSchema::build(file_get_contents(__DIR__ . '/schema.graphqls'));

# Then, extend it with Federation
$federation = new \PascalDeVink\GraphQLFederation\Federation();
$schema = $federation->extendSchema($existingSchema);

# Build your root value resolver
$rootValue = include __DIR__ . '/rootvalue.php';

# And extend it with Federation resolvers
$rootValue = $federation->addResolversToRootValue($rootValue);

# Finally, execute the query
GraphQL::executeQuery($schema, $query, $rootValue, null, $variableValues);
```

**Comment by nathanharper** [comment]
It seems like I was able to accomplish this by overriding the class used for the `graphql.executor` config, but it still didn't work with our gateway so I gave up and went back to schema stitching 🎉 😂

**Comment by fubhy** [comment]
Let's open a follow-up to add support for https://github.com/pascaldevink/php-graphql-federation

**Comment by fubhy** [comment]
... Or just re-open and re-purpose this.
