### ISSUE TITLE
Persisted Query fails

### ISSUE THREAD

**Issue by d0190535** [drupal-graphql/graphql#987]
I am trying to use the graphql-apq module for persisted query.  I followed the docs here https://www.drupal.org/docs/8/modules/graphql/query-maps to create query map and got the id for generated hash.

When I tried to query with it I kept getting the following error:
`Uncaught PHP Exception LogicException: "The persisted query loader must return query string or instance of GraphQL\Language\AST\DocumentNode but got: null." at /mnt/www/html/iqairdrupal8dev/docroot/modules/graphql/src/GraphQL/Execution/QueryProcessor.php line 434`

Any ideas on where I went wrong with the setup?

**Comment by d0190535** [comment]
I was able to get this to work.  Closing.

**Comment by christoz** [comment]
> I was able to get this to work. Closing.

Would you like to share some info on how you got this to work?

**Comment by d0190535** [comment]
> > I was able to get this to work. Closing.
> 
> Would you like to share some info on how you got this to work?

I don't recall what the exact issue was but it had to do with me saving the graphql query incorrectly.  It was a format / file type issue.

**Comment by kwiechmann** [comment]
Have seen this error when trying to call a non-existent persisted query.

**Comment by prineshaz** [comment]
In my case, i had to suffix the map key set in the config (config is created when you import the extracted query). You can find the config object in: 

1. Go to /admin/config/development/configuration/single/export
2. Select 'Query Map'
3. Select imported query (should be a generated hash, i used a human readable machine name)

Inspect the map key. Then modify query accordingly
ie:

Caused failure:
`http://0.0.0.0:8000/graphql?queryId=get_layouts`

Lookup works:
`http://0.0.0.0:8000/graphql?queryId=get_layouts:1`

Note the `:1`
